### ISSUE TITLE
Datatype Cleanup Buggy

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1008]
**Describe the bug**

As Sander prompted me, I reluctantly confess... :zipper_mouth_face: 

The datatype cleanup editor has several problems. I am the cause of all of them :man_facepalming: :wink: 

When the remove subtypes is checked:

1.  It sometimes takes several passes to remove all the templates. This is not what was intended. This was found by testing larger scd files, removing a whole IED, and cleaning up the unconnected DataType references.
2. It has a hard-coded `MAX_STACK_DEPTH` of 10,000 to ensure there are no recursive references. However, when indexing all templates, to begin with on a decent sized scd file, it is not hard to get close to this on my trial files. Some IEDs have very verbose data models.
3. If `MAX_STACK_DEPTH` is exceeded, it will silently fail. That is not very good. As a minimum, a log entry? Or a console debug statement would seem reasonable.

Additionally, on openscd.github.io the filtering doesn't seem to be working correctly either, items become grayed out rather than removed from the filtered list.

Once the Remove button is pushed, the checkboxes should all become deselected. This also applies to the cleanup and dataset windows.

Point 1 is the slightly complex one. I'm still thinking about it, but I think the point of entry is incorrect. We should start off by something like:

1. Creating an index entry for all datatypes in the DataTypeTemplates section. All entries start with usage of zero.
2. Indexing recursively based on the LNodeTypes which are _not_ selected for removal.
3. After this, those templates used will have a positive value and those without will be at 0.

The tests also need to be a little bit better. The most important one is the LNodeType which has to be treated differently from disconnected DOType, DAType or EnumTypes.

**Comment by Sander3003** [comment]
Thanks for you report @danyill! "I am the cause of all of them" no worries, we will always improve ;)
