### ISSUE TITLE
FCDA order doesn't follow dataset in GOOSE later binding editor

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1016]
**Describe the bug**

I was doing a little testing and noticed that the sort order was unexpected in the later binding GOOSE and SMV plugins.

Using the attached file:

[XAT_Prot2_Base_Configuration.scd.zip](https://github.com/openscd/open-scd/files/9641628/XAT_Prot2_Base_Configuration.scd.zip)

Where a GOOSE message is made including the following dataset:

```xml
<DataSet desc="A dataset for transformer trips" name="Ctl">
    <Private type="Siemens-GUID">9a196dba9bdb402191c79b9e8b78e0c5</Private>
    <FCDA ldInst="ANN" prefix="SVT" lnClass="GGIO" lnInst="4" doName="Ind01" daName="stVal" fc="ST" />
    <FCDA ldInst="ANN" prefix="SVT" lnClass="GGIO" lnInst="4" doName="Ind01" daName="q" fc="ST" />
    <FCDA ldInst="ANN" prefix="INC" lnClass="GGIO" lnInst="13" doName="Ind01" daName="stVal" fc="ST" />
    <FCDA ldInst="ANN" prefix="INC" lnClass="GGIO" lnInst="13" doName="Ind01" daName="q" fc="ST" />
</DataSet>
```

In OpenSCD the order appears reversed on the data attributes.

![image](https://user-images.githubusercontent.com/674783/192161978-f8c766c9-30e3-4227-85fc-1ae7f95f424e.png)

It is correct in the Publisher plugin:

![image](https://user-images.githubusercontent.com/674783/192161971-83495686-bc85-4f99-8b8e-c8ec983da69c.png)

**To Reproduce**

1. Open the attached scd file.
2. Go to Later Binding (GOOSE)
3. View the FCDAs on the left.

**Expected behavior**

The order should follow the dataset order by default.

**Comment by dlabordus** [comment]
Is it not better to have a predictable ordering? 
Because if the order is how it's in the XML, searching can become a issue if someone added them in some random order.

**Comment by danyill** [comment]
> Is it not better to have a predictable ordering?
> Because if the order is how it's in the XML, searching can become a issue if someone added them in some random order.

I think there's a good argument each way but:

* Searching can be done with the search bar?
* The FCDAs in datasets can be ordered by the end user. Shouldn't we respect this a little bit?
* This matters quite a lot when mapping onto protocols which are index based (DNP3) so we're often a bit sensitive to order.
* The order the user puts the information into the dataset may follow an in-house convention (which it does for us).
* Particularly when using an IED where the IEC 61850 names are not intuitive (e.g. SEL), grouping DO/DAs in the dataset makes a large dataset more understandable.
* I'm just used to tools which follow the dataset... SEL Architect does, Siemens does. In the screenshots below I tested by putting a MET LD FCDA at the top of a dataset and both follow this order in presenting the dataset.
   ![image](https://user-images.githubusercontent.com/674783/194393166-bac9a53e-a661-426f-93cf-83de3a6fe3aa.png)
   ![image](https://user-images.githubusercontent.com/674783/194393616-6f44a1fc-4666-4e38-9d50-56ee37b2907a.png)
   And the dataset:
   ![image](https://user-images.githubusercontent.com/674783/194393903-c627c94f-1719-4d56-a2f0-91072019b2de.png)
* It's helpful to UX if tools are a bit similar in this regard?
* In particular I find it confusing if the q of each DA comes before the item in one plugin (GOOSE LB) and after in the other (SV LB).
