### ISSUE TITLE
GOOSE later binding icon for GOOSE Control Block is incorrect

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1017]
**Describe the bug**

In the GOOSE later binding plugin we show GOOSE control blocks with a `S` icon when a `G` would be better.

**To Reproduce**

1. Go to the Subscriber Later Binding (GOOSE) plugin.
2. Look at the messages on the left.

**Expected behavior**

The icon is an `S` when we usually show GOOSE with a `G`.

**Screenshots**

![image](https://user-images.githubusercontent.com/674783/192162497-e3029880-86c9-4179-91fa-f2f0a75055f0.png)

**Comment by JakobVogelsang** [comment]
The fuck how could that slip through... :D. Well sometimes I check only tricky stuff and have no eye on those details. Thank you for noticing.
