### ISSUE TITLE
Reduce clutter in later binding editor

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1024]
**Is your feature request related to a problem? Please describe.**

As a user of OpenSCD I find the later binding information display a bit cluttered or confusing. Also, when I subscribe to an item the item I clicked on changes and the secondary field is quite different.

**Describe the solution you'd like**

I'd like to propose that we remove the information about the subscribing IED from the later binding view.

Currently, it repeats the information available on the left hand pane, tends to be cut off by an ellipsis on a large form factor device and feels visually cluttered. If it is retained I think it must be on a second line or have some iconography to help make it clearer.

See the screenshot:

![image](https://user-images.githubusercontent.com/674783/193383634-560133f5-6687-4d8c-9a28-9cedfdcb0428.png)

`MUSV I01 TCTR1 AmpSv instMag.i` repeats the left hand pane.
`@1-C:MUGO/GOINGGIO1.SPC` repeats the major name.

Additionally when I look at an element before it is subscribed:

![image](https://user-images.githubusercontent.com/674783/193383874-503f4522-1ab9-4af3-8a22-6fc380003857.png)

And after it is subscribed:

![image](https://user-images.githubusercontent.com/674783/193383877-45c90544-72c2-4fbf-b81f-16a69b991b51.png)

I think these should remain the same and that the first is clearer. The user is moving an "available to subscribe" into "subscribed", ideally the display wouldn't change too much.

I can do a PR for this for the later binding SMV and GOOSE plugins if this is acceptable after refinement. Perhaps I don't understand or it is there for another reason.

The other reason I want to reduce the clutter is that I'd like to add some in :stuck_out_tongue_winking_eye: I think we need to show the LN for LGOS and LSVS here at some stage.

**Comment by danyill** [comment]
@Sander3003 can we discuss this during refinement at the next weekly standup?

**Comment by Sander3003** [comment]
Yeah, just bring it in!
