### ISSUE TITLE
Delete empty subnetworks if they are empty after deleting an IED

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1033]
**Describe the bug**

When deleting an IED via the IED editor, if the IED has SubNetworks which only existed in this IED, then these are left behind and result in an empty SubNetwork.

This is schema invalid if I understand correctly, a SubNetwork must have at least one AccessPoint in it:

![image](https://user-images.githubusercontent.com/674783/194004543-dfcd1ab7-aadc-460b-8eb3-2c0414370a69.png)

This can be replicated using the attached file. It has a single IED with multiple SubNetworks. If the IED is deleted then the SubNetworks are empty but still exist without any ConnectAP elements.

[Schema_Valid_B30.scd.zip](https://github.com/openscd/open-scd/files/9713699/Schema_Valid_B30.scd.zip)

This doesn't seem to happen if the IED has a single access point where the behaviour is correct.

I have not looked in detail. I should not be surprised if this is related to the ServerAt directive.

**Expected behavior**

OpenSCD should strive to keep files schema compliant. The user should not worry about this where possible.

OpenSCD should check if SubNetworks have become empty as a result of the deletion event and delete any new empty SubNetworks.

I think OpenSCD does do this correctly where a device is only present in _one_ SubNetwork.

**Comment by Sander3003** [comment]
When you start a new project, if will always start with an invalid schema. Removing a subnetwork because it is empty is not my proference. If the subnetwork needs to be reused for other IED's, if would nice if it can stay.

What we can do is ask the user if he likes to remove the subnetwork as well.

**Comment by Sander3003** [comment]
As discussed today 7 November 2022; In de long run, it would be nice if the user gets an option to fix invalid files. For now, we keep it as it is. It is not a big issue for now.
