### ISSUE TITLE
Make LGOS and LSVS accessible in subscription editors

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1037]
**Is your feature request related to a problem? Please describe.**

When #942 is complete, supervision of subscriptions will be provided.
But it will not be visible to the user.

As a user, I care about this because I want to know:

* Where is this subscription supervised?
* When browsing the SCL object model online, which LSVS or LGOS logical node is associated with the communications of this FCDA or Control Element.

**Describe the solution you'd like**

I would like to see the path to the LN and the LN name and a small icon to indicate supervision, perhaps `monitor_heart`

Perhaps something like one of these for the later binding plugin:

![image](https://user-images.githubusercontent.com/674783/194930585-8b268022-fcc3-4890-8b06-5dea21845602.png)

Perhaps only the LN information could be shown with the fully qualified path being a tooltip.

Another option might be to show only the `monitor_heart` icon with the tooltip being the path and the LGOS name which would reduce clutter. This would mean "this subscription is supervised" and the user would need to hover to see the detail. The icon could be a button which opened the Logical Node editor for the user to access additional details.

In the Subscriber(GOOSE) and Subscriber(SMV) plugins, perhaps it could be on the right.

![image](https://user-images.githubusercontent.com/674783/194931102-0b612ea5-3f5c-4639-bfc4-fd2307ae0663.png)

![image](https://user-images.githubusercontent.com/674783/194931329-fee05345-f332-4a32-b767-5b6bd978f0a9.png)

**Comment by JakobVogelsang** [comment]
I like the proposal to put it as a meta icon into the `mwc-list-item`. I think this will not additionally clutter the list item as it is already. Furthermore, I also would propose to have a tooltip with the identity string of the logical node instance `LN`. I like the icon you have selected `monitor_heart`.

**Comment by JakobVogelsang** [comment]
As discussed in our last refinement session we want to add a indicator for subscription supervision:

**Requirements**
in case there is a subscription supervision for a GOOSE or SampledValue stream
- add meta icon to every list item that indicates a subscribed message/data
- use `heart monitor` from google fonts
- add a tooltip to this meta icon having the identity of the supervision logical node e.g. `IED2>>LD0> LGOS 1` or `IED2>>LD0> LSVS 1`

**Mockup**
![grafik](https://user-images.githubusercontent.com/66802940/196685040-4003c0cc-c8b0-46d2-ba01-949567c7883c.png)

**Comment by ca-d** [comment]
> * add a tooltip to this meta icon having the identity of the supervision logical node e.g. `IED2>>LD0> LGOS 1` or `IED2>>LD0> LSVS 1`

Do you think it may be possible to add that information to the list item text instead (and then maybe have a tooltip for the whole list item as in the current log), or go twoline and put the monitoring IED in the secondary slot? I'd love to have the information more accessible than just in a tooltip.

**Comment by danyill** [comment]
I tend to agree but would like to discuss and resolve #1024 first

**Comment by danyill** [comment]
> Do you think it may be possible to add that information to the list item text instead (and then maybe have a tooltip for the whole list item as in the current log), or go twoline and put the monitoring IED in the secondary slot? I'd love to have the information more accessible than just in a tooltip.

There may also be circumstances under which it would be nice to filter on the supervision node to allow answering the question, "What is this supervision node for?" or more likely "Where is this GOOSE/SV message supervised within receiving devices?"

**Comment by danyill** [comment]
Re-opening for further discussion on https://github.com/openscd/open-scd/issues/1037#issuecomment-1318210510
