### ISSUE TITLE
Export Communication Section Plugin

### ISSUE THREAD

**Issue by ca-d** [openscd/open-scd#1042]
**Is your feature request related to a problem? Please describe.**
As a user of OpenSCD I want to export a bare Communication section without any other information included. There currently is no defined file format for this.

**Describe the solution you'd like**
I'd like a plugin that exports just the Communication section from an scd as a single SCL file.

**Comment by JakobVogelsang** [comment]
I had a look at the file and found that is not valid. The type attribute in the `P` elements is duplicate `IP-GATEWAY`. But that is picky and has nothing to do with what you want to have. Regarding this, I would propose not use any of the SCL type format (scd,icd,iid...) but to make it a xml file to not run into misuse of such a file.
