### ISSUE TITLE
Import IEDs menu item fails to import multiple selected IEDs

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1052]
**Describe the bug**

I try to import multiple merging units on top of an existing file.
Only the first one is imported, possibly not even correctly but there are no obvious errors or warnings.

[Prot1_SCD.zip](https://github.com/openscd/open-scd/files/9868382/Prot1_SCD.zip)

**To Reproduce**

With reference to the files in the zip file.

1. Open the scd file, 'first.scd'
2. Click on 'Import IEDs'.
3. Enter M1 in the filter field, select all IEDs and go import.
    ![image](https://user-images.githubusercontent.com/674783/197997382-17117d82-ca3e-43ab-beb7-58034adf0702.png)
4. Notice only one IED is added (`XAT_T1_M1`).

Note the file is initially schema invalid because the SubNetwork is empty and is schema valid after an IED is imported.

**Expected behavior**

All IEDs should be added.

**System**

 - OS: Ubuntu (also tested on Windows Server 2016)
 - Browser [Firefox (also tested on Chrome)
 - Using openscd.github.io

cfyi @TPChenDNZ

**Comment by JakobVogelsang** [comment]
That's on my sorry. I did a fix here some time ago and obviously the tests were not sufficient
