### ISSUE TITLE
Import IEDs only imports from the first document 

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1106]
**Describe the bug**

When importing IEDs from an SCD file, I have the ability to select multiple scd files.

When I select multiple scd files, only  the first one is processed.

**To Reproduce**

1. Go to Import IEDs menu plugin.
2. Select two files with more than one IED in them.
3. Notice the dialog allows you to select IEDs, but only IEDs from the _first_ file are allowed.

**Expected behavior**

If I am allowed to select multiple files, then I expect either:

1. The dialog to combine all my IEDs from both files in the dialog, or 
2. To receive a dialog for each SCL file, or
3. To only be allowed to select a single file.

I think any of these may be a legitimate option and my preference is in the order listed.

**Comment by JakobVogelsang** [comment]
How often will I break-repair that thing wahr do you think.😂

Sorry for that

**Comment by Sander3003** [comment]
@JakobVogelsang is this fixed now by #1103?

**Comment by JakobVogelsang** [comment]
No, unfortunately I broke-repair it with #1103

**Comment by Sander3003** [comment]
What use-case to you have in mind for this issue?

**Comment by danyill** [comment]
> What use-case to you have in mind for this issue?

Currently we support import IEDs from an existing SCD file.
It's not uncommon to have multiple SCD files in a protection system (e.g. System 1 / System 2).
I can imagine it would be useful to combine these files by selecting all devices from both systems.
Currently if I take two large enough SCD files, it actually flashes up a dialog with the files from one of the SCD files before switching to the other SCD file which is somewhat confusing.

**Comment by JPister** [comment]
Just to note I am interested in the same use case as @danyill. I have a pile of SCD files and when I import them, only some of the IEDs appear. I can work around this by simply going Import IEDs, and selecting the same files multiple times.

**Comment by danyill** [comment]
I think this issue description mischaracterizes the problem.

I can reproduce a behaviour similar to this by:

1. I take 8 SCD files, each with one IED in it, called something other than 'TEMPLATE'.
2. I create a new project, (Edition 2) and then go Import and select all 8 SCD files.
3. Sometimes all 8 are created. Other times only 6 or 7. On a different machine, always 5 or 6 are created.

So the initial description doesn't appear correct and seems to be related to the files specifically used (which were relatively larger files).

An improved description would be: 

* Import IEDs doesn't always import all IEDs from all files
* When it fails there is no Javascript console or log error
* There is often at least one "schema validation failed" error in the log, but it is transient and after that there is always a "schema validation successful"
* There is usually one log message "Imported <IED name>" per successful IED and none for the IEDs that failed

Is our current Action API safe to use with asynchronous calls @ca-d? I worry particularly about the document being swapped out and recreated while a subsequent call is referencing a previous document. I am not sure how best to debug this.

**Comment by danyill** [comment]
I guess this is perhaps one more reason to move toward the Edit API, which might just fix this.

On Linux:

* I find this "easy" to reproduce with Chrome Version 110.0.5481.100 (Official Build) (64-bit), typically it either imports all 9 or sometimes only 7.
* I cannot reproduce this at all with Firefox 112.0b6 (64-bit)

On Windows:

* Pretty consistently missing some IEDs in Chrome when importing more than about 5.

Here are some reproduction files. I create a new IEC 61850 Ed 2.1 project and import al the files in the zip.

[Test_Files.zip](https://github.com/openscd/open-scd/files/11076424/Test_Files.zip)

Another easy way to reproduce:

Within `ImportIEDs.js` around L291

```js
async onLoadFiles(event) {
    const files = Array.from(event.target?.files ?? []);
    const promises = files.map(async (file) => {
      this.importDoc = new DOMParser().parseFromString(await file.text(), "application/xml");
      return this.prepareImport();
    });
    const mergedPromise = new Promise((resolve, reject) => Promise.allSettled(promises).then(() => resolve(), () => reject()));
    this.dispatchEvent(newPendingStateEvent(mergedPromise));
  }
```

And then to reproduce it:

1. Create a new project.
2. Import all the files in the zip file.
3. _But_ before hitting import, place a breakpoint on `return this.prepareImport()`.
4. Allow this to run _once_.
5. Chill for 5 seconds.
6. Allow to run again.
7. Chill again for 5 seconds.
8. Wash, rinse and repeat.
9. At the end, I expect you to only get _one_ of the _eight_ IEDs imported!
