### ISSUE TITLE
ConnectedAP wizard incorrectly populates pTypes from descendant <Address> nodes

### ISSUE THREAD

**Issue by jarradraumati** [openscd/open-scd#1123]
**Describe the bug**
When editing a ConnectedAP using the Communication editor, the `VLAN-ID` and `VLAN-PRIORITY` pTypes are populated with values from a <GSE> node, even when no pTypes are under the ConnectedAP `<Address>` node.

**To Reproduce**
1. Open a project with an IED that has a ConnectedAP containing a GSE/SMV that has `VLAN-ID` and `VLAN-PRIORITY` fields populated, but not within the ConnectedAP <Address>.
2. Click on `Communication`
3. Click on the ConnectedAP within the IED
4. Click edit
5. Scroll down to VLAN-ID and VLAN-PRIORITY
6. See those fields populated with values from the first GSE <Address>
7. Open the SCL xml editor and confirm the ConnectedAP `<Address>` doesn't contain any `VLAN-ID` or `VLAN-PRIORITY` pTypes.

**Expected behavior**
When a ConnectedAP is edited that doesn't contain pTypes, it should not use populated pTypes from descendant GSE/SMV `<Address>` nodes.

**Screenshots**
![image](https://user-images.githubusercontent.com/3224671/211448611-226314f6-8dc2-4f14-85c7-317731625592.png)

![image](https://user-images.githubusercontent.com/3224671/211448637-5196bd96-d2de-4802-b062-47dd4c7b2d9a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 108.0.5359.125 (Official Build) (64-bit)

**Additional context**
I suspect the issue is to do with the `createPTextField` function within the connectedAP wizard. The function at present grabs the first pType under an `<Address>` child from all descendants under the ConnectedAP.

https://github.com/openscd/open-scd/blob/2d1464fa3446d459aa411f82080241ebf0ff379a/src/wizards/connectedap.ts#L325-L338

One way to avoid this is the following:

```ts
.maybeValue=${Array.from(element.querySelectorAll(`Address > P[type="${pType}"]`)).filter(e => e.parentElement.parentElement === element)[0]?.innerHTML ?? null}
```

However this probably doesn't work for some other cases...

Here is a test scd file which you can use to reproduce the issue.

[connectedap_test.zip](https://github.com/openscd/open-scd/files/10378593/connectedap_test.zip)

**Comment by danyill** [comment]
I think we need to just narrow this using [:scope](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope)

What might be adequate is: `:scope > Address > P[type="${pType}"]`

Although I appear to be picking a fight with the tests for some reason which escapes me...

**Comment by JakobVogelsang** [comment]
Hahaha. I was just writing that, but you were quicker @danyill.

Thank you @jarradraumati for this very detailed bug report. I was able to reproduce and fix testwise in a few minutes, and that makes a huge difference.

**Comment by JakobVogelsang** [comment]
The tests for me. There is even one snapshot test that is showing the change. I still would add one simple regression test that is covering this very specific situation. 

@danyill @jarradraumati do you want to give it a shot or shall I?
