### ISSUE TITLE
Substation Editor doesn't handle SubEquipment Functions and SubFunctions element overflow

### ISSUE THREAD

**Issue by jarradraumati** [openscd/open-scd#1129]
**Describe the bug**
When SubFunctions are contained within SubEquipment elements within the `<Substation>` section, OpenSCD does not manage the overflow of content within the element when there are a large number of bays within a voltage level.
This results in icons appear outside of the elements boundary, and obstructs editor menus.

**To Reproduce**
1. Open a scl file that contains SubEquipment with Function and SubFunction elements, and at least one LNode.
2. Click on Substation
3. Scroll down to a SubEquipment with a Function and a SubFunction.
4. Observe malformed elements.

**Expected behavior**
The Substation editor should be able to present all legal elements within a `<Substation>` section without obscuring content, buttons or menus.

**Screenshots**

![image](https://user-images.githubusercontent.com/3224671/212212810-89026eb0-a860-496a-8464-873f264c18ce.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 108.0.5359.126 (Official Build) (64-bit)

**Additional context**

Attached is a ssd which reproduces the issue.

[XAT.zip](https://github.com/openscd/open-scd/files/10407268/XAT.zip)

**Comment by JakobVogelsang** [comment]
Sorry for this inconvenience. I did already provide a fix #1130. If you can, check it out. I would love to hear your opinion.
