### ISSUE TITLE
Add read-only transformer winding editor to substation plugin

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#1131]
As a user of OpenSCD I want to see `TransformerWinding` element in the SCL in the substation plugin

**Requirements**
- make use of `action-pane`
- title is "TransformerWinding.name — TransformerWinding.desc"
- show in all possible parents that is `PowerTrasnformer`
- show all possible children, that is: `TapChanger, `EqFunction`, `LNode` 
- show only with function filter disabled `showfunction=true`

**Comment by Sander3003** [comment]
How does this relates to https://github.com/openscd/open-scd/pull/1073?

**Comment by JakobVogelsang** [comment]
Very right!!!
