### ISSUE TITLE
Don't show null for LNode missing iedName attribute in Substation editor

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1132]
**Describe the bug**

If an LNode has no iedName attribute:

```xml
<Bay xmlns="http://www.iec.ch/61850/2003/SCL" name="Bus_A" desc="Bus A"
    xmlns:sxy="http://www.iec.ch/61850/2003/SCLcoordinates" sxy:dir="horizontal" sxy:y="10">
    <ConnectivityNode name="L1" pathName="XAT/V220/Bus_A/L1"/>
    <Function name="Busbar_Protection">
        <LNode ldInst="BBProtection" prefix="BZ_" lnClass="PDIF" lnInst="1">
            <Text>BusA Dif</Text>
        </LNode>
    </Function>
</Bay>
```

Then the text `null` is shown in the Substation editor:

![image](https://user-images.githubusercontent.com/674783/212402366-ba64937b-b682-47de-adb5-6e7d9795e6ca.png)

We should either show nothing, or "None" to indicate a lack of reference as per IEC 61850-6 Ed 2.1, 9.2.6.

if iedName is set to "None", as shown below:

```xml
<LNode xmlns="http://www.iec.ch/61850/2003/SCL" iedName="None" ldInst="BBProtection" prefix="BZ_" lnClass="PDIF" lnInst="1">
   <Text>BusA Dif</Text>
</LNode>
```

![image](https://user-images.githubusercontent.com/674783/212402924-4e51d78b-17f7-4b7c-a314-07e22f1b9447.png)

which is probably what should occur if it is missing as well.

If the attribute 

**To Reproduce**
1. Open the attached file
2. Go to Substation plugin
3. Enable functions
4. Observe the word null as in the screenshots above.

[XAT.ssd.zip](https://github.com/openscd/open-scd/files/10414812/XAT.ssd.zip)

**Expected behavior**

Not to see null... whatever that is... :wink:

**Comment by JakobVogelsang** [comment]
I would argue that IEC61850-6 does not allow a missing `iedName` so far I know. It is not covered with the schema but is clearly stated in the -6. A `Lnode` referencing to a `LNodeType` only must state that using `iedName="None"` and must have a `lnType` defined.

Are those Ed1 files you have?

**Comment by danyill** [comment]
I think you are probably correct, we can close this - the field were hand crafted and should have included `iedName="None"`.

(I ignore the slightly obscure statement about the missing attribute in the standard:

![image](https://user-images.githubusercontent.com/674783/213037273-45960f39-54e4-4034-8f02-f53e2c4f5f64.png)

)
