### ISSUE TITLE
Provide edit button for EqFunction and EqSubFunction

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1133]
**Is your feature request related to a problem? Please describe.**

In Pro mode, we have an ace editor edit button for most elements in the Substation editor.
Notably, we don't have this for EqFunction and EqSubFunctions

**Describe the solution you'd like**

I'd just like that button because it delights me to quickly jump into the SCL without having to go to a parent container which has the button.

So a button in the top right corner:

![image](https://user-images.githubusercontent.com/674783/212405923-b2f4ea81-6c6a-43de-999c-9fdbfe536812.png)

Like for other containers:

![image](https://user-images.githubusercontent.com/674783/212406035-2a37fbf2-43af-48d3-9de4-eedf34b4ffe7.png)

**Comment by JakobVogelsang** [comment]
That is bug, sorry for that :)
