### ISSUE TITLE
Add multiple `Val` element into `DAI` distinguished by `sGroup`

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#1139]
As a user of the `IED` plugin, I want to instantiate multiple setting group parameters at the same time.

**Requirement**
- if a data attribute is not instantiated, show an add icon on the header of the data attribute container
- given the data attribute `DAI` has the functional constraint `SG` or `SE`
   - change the create wizard to the mock below
   - given setting groups are available at all
     -> the parent `IED` element must have a `SettingControl` element and this an attribute `numOfSGs`
     -  allow to specify a specific setting group for the newly created value `sGroup`
       -> checked `show individual setting groups` (default) 
       - show as many input fields as there are `numOfSGs`, make them required to assure a value
     - allow to specify that the given value is for all setting groups
       -> unchecked `show individual setting groups` 
   - without existing `SettingControl`
     - leave the wizards as is at the moment
- given the data attribute `DAI` has any other functional contraint
   - leave the wizards as is at the moment

Mocks:
- when fc=SG or SE and user wants to set setting groups individualy
![grafik](https://user-images.githubusercontent.com/66802940/213170866-2edc0477-4458-4ff4-ab16-42483bd3b57f.png)

- when fc=SG or SE and user wants to have value for all setting groups
![grafik](https://user-images.githubusercontent.com/66802940/213170889-1e8353a7-67ee-49be-b819-dda2ac8b4d2b.png)

-when fc=SG or SE and not `SettingControl` is defined in parent `IED`
- wizard as is

- when fc!=SG or SE
- wizard as is

**Comment by romdhanisam** [comment]
According to `SCL`, the `SettingControl` element are not allowed in `IED`, they can only be found in `LN0`
1. 2003: https://github.com/openscd/open-scd/blob/main/src/schemas.ts#L1477
2. 2007B: https://github.com/openscd/open-scd/blob/main/src/schemas.ts#L4575
3. 2007B4: https://github.com/openscd/open-scd/blob/main/src/schemas.ts#L8014

**Comment by Sander3003** [comment]
![image](https://user-images.githubusercontent.com/7427358/227514413-a5723f3d-33ad-428a-90a4-742a0f597e3c.png)
 @romdhanisam that is correct, the sgroup can be used in the LN as well.

**Comment by juancho0202** [comment]
How do we check if a `DAI` has a functional constraint of SE or SG?

**Comment by Sander3003** [comment]
How does this relates to https://github.com/openscd/open-scd/issues/149 ?
