### ISSUE TITLE
LGOS/LSVS supervision instantiation counts existing instances incorrectly

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1161]
**Describe the bug**

Currently we check several items as part of instantiating supervisions:

https://github.com/openscd/open-scd/blob/8ebac53bbf86b86e6b8cdb9d79b28957d4a7b5fc/src/editors/subscription/foundation.ts#L355-L378

One of these items is `instantiatedSupervisionsCount`:

https://github.com/openscd/open-scd/blob/8ebac53bbf86b86e6b8cdb9d79b28957d4a7b5fc/src/editors/subscription/foundation.ts#L509-L520

With the following (slightly hand modified IID file), supervisions cannot be instantiated.

[B30_valKind_valImport.zip](https://github.com/openscd/open-scd/files/10670869/B30_valKind_valImport.zip)

The reason for this is that the count function is showing a much larger number of supervisions than exist.

This is because we are counting all `DOI`s which have `DAI`s which have a `Val`. In this particular IED there are many `DOI > DAI > Val` within each `LGOS`.

```xml
<LN lnType="LGOS_4" lnClass="LGOS" inst="1" prefix="">
    <Private type="GE_Digital_Energy_UR LN_UUID">Master_LGOS1</Private>
    <DOI name="NamPlt">
        <DAI name="d" valKind="RO" valImport="true">
            <Val>Ctl</Val>
        </DAI>
    </DOI>
    <DOI name="Beh">
        <DAI name="d" valKind="RO" valImport="true">
            <Val>This logical node's behaviour</Val>
        </DAI>
        <DAI name="stVal" valKind="RO"/>
    </DOI>
    <DOI name="St">
        <DAI name="d" valKind="RO" valImport="true">
            <Val>RxGOOSE1 On operand</Val>
        </DAI>
        <DAI name="stVal" valKind="RO" sAddr="0:1441793,0"/>
    </DOI>
and so on...
```

There are enough supervision instances available, within the `Services` section: `<SupSubscription maxGo="64" maxSv="16"/>`

I think this query needs to be tightened up. When is a supervision instantiated? I think only when a DO `GoCBRef`has a `Val` against the DA `SetSrcRef`.

```
Array.from(subscriberIED.querySelectorAll(`LN[lnClass="${supervisionType}"]>DOI>DAI>Val`))
(396)

Array.from(subscriberIED.querySelectorAll(`LN[lnClass="${supervisionType}"]>DOI[name="GoCBRef"]>DAI[name="setSrcRef"]>Val`))
12
```

I think this change would be sufficient (with appropriate modifications for the control block type):

```diff
const instantiatedValues = Array.from( 
     subscriberIED.querySelectorAll( 
-       `LN[lnClass="${supervisionType}"]>DOI>DAI>Val` 
+      `LN[lnClass="${supervisionType}"]>DOI[name="GoCBRef"]>DAI[name="setSrcRef"]>Val`
     ) 
   ).filter(val => val.textContent !== '');
```

**To Reproduce**

1. Import an instance of the IED included in the above zip file.
2. Include another IED, e.g. the attached: [NR.zip](https://github.com/openscd/open-scd/files/10671066/NR.zip)
3. Try to carry out a GOOSE subscription.
4. No supervision occurs. 

**Expected behavior**

A supervised GOOSE instance should appear with the supervision icon.

**Comment by JakobVogelsang** [comment]
SORRY!!! It is on me @JakobVogelsang
