### ISSUE TITLE
Remove `filtered-list` and use `oscd-filtered-list`

### ISSUE THREAD

**Issue by juancho0202** [openscd/open-scd#1208]
**User Story**

As a dev-user of the open-scd project I would like to have the current distribution use the new `oscd-filtered-list` component instead of the `filtered-list` one, so that the distribution starts to get "decluttered".

**Acceptance criteria**

- The code of the `filtered-list` is removed from this repository
- We have an installed dependency of `@open-scd/oscd-filtered-list` in our package.json
- All the _imports_ of `filtered-list` pointing to a local path are updated to point to `@open-scd/oscd-filtered-list`
- All the html implementations of the list are updated from 
  ```html
  <filtered-list></filtered-list>
  ``` 
  to 
  ```html
  <oscd-filtered-list></oscd-filtered-list>
  ```
- All current tests should pass successfully

**Comment by Stef3st** [comment]
This story is a bit bigger than originally expected. For the implementation to work we also have to take into account all the query selectors that are cast to a List element. This happens a lot in the wizard structure and needs to be corrected aswell

**Comment by Stef3st** [comment]
Not going to implement this in open-scd
