### ISSUE TITLE
Validation of DO Child element DA Triggering Options

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#1213]
**Describe the solution you'd like**
While using Templates extension, DO child element DA are as defined in 7-3 CDC shall have triggering options defined accordingly in the related table. OpenSCD should validate if correct triggering options is selected. 

**Requirements**
Data Type Templates validator also validates triggering options for DO child elements.

**Comment by JakobVogelsang** [comment]
Would it be ok with you to have only the check in the validator? I am asking because so far we want to not be restrictive on what the user can do with SCL elements, but rather notify the user when something is outside the schema/nsd.

**Comment by BurTah00** [comment]
Yes that would be perfectly fine.
