### ISSUE TITLE
Import IED and Open File seems to do an incomplete import of a device

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1217]
**Describe the bug**

Today I was trying to import an IED from a larger SCD file.

The IED had a specific characteristic I was looking for (the presence of `<Val sGroup="1">200</Val>`) against some DAIs.

When I imported it into a new project I was surprised that I could not locate the `sGroup` reference in the IED editor.

I conclude that the Import of IEDs is buggy (may be related to discussions in #1106) and have not been able to determine exactly why. The other option is that this test file is poorly formed (somehow).

**To Reproduce**

[XAT_Prot2_Base_Configuration.scd.zip](https://github.com/openscd/open-scd/files/11093057/XAT_Prot2_Base_Configuration.scd.zip)

1. Create a new project.
2. Go to "Import IEDs"
3. From the attached:  `XAT_Prot2_Base_Configuration.scd`, import the IED `SOM_102_P2`.
4. Go to the IED Editor while in Professional mode.
5. Look at the XML.
6. Search for the value `sGroup`.

Also:

1. Open a new project.
2. Select `XAT_Prot2_Base_Configuration.scd`
3. Go to the IED Editor while in Professional mode.
4. Look at the XML.
5. Search for the value `sGroup`.

**Expected behavior**

The IED should be imported completely and correctly.

**Screenshots**

In original file:

![image](https://user-images.githubusercontent.com/674783/228334330-9f80f7ed-e8f9-4cf7-86ed-b090f0f3d6c4.png)

![image](https://user-images.githubusercontent.com/674783/228333951-b48dddfb-f9dd-45d0-a65d-cfa36a2cc27e.png)

In OpenSCD:

![image](https://user-images.githubusercontent.com/674783/228334575-9dbe2cc3-afde-4a5c-b1d2-e613b2da6c96.png)

**Desktop (please complete the following information):**

(In this case, I suspect the browser may be important)

 - OS: Linux
 - Browser: Chrome
 - Version: Version 110.0.5481.100 (Official Build) (64-bit)

Also replicated in:

- OS: Linux
- Browser: Firefox
- Version: 112.0b6 (64-bit)

**Additional context**

While looking at this, I found that the DOI I am looking for is completely missing and it appears that OpenSCD has simply truncated the data model.

The LN in the XML looks like:

![image](https://user-images.githubusercontent.com/674783/228335343-96c56ea3-2457-4596-8d92-43609c6fee02.png)

The LN in OpenSCD cannot be found.

I thought it would be good to see if this was actually a problem with "Import IEDs" or something else.
I opened the project scd file and found the same issue (can't find the `sGroup` text or the text `SIPROTEC5_1038`) which means I'm now really confused. Perhaps there is something poorly formed in this file.
When I save the project scd file and open it I find the `sGroup` entries are present.

So there appears to be a parsing of the file issue, "somehow" and it is unclear if the issue is within OpenSCD or the file is somehow "pathological".

**Comment by danyill** [comment]
We are saved, this appears to be my user error.
I had two IEDs, one with a name equal to the others description, which caused repeat mishandling :cry:

**Comment by Sander3003** [comment]
Thanks for reporting anyway! This functions needs to run stable.
