### ISSUE TITLE
Change appendChild / prependChild to createActions

### ISSUE THREAD

**Issue by pascalwilbrink** [openscd/open-scd#1220]
In order to make maximum use of the Action API, we should change all the appendChild and prependChild occurrences to createActions.  This is used in OpenSCD and CoMPAS.

This will make sure that the new element will be in the right place.
If a new XSD schema rolls out, we only have to change 1 function, the foundation.

**Comment by pascalwilbrink** [comment]
usages:

connectedAp.ts
subnetwork.ts
editors/subscription/foundation.ts
menu/virtualtemplateied/foundation.ts
wizards/address.ts
wizards/bda.ts
wizards/clientln.ts
wizards/conductingequipment.ts
wizards/da.ts
wizards/reportcontrol.ts
wizards/sampledvaluedcontrolts
wizards/voltagelevel.ts
wizards/subNetwork.ts

**Comment by Sander3003** [comment]
This actions need to be moved to complex actions in the future; Currently, blobs get created.

**Comment by Sander3003** [comment]
@JakobVogelsang will look into the current usage and determine if change is needed.

**Comment by Sander3003** [comment]
It is a bug when undo will result in a missing element.
