### ISSUE TITLE
On rename in IED editor, supervision is not updated

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1224]
**Describe the bug**

Supervision instances (`lnClass` = `LGOS` or `LSVS`) have the control block reference of the publishing device included in the `Val` of the `setSrcRef` `DAI`. For example:

```xml
<DOI name="GoCBRef">
    <DAI name="setSrcRef">
        <Val>XAT_232_M1MUGO/LLN0.Ind</Val>
    </DAI>
</DOI>
```

When we rename the device in the IED editor, this is not updated.

**To Reproduce**

1. Open a file with supervisions.
2. Rename the IED.
3. Check to see if the supervision information is updated.
4. Find that it is not.

**Expected behavior**

When an IED is renamed, the subscribing supervision instances are updated.

If I rename a device from: `XAT_BusA_P2` to `BlueSky`, then I expect the following change in all LGOS or LSVS LNs (to `GoCBRef` or `SvCBRef`)

```xml
<DOI name="GoCBRef" desc="Ref. GOOSE CB">
    <DAI name="setSrcRef" valImport="true">
        <Val>XAT_BusA_P2Bay240_DCB/LLN0.Ctl_1</Val>
    </DAI>
</DOI>
```

to:

```xml
<DOI name="GoCBRef" desc="Ref. GOOSE CB">
    <DAI name="setSrcRef" valImport="true">
        <Val>BlueSkyBay240_DCB/LLN0.Ctl_1</Val>
    </DAI>
</DOI>
```

**Additional context**

We do the renaming in `src/wizards/foundation/actions.ts` in `updateNamingAttributeWithReferencesAction` and call it from `src/wizards/ied.ts` (about L#212 currently).

**Comment by juancho0202** [comment]
For the creation of the text content of a `Val` element in a supervision instantiation we use a fn called `controlBlockReference` in `src/editors/subscription/foundation.ts` L#657

**Comment by danyill** [comment]
I think it is sufficient to, on an IED change:

1. Iterate across all IEDs and all supervision instances
2. For LGOS and LSVS if there is a non-empty `Val` element, check that it starts with the current IED name
3. If it does, it is a candidate for replacement. Store these in a Map (control block reference => supervision element)
4. Filter the candidates with the control block reference generated for all GSEControl/SampledValueControls in the IED to be renamed to check that they match the control block reference keys. If they do, it is a valid supervision reference.
5. Then recalculate and update the supervision's control block reference.

If that seems good, I'm happy to implement.

**Comment by danyill** [comment]
@JakobVogelsang does that seem good to you?

**Comment by trusz** [comment]
As discussed we need input from @JakobVogelsang.

It also somewhat relates to:
- #1313
- #1315

**Comment by juancho0202** [comment]
Maybe for a next story would it make sense to add a UI component that informed the user about all the different places in the SCL document that were renamed as well to ensure accuracy and completeness? @danyill @trusz

**Comment by JakobVogelsang** [comment]
I have created a simple edge case that could be used for testing. When you try to rename the IED `Pub` with the LDevice inst `lisher` you will conflixt with the IED `Publi` with the LDevice inst `sher`. I think the above approach, reconstructing through `ExtRef`s would be sufficient enough. I would make sure to only rename ONE such object reference per GSEControl in the renamed IED.

[changeIedName.scd.zip](https://github.com/openscd/open-scd/files/12725256/changeIedName.scd.zip)
