### ISSUE TITLE
Improve plugin defaults and user interface

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1225]
**Is your feature request related to a problem? Please describe.**

As a user of OpenSCD, I wish my life to be easy. It may even be part of the human condition :wink: 

For discussion and possibly controversially:

I'd like to see a few small changes to meet this end as someone opening OpenSCD for the first time I expect to see simple defaults (a la KDE, "Simple by default, powerful when needed") and some immediately relevant information when opening a file. As a user this makes me feel like I know what is going on.

![image](https://user-images.githubusercontent.com/674783/229604126-5490486c-a93e-4a27-9a62-ca3534b1698a.png)

I suggest the later binding should be the default subscriber plugin, and the others should be disabled (I think it is the most common way to do subscriptions). It is not obvious to hold shift to scroll the tabs at the top (and we don't all have Macs?), and if your screen form factor is unfortunate, you may lose information.

Also, the IED editor should be enabled by default - it adds significant functionality and is now relatively mature.

That would give something like this, which feels clean to me.

![image](https://user-images.githubusercontent.com/674783/229605490-a4e98d77-e7da-4170-b088-7adeb5b1515e.png)

(instead of:

![image](https://user-images.githubusercontent.com/674783/229606680-b0129542-0127-48ad-8ae3-27ae28bd0a90.png)
)

We could also consider enabling the "Compare IED" functionality by default -- it is a frequent operation, and more items in the menu are not a big problem (?). I'd consider that this menu could be reduced by:

* removing undo and redo and relying on the top right of the app
* removing view log and view diagnostics and relying on the top right of the app

![image](https://user-images.githubusercontent.com/674783/229605238-6dbfe5a8-d6f8-41be-97eb-7a39454a33a2.png)

Saving four menu items would be a general decluttering. But this may not be compatible with our (present/future) idea of plugin interfaces (?).

Finally, the substation plugin shows nothing when a user opens a file and "Show/hide" IEDs are not checked, and there is no SSD section of the file. We could do better by either changing the default plugin to the IED plugin or changing the default in this plugin so the user "immediately has some content". So instead of this fairly blank display:

![image](https://user-images.githubusercontent.com/674783/229605946-1154a87f-1162-4795-803d-a56f3364c514.png)

I'd like either:

![image](https://user-images.githubusercontent.com/674783/229606012-25b9db33-c2a9-44d4-af21-18e7c7a1dc19.png)

Or:

![image](https://user-images.githubusercontent.com/674783/229606054-5b444264-5265-472c-bf10-05dcd117db65.png)

**Comment by Sander3003** [comment]
I suggest to keep the substation editor and show the IED's by default.

**Comment by danyill** [comment]
Also related, #1235 and #1236

**Comment by danyill** [comment]
I think we've done the actionable items on the issues, so it can be closed.
