### ISSUE TITLE
Services section missing item

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1227]
**Describe the bug**

Recently I wanted to find the `maxAttributes` for a dataset.

In the Services  section, this would be something like:

```xml
<ConfDataSet max="50" maxAttributes="200" modify="true"/>
````

We have omitted this in our current implementation (I think). I'd expect this to be perhaps on the first page (as not justifying its own page).

Also, I noticed a small error in passing:

```ts
clientServices: {
      readLog:
        parent.querySelector('CientServices')?.getAttribute('readLog') ?? null,
    },
```

`ClientServices` would be the correct spelling.

It is touching all three services `ReportControl`, `GSEControl` and `SamepledValuesControl` it fits best on the first page.

**Requirement:**
- I would propose to add it between `ClientCapabilities` and `Setting Group`.
- add new section labeled `DataSet Configuration`

In element `ConfDataSet`
|       | name | required | type | pattern | default | helper text |
| --- | --- | --- | --- | --- | --- | --- |
|  A | max | yes | unsignedInt | none | number of existing DataSets in the IED | The maximum number of data sets in this IED |
| A | maxAttributes | no | unsignedInt |  none | none | The maximum number of FCDA elements per DataSet |
| A | modify | no | boolean |  | true | Whether DataSet can be modified by SCT |

**Comment by Sander3003** [comment]
@JakobVogelsang will take a look at it

**Comment by danyill** [comment]
Still relevant and requires attention.
