### ISSUE TITLE
Provide ability to see Services section XML

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1228]
**Is your feature request related to a problem? Please describe.**

As a user of OpenSCD I'd like to drop into the XML view of the Services section in Pro mode as is available in other places in the UI.

**Describe the solution you'd like**

I'd like to have a button in the top right corner which brings up the Ace editor and shows the Services section of the file:

![image](https://user-images.githubusercontent.com/674783/229613530-dc5eca3b-2772-406f-929d-43eef0a8a934.png)

**Requirements**

1. Click button.
2. See XML.

**Suggestions for a specific user interaction**

Same UI as used throughout app.

**Comment by danyill** [comment]
Still relevant and requires attention.

**Comment by Sander3003** [comment]
Wish confirmed by others the SGF IEC week 2023.

**Comment by Sander3003** [comment]
Todo:
Update or add screenshot test
Add regression test
