### ISSUE TITLE
Dedupe DOTs

### ISSUE THREAD

**Issue by tamasrusz** [openscd/open-scd#1249]
**Is your feature request related to a problem? Please describe.**
As a specification engineer I want to remove duplications of data object type (DOT) to reduce ambiguity in the data model.

**Describe the solution you'd like**
I have considered the following places for a solution:
1. "Cleanup" plugin
2. "Templates" plugin
3. "Tree Model Creator" plugin (I am not sure how it is called)

**Requirements**
This feature request considers two DOTs equal if their contents are equal.

- must-have: the ability to chose a DOT and point all equivalents' DOT referenced usage to the chosen one
- nice-to-have: remove all dangling DOTs
- nice-to-have: one-click clean up. The same as above but every DOT will be cleaned up
- nice-to-have: OpenSCD's plugin that modify the data model do this automatically

**Suggestions for a specific user interaction**
For the must-have change we are considering to add a menu point to the DOT Editor's context menu:
<img width="50%" src="https://user-images.githubusercontent.com/118465923/235786112-66e85c35-924a-44c7-af5a-c18192495b60.png" />

Furthermore, for an MVP the users can remove every dangling DOTs with the "Cleanup" plugin.

**Additional information**
N/A

**Test Files**
soon

**Comment by Sander3003** [comment]
Based on your suggestions, I would suggest to add the cleanup functionality to the existing cleanup plug-in and expand the functionality to prevent DOT duplications in editing.

**Comment by trusz** [comment]
The problem is solved with a plugin
- source: https://github.com/sprinteins/oscd-plugins.src/tree/main/packages/plugins/type-switcher
- plugin: https://sprinteins.github.io/oscd-plugins/type-switcher/index.js
