### ISSUE TITLE
fcda-binding-list test fails

### ISSUE THREAD

**Issue by Stef3st** [openscd/open-scd#1257]
**Describe the bug**
fcda-binding-list test sometimes fails. It looks like a synchronization/timing issue.

**To Reproduce**
1. run `npm run test:watch` in open-scd
2. Check the results, it doesn't always happen which make it hard to reproduce

**Expected behavior**
Test will always succeed and always have the same behaviour.

**Screenshots**
![image](https://github.com/openscd/open-scd/assets/35229971/42267d68-6c3e-434e-a52c-f7cb98f8847a)

**Comment by Sander3003** [comment]
@danyill has similar experiences

Possible solution: add an animation frame
