### ISSUE TITLE
Highlight IEDs with multiple Access Points

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#129]
For the IEDs which have multiple Access points, it would be nice if clicked on the IED in AP1, the other AP of IED in another subnetwork is "highlighted" to let the user recognize that : "it is actually the same IED with more than one APs".

![APs](https://user-images.githubusercontent.com/78562586/108110106-159c4b80-7093-11eb-9241-12cc91f6b46e.JPG)

Hope it is clear. Thx!

**Comment by JakobVogelsang** [comment]
This is very clear thank you and welcome to GitHub! Would it be enough, if the other `access point` is displayed but disabled within the IED? By the way with #103 you will have an overview similar to the one you are used to.

**Comment by BurTah00** [comment]
I am not sure if the other access point is shown with all communication details, this might be too much. Just highlighting would be enough I guess.
