### ISSUE TITLE
Add bay editor

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#13]
Add a container that displays and manipulates the `bay` element in the substation section of the SCL file.
The following user interaction shall be included
- add conducting equipment of the type CBR
- add conducting equipment of the type DIS
- add conducting equipment of the type DIS with a single Terminal that has a cNodeName="grounded"
- add conducting equipment of the type CTR
- add conducting equipment of the type VTR
- add power transformer element
- edit name and desc attribute of the bay element
- delete the bay element
- add LNode to the bay element  - opens UI to connect and save the bay element in the destination filter
- copy bay structure (excluding the LNode)
- move bay element to any voltage level element in the file

**Comment by c-dinkel** [comment]
Closed by #39
