### ISSUE TITLE
Tooltip for assigned LNs to the conducting equipments

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#130]
Once we discussed this. It would be great to see maybe:

1) a small indicator that a conducting equipment has some assignment, this can be a very small icon or might be changing the color of the conducting equipment slightly. 

Because when you start creating a substation station for a big project you can always get tired and go for a break and then you forgot where you left off.

2) And also a tooltip or any other possibility to see the assigned LNs to that conducting equipment maybe when hovered or in somewhere else.

**Comment by JakobVogelsang** [comment]
The extra icon that is indicating existing connections is a great idea. The second point is worthy to discuss. In my opinion it would make more sense to have something like this #132 instead. What do you think?

**Comment by BurTah00** [comment]
one of them would be helpful. A preview of assignments is needed to see the progress that made. 
Please consider that creating the substation section is a sum of multiple sessions of work. 
For instance I did some for some bays and in the next session I'd like to know where I left off by looking at the assignments summary.

**Comment by JakobVogelsang** [comment]
@BurTah00 I was wondering if the overview in the substation using the filter button for function type elements does somehow satisfy your need to see all `LNode` elements at once? If yes, I would ask you to close the issue :)

**Comment by BurTah00** [comment]
Closed with filter button.
