### ISSUE TITLE
Can no longer save VLAN-ID and VLAN-Priority in Wizard

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#1327]
**Describe the bug**

To my surprise, today I discovered that I can no longer save either VLAN-ID or VLAN-Priority for `GSE` or `SMV` elements.

**To Reproduce**

[testSCL.scd.zip](https://github.com/openscd/open-scd/files/12832357/testSCL.scd.zip)

1. Go to the Communications screen.
    1a.  Either through the Substation Editor clicking on the (G) or (S) and then clicking More (three dots) and Communication
    1b.  Or by going to the Communications editor.
2. Open a GSE. 
3. Enable the Priority and VLAN-ID and enter valid values (e.g. `7` and `3E8`)
4. Click Save. 
5. Re-open and see no changes (or alternatively download and examine the SCL).

**Expected behavior**

When I click Save, it saves...

**Comment by Sander3003** [comment]
Good catch!
