### ISSUE TITLE
Enhance GitHub Actions to only run if the correct project has been changed 

### ISSUE THREAD

**Issue by pascalwilbrink** [openscd/open-scd#1330]
Now that we're migrating to a monorepository, we don't want all the GitHub Actions to be run all the time.
If we enhance the current (and upcoming) GitHub Actions with a filter, we can exclude specific actions to be run when nothing in that directory has been changed.

For example, we don't want to run all the tests when nothing in `packages/open-scd` has been changed.

There's an example in this SO:

https://stackoverflow.com/questions/63822219/how-to-run-github-actions-workflow-only-if-the-pushed-files-are-in-a-specific-fo

**Comment by pascalwilbrink** [comment]
@trusz I'll pick this one up today or tomorrow, small fix

**Comment by Sander3003** [comment]
@trusz is this already fixed?
