### ISSUE TITLE
Allow to load .isd files as well

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#1341]
As a user of OpenSCD I want to load so-called IED Specification Description(ISD) files into the project. Those are at the moment filtered in the file upload dialog.

**Requirements**
- allow loading ISD file extensions wherever an SCL file can be uploaded to OpenSCD
   - Open Project
   - Merge
   - Update Substation
   - Import IEDs
   - Compare IEDs

**Comment by Sander3003** [comment]
The implementation can be found in CoMPAS.

**Comment by Sander3003** [comment]
In terms of testing; add a snapshot test (just HTML). Is this what you mean @JakobVogelsang ?

**Comment by JakobVogelsang** [comment]
> In terms of testing; add a snapshot test (just HTML). Is this what you mean @JakobVogelsang ?

I do not know why I have added the test requirement. Thinking about this, I am not even sure whether this is possible at all
