### ISSUE TITLE
Create a glossary.md

### ISSUE THREAD

**Issue by pascalwilbrink** [openscd/open-scd#1345]
It would be nice to have a `glossary.md` where we can explain some words and maybe start a discussion to have a common idea/agreement on what something means.

Acceptance criteria:

Words to metion:
Wizard
Plug-in
Distribution
Validator plug-in
Menu plug-in
Editor plug-in

Create glossary.md in the main repository (root)

SCL terms are outside the scope

**Comment by Sander3003** [comment]
Words to metion:
Wizard
Plug-in / Extension
Distribution
Validator plug-in
Menu plug-in
Editor plug-in
