### ISSUE TITLE
Assigning the same IOA addrees for Mapping DA of a CDC to a 104 Point

### ISSUE THREAD

**Issue by DavoodSooran** [openscd/open-scd#1348]
**Description of the bug**
When mapping an IEC 61850 Common Data Class (CDC) to an IEC 104 data point in the IEC 104 module, the standard procedure involves clicking on "Add 104 Addresses" and then selecting a Data Object (DO), as illustrated in the image below.

![image](https://github.com/openscd/open-scd/assets/146732918/f81cc7ce-8314-4171-beeb-3d8aa4ca3e33)

Following this step, it is essential to select the appropriate monitoring Type Identifier (Ti) for the chosen DO.

![image](https://github.com/openscd/open-scd/assets/146732918/5b12a485-9af7-454c-b99c-2403619880e9)

After adding the point, a new dialog box containing various parameters will be displayed. At this stage, it is necessary to enter the CASDU number and IOA number. In certain instances, specific DOs within particular CDCs may have more than one Data Attribute (DA). As depicted in the image below, there are five distinct data attributes for which CASDU numbers and IOA addresses must be defined.

![image](https://github.com/openscd/open-scd/assets/146732918/47176dbf-5bf1-44b3-99f7-c457d23f512b)

The key point to note here is that while the CASDU number can remain the same for all the points, it's crucial to assign a unique IOA for each point. Therefore, within the CoMPAS system, it's essential to implement a validation mechanism to prevent users from selecting the same IOA address for different DAs. This ensures that each point is uniquely identified by its IOA address, which is a vital aspect of the mapping process.

It's important to note that the Common ASDU (CASDU) number serves to address a specific entity within the communication network, which can range from a substation to a bay within a substation or even a single Remote Terminal Unit (RTU). Therefore, the combination of CASDU number and Information Object Address (IOA) must be handled with care. 

In cases where there's only one CASDU number designated for an entire substation (e.g., CASDU=1), each IEC 104 point should have a unique and distinct IOA address (e.g., IOA=1, 2, 3, 4, 5, 6, and so on).

On the other hand, when multiple CASDU numbers are allocated within a substation, particularly for each bay (e.g., CASDU=1 and CASDU=2), it is permissible to utilize the same IOA address for both CASDU numbers. For example, CASDU=1 may correspond to IOA=1 from Bay 1, and CASDU=2 could also be linked to an IOA=1 from Bay 2. This flexibility allows for efficient communication and addressing within the substation environment.

**Expected behavior**
CoMPAS should not allow the user to chose the same IOA address for different point as it is shown in the picture below. As it can be seen it the picture below, we have IOA=1 for all the DAs from this DO.

Indeed, it's imperative that CoMPAS enforces a restriction preventing users from selecting the same IOA for different points, as illustrated in the image below. In this instance, all DAs from the same DO share the IOA value of 1, which is a situation that should be avoided to maintain proper data mapping and differentiation.

In scenarios where the same IOA address is employed for different Data Attributes (DAs) within the same CASDU number, the system should ideally generate an error message to alert the user. Examples of such error messages could be:

1. "IOA Address Already in Use"
2. "Duplicate IOA Detected"
3. "Cannot Use the Same IOA for Multiple DAs"
4. "IOA Address Conflict"

These messages would effectively communicate the issue and prompt the user to select a unique IOA address to ensure proper data mapping and avoid potential conflicts.

**Screenshots**

The statement effectively conveys that CoMPAS accepted the usage of the same CASDU and IOA addresses for different Data Attributes (DAs).

![image](https://github.com/openscd/open-scd/assets/146732918/2134ab94-87ab-4bfe-8ae5-01c7639b2c08)

**Comment by DavoodSooran** [comment]
@Sander3003 now it is complete

**Comment by juancho0202** [comment]
Very thorough and detailed so I was able to follow. Thanks a lot Davood!

**Comment by DavoodSooran** [comment]
@juancho0202 please let me know if you need more information.
