### ISSUE TITLE
Fix the misuse of the test framework

### ISSUE THREAD

**Issue by juancho0202** [openscd/open-scd#1349]
Currently our snapshot testing approach has some failing points like removing a test will not trigger any error or alert, same when a person manually updates the snapshot.

**Comment by Sander3003** [comment]
Add example where it went wrong.

**Comment by juancho0202** [comment]
<img width="1727" alt="Screenshot 2023-11-01 at 15 25 31" src="https://github.com/openscd/open-scd/assets/843030/2878d18a-af8f-4581-8359-22d6aa2c075a">

Here is a more specific and existing example of the problem that I'm reporting. Go to the Settings unit test, at the end of the file you will find two snapshot tests both are marked as successful and passing, but if you debug into it you will see in the browser console both of them are failing with AssertionError because the snapshot doesn't match the file on the disk. 

This for me is a deal breaker because as a developer I want to trust the tool I use to execute my snapshot test will let me know AND FAIL everytime that it encounters a discrepancy between the generated snapshot and the files we're committing to main.

**Comment by Sander3003** [comment]
Maybe we can lookup and fix the misuse of the test framework?

**Comment by Sander3003** [comment]
Todo:
Lookup every lookup snapshot
Put the await before it.
