### ISSUE TITLE
Enhance Plugin properties with 2 additional properties

### ISSUE THREAD

**Issue by pascalwilbrink** [openscd/open-scd#1360]
If we want to make OpenSCD adhere to OpenSCD/Core more, we need to align both property lists that are passed down to each plugin.
To do so, we need to add the following properties to OpenSCD:
* docs => List (can be empty for now, since it's not really being used by any plugin)
* locale => Locale of the browser, can be hardcoded for now, or fetched from the settings / browser

**Comment by Sander3003** [comment]
Looks good!
