### ISSUE TITLE
Protocol 104: Change options between different TI's when selecting a DOI

### ISSUE THREAD

**Issue by Stef3st** [openscd/open-scd#1375]
It is possible to be able to select multiple Ti's when adding a DOI. But all Ti's are bound to the same options.

When a DOI is a chosen a wizard pops up where a Ti number can be chosen. Below that are two switches that can be enabled and therefore used, or can be disabled, depending on if a Ti number allows that option. Right now it doesn't matter which Ti number you choose. If there's only 1 Ti number that allows an option, this option will be available for all Ti's in that DOI.

I would like to see a solution that the options are set for the chosen Ti number

**Comment by DavoodSooran** [comment]
@pascalwilbrink @Stef3st @juancho0202
FYI, the “Created Inverted Addresses (Monitor)“ feature is not applicable for the following ASDU/Ti numbers:

<20> := Packed single-point information with status change detection
<38> := Event of protection equipment with time tag CP56Time2a
<39> := Packed start events of protection equipment with time tag CP56Time2a
<40> := Packed output circuit information of protection equipment with time tag CP56Time2a

**Comment by juancho0202** [comment]
**Acceptance Criteria:**
- The inverted switch is succesfully disabled for the numbers provided by Davood
