### ISSUE TITLE
Manage GOOSE service connections

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#139]
As a user of OpenSCD I want to connect GOOSE's  to a subscriber. I want to see if a GOOSE has a valid subscriber and want to edit or create connections. This story is an extension of https://github.com/openscd/open-scd/issues/525. A user should be able to subscribe or unsubscribe IEDs to a specific GOOSE message as shown below.

![image](https://user-images.githubusercontent.com/47896624/152175758-652265ff-113e-42b2-a253-a032897a19a2.png)

On the right side, the subscription 'status' is shown to the user by showing IEDs either in the subscribed or the available to subscribe part. By clicking the '+' sign or the 'x' sign, the user can resp. Subscribe or unsubscribe an IED to a specific GOOSE message.

**Subscribing**
When subscribing, an `Inputs` block should be created, if not present, under the first `LN0` of the IED which is subscribing. In addition, `ExtRef` should be created in the `Inputs` element for each `FCDA` in the dataset. For the `ExtRef`, at least the following parameters should be filled.

Depending on the version of the project, the `ExtRef` attributes shall be set to:

*Ed1 upwards*: 
- `iedName` -> Contains the target IED name (GOOSE publisher IED)
- `ldInst` -> `ldInst` name from the `FCDA` block of the `DataSet` the IED is subscribing to
- `prefix` -> `prefix` name from the `FCDA` block of the `DataSet` the IED is subscribing to
- `lnClass` -> `lnClass` name from the `FCDA` block of the `DataSet` the IED is subscribing to
- `lnInst` -> `lnInst` name from the `FCDA` block of the `DataSet` the IED is subscribing to
- `doName` -> `doName` name from the `FCDA` block of the `DataSet` the IED is subscribing to
- `daName` -> `daName` name from the `FCDA` block of the `DataSet` the IED is subscribing to

*Ed2 upwards:*
- `serviceType` -> "GOOSE"

**Limitations**
The limitation are a bit tricky and are not complete in this story :)

*Ed1 upwards*
1. Creates `ExtRef` must have a unique reference within the same `Inputs` element - unique is the combination of the attributes `iedName`, `lnInst`, `prefix`, `lnClass`, `lnInst`, `doName`, `daName`.

*Ed2 upwards*
2. `Service` element of the subscribing IED can have child `ClientServices` with `goose` that must be set to true. This indicates that the IED can be "client" for GOOSEs - in better term, it can Subscribe on GOOSEs.

*Ed2.1 upwards*
3. `Services` element of the subscribing IED can have child `ClientServices` with `maxGOOSE`: The maximum number of GOOSE messages that an IED can subscribe on. This must be checked before creating an `ExtRef` with new `iedName` attribute in a subscriber IED. 
4. `Service` element of the subscribing IED can have child `ClientServices` with `noIntBinding` set to true. If true, the System Configuration Tool is not allowed to create `ExtRef` elements. Default is false!! Meaning, we can create `ExtRef` elements. See the Tissue that lead to this attribute [Tissue1397](https://iec61850.tissue-db.com/tissue/1397#comment4412) 

> NOT covered by this story yet is the creation of `LGOS` instances and `LSVS` instances by the System Configuration Tool with configuring subscriptions as discussed in some Tissues like [Tissue 1396](https://iec61850.tissue-db.com/tissue/1396) and [Tissue 1401](https://iec61850.tissue-db.com/tissue/1401)

**Comment by Sander3003** [comment]
@Flurb is this solved?
