### ISSUE TITLE
IED doesn't support Functional Naming/ConfldName

### ISSUE THREAD

**Issue by DavoodSooran** [openscd/open-scd#1402]
**Is your feature request related to a problem? Please describe.**

As a 104 Engineer, I aim to modify the **ldName** associated with a particular **LDevice**. Presently, CoMPAS lacks support for this functionality, necessitating the inclusion of ldName configuration within the tool. Below outlines the steps involved in configuring and altering the ldName.

It's important to note that we don't want users to modify the **inst** of an LDevice. Changing the ldInst might create inconsistencies across the entire SCD file. Only modifications to ldName are permitted. 

Another ticket has been created for developing this feature, which can be found below. We've clearly explained how this function can operate in that ticket. Please refer to it for more detailed information. https://github.com/openscd/open-scd/issues/1326#issuecomment-1836913143

**Describe the solution you'd like**

It's crucial to note that the availability of the dialog box is contingent upon the presence of the **ConfLdName** service within the services section of the SCD file. In the event that this service is absent, users should still have access to the dialog box. However, in this scenario, all parameters will be displayed in a grayed-out and disabled state, preventing any modifications. This limited functionality allows users only to view the current **ldName** and **inst** without the ability to make changes. An example of the services section from an SCD file is displayed below.

![image](https://github.com/openscd/open-scd/assets/146732918/eb08e4ab-615c-4247-b16c-dc44705f2cca)

<img src="https://github.com/openscd/open-scd/assets/146732918/ae765bee-f570-4935-ac76-269bd4ed92dc" width="500" height="550">

To provide users with more context regarding the grayed-out ldName, it would be advantageous to include additional information below the **ldName**, similar to the description provided for the **desc** parameter. In the accompanying image, this supplementary information is visible beneath the **ldName**.

In this scenario, a comment similar to the following examples would be ideal:

1- **_IED doesn't support Functional Naming_** 
2- **_IED doesn't support ConfldName service_**
3- **_IED doesn't support Functional Naming (ConfldName service)_**

<img src="https://github.com/openscd/open-scd/assets/146732918/d46b2ba7-4a6a-449a-b70b-c73ca37862ad" width="500" height="550">

**Comment by DavoodSooran** [comment]
@Sander3003 what do you think about it? I believe It would be helpful to include additional information under the grayed-out ldName

**Comment by Sander3003** [comment]
It is done
