### ISSUE TITLE
Add DISCLAIMER.md to packages/openscd/public/xml

### ISSUE THREAD

**Issue by pascalwilbrink** [openscd/open-scd#1423]
Add a DISCLAIMER.md in packages/openscd/public/xml to explain why the CC-EULA.pdf is in here.

1) Create a note stating that no modifications have been made to the NSD files (IEC Code Components)
2) Add a note stating that if any modifications in the NSD files are not allowed, Changes must go via the IEC relevant working groups (TC57).

Also state that the notes are applied to the maintainers, contributors and external downstream users.

**Comment by Sander3003** [comment]
Suggested text:

"Disclaimer:
**CC-EULA License Requirement**: The files within this directory are subject to the CC-EULA (Creative Commons End User License Agreement) license. Users are required to adhere to the terms and conditions specified in the CC-EULA for the use, distribution, and modification of these files.

**NSD Files (IEC Code Components) Unmodified**: It is hereby stated that no modifications have been made to the NSD files (IEC Code Components) in this directory. Users are expected to utilize these files in their original form as provided.

**Modification Restrictions for NSD Files**: In the event that modifications to the NSD files are necessary, it is imperative that any changes comply with the guidelines established by the IEC relevant working groups (TC57). Unauthorized modifications are strictly prohibited. Changes must be submitted through the appropriate channels within the IEC working groups.

**Applicability to Maintainers, Contributors, and Downstream Users**: These notes apply to maintainers, contributors, and external downstream users of the files within this directory. All individuals and entities interacting with these files are bound by the specified license and guidelines, and any deviations from these terms are not permitted.

Please ensure strict adherence to these conditions to maintain the integrity of the files and compliance with the relevant licensing and standards."

**Comment by Sander3003** [comment]
Approved, let's use it!

**Comment by Stef3st** [comment]
fixed in pr #1440
