### ISSUE TITLE
Enhance Term Consistency in OpenSCD UI

### ISSUE THREAD

**Issue by DavoodSooran** [openscd/open-scd#1429]
**Describe the bug**
As a user, I would appreciate consistency in terms within the OpenSCD tool.

We aim to maintain term consistency in the OpenSCD user interface, encompassing aspects such as capitalization, abbreviations, and acronyms. Consistency in naming conventions enhances readability and minimizes the risk of misunderstandings.

For example, the term **Extensions** found in the menu refers to **Plug-ins**. Within the Extensions section, users can add or remove **plug-ins** from the main workspace area of the OpenSCD UI.

The image below illustrates where the **Extensions** features can be found in the tool. At first glance, it may lead to misunderstandings for users in distinguishing between **Extensions** and **Plug-ins**.
![image](https://github.com/openscd/open-scd/assets/146732918/b31adf24-4666-45e3-a71f-961441e38d32)

Upon replacing the term **Extensions** with **Plug-ins**, we anticipate an overview of the menu as depicted in the image below:
![image](https://github.com/openscd/open-scd/assets/146732918/dbcb0541-4a6b-49e0-82fa-bb1753a91316)

**Comment by DavoodSooran** [comment]
@Sander3003 good enough?

**Comment by Sander3003** [comment]
Yes, good for me

**Comment by juancho0202** [comment]
After consulting with @DavoodSooran we agreed on modifying "Plug-in" with "Plugins" instead.
