### ISSUE TITLE
Display LN describtion

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#1431]
**Is your feature request related to a problem? Please describe.**
As a user of OpenSCD I want to show the LN describtion in the IED browser
So I can understand the LN better

**Describe the solution you'd like**
An edit button on the LN's in the IED browser:
![image](https://github.com/openscd/open-scd/assets/7427358/a46fd814-0886-4dac-9b05-06bcc645f1d6)

And an dialog to show and edit the describtion.

**Requirements**
Show and edit LN description fields

**Additional information**
desc is part of the SCL XSD's

![image](https://github.com/openscd/open-scd/assets/7427358/8165d20c-6df1-4fa6-adae-86652fe80e49)

**Test Files**
If possible provide a file that can be used to test the feature and explain what is the outcome of the test with the test file

**Comment by DavoodSooran** [comment]
@Sander3003 Sure I will work on it.

**Comment by DavoodSooran** [comment]
**Is your feature request related to a problem? Please describe.**
As a user of OpenSCD I want to show the LN describtion in the IED browser
So, it gives a better understanding about the LNode.

**Describe the solution you'd like**
At the moment it is possible to see all the necessary information of a Logical Node in the Substation plug-in but the LN description is still missing in that Edit LNode wizard. 
To reach out this dialog box, the desired LNode has to be selected and then by clicking on the Edit icon, this wizard will be appeared. See below in the picture:

![image](https://github.com/openscd/open-scd/assets/146732918/ced899f9-99f1-480a-98b2-3e36edf09764)

![image](https://github.com/openscd/open-scd/assets/146732918/f5245565-bc1b-45c9-b1e9-990a5c120f2d)

Currently, It is not possible to see the same information in the IED plug-in. To have this information and adding the LN description, an edit button needs to be added for the LNodes in the IED browser. An edit button on the LN's in the IED browser can be added as below:

![image](https://github.com/openscd/open-scd/assets/7427358/a46fd814-0886-4dac-9b05-06bcc645f1d6)


| Attribute  | Required or Optional|
| ------------- | ------------- |
| desc | optional |
| iedName | optional |
| ldInst | optional |
| prefix | optional |
| lnClass | required |
| lnInst | optional |
| lnType | optional |



 After clicking on the Edit icon, the below Edit Logical wizard will be apeared. Below 
![image](https://github.com/openscd/open-scd/assets/146732918/0ba8a471-fe06-4aa0-a104-f0bb74606590)



And an dialog to show and edit the describtion.

**Comment by JakobVogelsang** [comment]
Hi you two. I would like to comment on this:
1. I am seeing two-story descriptions and find it very irritating. If the story description is not sufficient we can edit it and when it is hard to adopt I would open a new one and point from this one that it is handled in the new issue. For the reviewer, it is crucial to have a straight forward reference to review against.
2. The wizard that is see is for the element `LNode` as well as the table with the attributes. The element shown in the SCL is the element `LN` and I would add `LN0` as well just as they are close code wise. Now it makes sense to add the description field in the wizard of all three of the element, but I would then split those up.

**Comment by Sander3003** [comment]
Agree @JakobVogelsang it is confunsing to create an new issues if the one is around the same topic.

**Comment by DavoodSooran** [comment]
@Sander3003 Jakob's comment is related to the scenario I added beneath this story. Using Jakob's feedback, I crafted a new narrative addressing the concerns raised in the comment.

**Comment by Sander3003** [comment]
Closed by https://github.com/openscd/open-scd/issues/1465
