### ISSUE TITLE
Add LNode connection container to the substation editor

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#15]
The LNode connection container shall manipulate LNode elements to all substation section elements. 
- as source all IEDs shall be allowed 
- add filter for source IED names
- as destination all substation section elements up to the conducting equipment level shall be possible
- add filter for source element (use CSS pattern: substation name > voltage level name > bay name > conducting equipment name)
- show example filter in the textfield
- show default logical nodes for specific element (conducting equipment of type CTR,VTR,CBR,DIS)
   - for conducting equipment of type CBR: CILO,CSWI,XCBR
   - for conducting equipment of type DIS: CILO,CSWI,XSWI
   - for conducting equipment of type CTR: TCTR
   - for conducting equipment of type VTR: TVTR
- otherwise show the complete data model up until the logical node level as a tree with all nodes folded as default

Allow following user interaction in the editor:
- create LNode 
  - only when substation element and logical node are selected 
  - if filter for destination leaves one possible element this a valid selection
- delete LNode
  - only if LNode is selected 

`Note`: Visualize LNode in subequipment as well but not allow to add/delete LNodes to subequipment

**Comment by c-dinkel** [comment]
Was closed by #38
