### ISSUE TITLE
Subscribing on minimal ExtRef definition

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#1532]
As a user of OpenSCD I want to be able to see already existing subscriptions in OpenSCD in all circumstances. At the moment when an `ExtRef` element has missing `srcLNClass` and `srcLNInst` is interpreted as unsubscribe. That however is incorrect as 
described here.

<img width="635" alt="grafik" src="https://github.com/openscd/open-scd/assets/66802940/75c7524c-bc0e-44d4-b5db-d002bcae9ecc">

**Acceptance Criteria**
On checking existing subscriptions, the existing rules must be extended so that:
- have `srcLNClass` defaulting to `LLN0` when missing
- have `srcLNInst` defaulting to empty string when missing

**Example**
`<ExtRef iedName="AA1E1Q01BCU" ldInst="MV" ... srcLDInst="LD0" srcCBName="gcb"  serviceType="GOOSE" />` must be interpreted as
`<ExtRef iedName="AA1E1Q01BCU" ldInst="MV" ... srcLDInst="LD0" srcLNClass="LLN0" srcLNInst="" srcCBName="gcb"  serviceType="GOOSE" />`

**Comment by Sander3003** [comment]
What plug-ins are affected in this issue?

**Comment by pascalwilbrink** [comment]
On which `plug-ins` does this occure?
- Later binding / message binding
- Goose / SMV

**Comment by JakobVogelsang** [comment]
It could appear in all the six subscriber plugins:

- Later binding (GOOSE)
- Later binding (SMV)
- Message binding (GOOSE)
- Message binding (SMV)
- Data binding (GOOSE)
- Data binding (SMV)

**Comment by JakobVogelsang** [comment]
The problem is likely to be found here:

<img width="648" alt="grafik" src="https://github.com/openscd/open-scd/assets/66802940/9cca61b0-2702-40a7-b3b0-c361a7e495f7">

Here, a query is constructed with the assumption that `srcLNClass` and `srcLNInst` are not empty.

**Comment by clepski** [comment]
The part in `packages/plugins/src/editors/subscription/foundation#getExtRef` is being used in the Message binding plugins

**Comment by JakobVogelsang** [comment]
@clepski this would be the file for the regression test. It has SMV and GOOSE services linked to the ExtRef and both would fail to show correct subscription at the moment.

[dafaultSrcLNClassSrcLNInst.scd.zip](https://github.com/user-attachments/files/16140670/dafaultSrcLNClassSrcLNInst.scd.zip)

**Comment by Sander3003** [comment]
@DavoodSooran can you validate this story?

**Comment by Sander3003** [comment]
I suggest to close this issue and create an new issue and pull-request for the following finding: https://github.com/openscd/open-scd/issues/1556
