### ISSUE TITLE
Data Picker Fails to Add Data Attribute for Creating Sampled Value Control Blocks

### ISSUE THREAD

**Issue by DavoodSooran** [openscd/open-scd#1566]
As a user of OpenSCD, I want to create Sampled Value Control Blocks. All steps work fine except for the final step, which involves adding Data Attributes. After clicking on the LDevice, we expect to see a list of LNodes. Then, by clicking on a LNode, a list of the supported DOs should appear. Finally, by clicking on each DO, all possible Data Attributes should be listed, and the user should be able to select them.

Currently, it is only possible to see a list of LNodes supported by each LDevice. From this point, the process does not proceed further, and the system does not display the subsequent levels, including the Data Attributes. Please see the image below:

<img width="500" alt="grafik" src="https://github.com/user-attachments/assets/4864359a-d98e-4b3e-82bb-cf09af5f3535">

The correct way to select multiple Data Attributes is as follows:

![image](https://github.com/user-attachments/assets/b39ff27d-1a56-4ad9-9610-4d8799410624)

**Comment by Sander3003** [comment]
@JakobVogelsang can you give a status update of your investigation?

**Comment by DavoodSooran** [comment]
@Sander3003 I just remembered that the issue was related to the SCL file. The reason the data picker does not display further information, such as Do and DA, is that the required DO (Data Object) is not defined or supported for the IED and LDevice.

**Comment by Sander3003** [comment]
@DavoodSooran thanks, we can close the issue.
