### ISSUE TITLE
IED import does not work properly on TEMPLATE IEDs

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#157]
`IED`'s imported from the icd file usually do not contain meaningful names, yet, but use the placeholder `TEMPLATE`. Import function however does not allow to add an IED with name existing in the project.

**Comment by BurTah00** [comment]
Hi Jakob, this is an important issue when importing .icd files. They are all TEMPLATEs. I had the same issue.

**Comment by JakobVogelsang** [comment]
Thanks you for this comment. We have it in the Milestone till 14-05 and will fix it until then.
