### ISSUE TITLE
Support the Editing API v2

### ISSUE THREAD

**Issue by clepski** [openscd/open-scd#1576]
**Is your feature request related to a problem? Please describe.**
As a plugin developer I want to use the Editing API v2.

**Describe the solution you'd like**
Open SCD should support the Editing API v2.

**Requirements**

- Edit Events conforming to API v2 should be applied the SCD file and create the usual history entries

**Suggestions for a specific user interaction**

The code for the API v2 is already present in the old Editing Mixin, see https://github.com/openscd/open-scd/blob/main/packages/core/mixins/Editing.ts
We should transfer this code to the Editor Addon https://github.com/openscd/open-scd/blob/main/packages/openscd/src/addons/Editor.ts and support both Editing v1 and v2. The editing code needs to be tested.

**Comment by michelguerin** [comment]
See https://github.com/openscd/open-scd/pull/1581 - In review
