### ISSUE TITLE
Enable Publisher plugin from transpower in open scd

### ISSUE THREAD

**Issue by clepski** [openscd/open-scd#1596]
**Is your feature request related to a problem? Please describe.**
As a user I want to able to use the publisher plugin from the [transpower distribution](https://danyill.github.io/scl-editor/).

Pluging source: https://danyill.github.io/scl-editor/plugins/oscd-publisher/oscd-publisher.js

**Describe the solution you'd like**
For the plugin to work we need to adjust open scd to be closer to the agreed upen core specs (https://github.com/OpenEnergyTools/open-scd-core/blob/main/API.md).

**Requirements**

- The publisher plugin can be imported and is working as intended

**Necessary steps**
- Add global styles accoring to the core API specs
- Handle openenergytools edit events v2 (which are slighty different from open scd edit events v2)
- Fix or add icons (material icons vs material symbols)
- Check for bugs resulting from conflicting mwc versions

**Comment by Sander3003** [comment]
Looks good, do you have a plan where to commit these changes? Maybe you can bring it for refinement tomorrow.

**Comment by clepski** [comment]
> Looks good, do you have a plan where to commit these changes? Maybe you can bring it for refinement tomorrow.

Here is a PR with demo environment https://github.com/openscd/open-scd/pull/1598, we can discuss changes in the refinement tomorrow
