### ISSUE TITLE
Tooltip for conducting equipment selection in substation section 

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#174]
When clicked on a conducting equipment, the icons does not have a tooltip when hovered.
Please add related tooltips that I don't have to write the meanings down somewhere until I memorized them. 

![image](https://user-images.githubusercontent.com/78562586/114837205-c09b5e00-9dd3-11eb-8985-4298227adf8c.png)

**Comment by JakobVogelsang** [comment]
I think this can be closed for now as we can see all `LNode` elements with `show functions`. Is that true @BurTah00

**Comment by BurTah00** [comment]
yes that is absolutely true @JakobVogelsang
