### ISSUE TITLE
Chrome compatibility

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#183]
Can we say that Chrome is not supported atm? I see that any tab and buttons are not visible in Chrome.

**Comment by JakobVogelsang** [comment]
Hi, it works perfectly fine with mine. Can you please reload and maybe reset in the extentions menu. If still not working can you please share the version of Chrome you are working with.

**Comment by BurTah00** [comment]
Okay. It is about disabled extensions. Somehow I disabled the extensions for Chrome. Thanks :)
