### ISSUE TITLE
Investigate use of NSD files

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#199]
The standard provides files in the format `NSD`. Those file contain machine readable information of the parts 7-2, 7-3, 7-4 and 8-1. Their use would benefit OpenSCD and especially the `Template` editor. For this reason check if 
- the use of those file is allowed in an open source project
- which information in detail can be subtracted form those files

**Comment by keith-gray-powereng** [comment]
The EULA can be found at http://www.iec.ch/CCv1.

**Comment by Sander3003** [comment]
In the CoMPAS community, we are planning to add the XSD's in a separate repro: https://github.com/com-pas/compas-scl-xsd. This to be clear that the XSD is using a diffent license.

**Comment by JakobVogelsang** [comment]
Does that mean we can use *.nsd files in the same way we already use the schemas?

**Comment by Sander3003** [comment]
I currently don't know the difference of the .nsl and .xsd files.

**Comment by keith-gray-powereng** [comment]
@Sander3003 The .xsd files describe how the SCL (.cid, .iid, .icd, .scd, etc) can be constructed using the allowed XML elements, their attributes, and their containment in other elements.

The .nsd files are an XML file format, separate from the SCL files, that describe the Logical Nodes and their data attributes/data objects in a machine-processable format.

**Comment by JakobVogelsang** [comment]
We will use the `NSD` files for two perposes. 
1. Create a data validator that shows validity against 61850-7-2, 61850-7-3, 61850-7-4 and 61850-8-1
2. Use NDS files for special wizards 

Both functionality will only work with the newest version of the NSDs and will only work for the newest schema version that is `2007B4`.

There will several new stories where you can track the development.
