### ISSUE TITLE
Max. Number of Clients check for ClientLN assignment of Reports

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#203]
Hi,
In a training with colleagues from US & LA, we discussed this feature.

From SCL it is clear to get the info for maximum number of clients for Client LN assignment to a report control block instance.
OpenSCD should only allow up to this number for client LN assignment of an RCB, not more.

Thanks!

**Comment by JakobVogelsang** [comment]
This is very true and will come with other functional validation in the IED section. How urgent is this issue? We plan to add this Aug/Sep.

**Comment by BurTah00** [comment]
no so high priority. Just to verify that it'll be implemented.

**Comment by ca-d** [comment]
> no so high priority. Just to verify that it'll be implemented.

@JakobVogelsang added this last week, the feature is part of the current version 🎉 .
