### ISSUE TITLE
Check for `SwTyp` when displaying conducting equipment

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#267]
As a user of OpenSCD I want to see the type of disconnector I am working on. 

1.) If conducting equipment of type `DIS` is connected to a logical node `XSWI`
2.) You can get the `SwTyp` data object of `XSWI` which is an enumeration and mandatory
3.) And from that the `stVal` data attribute that CAN have a pre-defined `Val` which ultimately gives you more information about the type

**Comment by danyill** [comment]
I'll take a look at this.

**Comment by JakobVogelsang** [comment]
Is implemented!
