### ISSUE TITLE
fix(sw.js): deliver consistent versions of js files

### ISSUE THREAD

**Issue by ca-d** [openscd/open-scd#272]
CoMPAS reported our service worker sometimes delivering an old version of one `js` file from cache while loading a new version of another `js` file from the remote host.

**Comment by JakobVogelsang** [comment]
@dlabordus Is still an issue?

**Comment by Sander3003** [comment]
This might be already fixed by @dlabordus; it needs to be tested if it works

**Comment by Sander3003** [comment]
With the latest release, it looks fixed.

**Comment by Sander3003** [comment]
Looks good for now.
