### ISSUE TITLE
Feature request, delete unused (not referenced GCBs)

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#290]
It is the case in MICOM Px40 series IEDs have no dataset referred or not defined in the communication sections GCBs. 
Each case I have to delete this GCBs manually by hand. 
Could you introduce a feature that deletes the GCBs if they have no dataset reference or they are not defined in the communication section or ...... (this can be extended with irrelevant cases that creates problem in StationScout) ?

Thanks!

**Comment by JakobVogelsang** [comment]
I was thinking already about something like that. I would call it `clean up`. Can be used for report as well as sampled values and GOOSEs.

**Comment by BurTah00** [comment]
Hi Jakob, could you give a rough date for this feature?

**Comment by JakobVogelsang** [comment]
Hi Burak, sorry for the delay. I have prioritized this issue a bit higher. But being hones with you, I don't think we can make it until mid-December. I am confident however, we can include it until the end of the year. Do you have other suggestions for this `cleaning-up` feature? So far I can think of:
- GSEControl with no or invalid `datSet`
- SampledValueControl with no or invalid `datSet`
- DataSet that a not referenced by any control block
- `LNode`s that are invalid reference
- `LNodeType`, `DOType`, `DAType` and `EnumType` that are not referenced

**Comment by BurTah00** [comment]
Hi Jakob, they are all fine and have use cases for different vendor implemantations.
What this story should not cover is:

-RCBControl with no  `datSet`

These RCBs would be filled out via a Client who creates a dynamic dataset.
Other than that your proposals make me happy.

**Comment by danyill** [comment]
> @BurTah00 can you check if the clean-up tool of @danyill works for you?

Regrettably, the first task was not the one that was requested here (it's always the way). I'll do that next. I promise :handshake: 

> What this story should not cover is:
> -RCBControl with no datSet
>These RCBs would be filled out via a Client who creates a dynamic dataset.

As long as you can clearly see it's a ReportControl and filter on it this should be OK. Some will want to remove unused ReportControls and others will be using a dynamic allocation via the client.

**Comment by BurTah00** [comment]
Hi,
@danyill thanks, I'll check this week hopefully when I have some time. Sorry for the delay.
You are right, RCBs with no datSet should not be wiped out, even I don't enjoy seeing crazy URCB101.....120 BRCB101...120 series in SIEMENS IEDs. That's the game...
Thanks again!
