### ISSUE TITLE
Display SCL tHistory

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#295]
As an engineer
I want to see the tHistory items in the SCL file
So I can know the history and know what is changed

Acceptance criteria:

- Window for displaying the history
- Editor plug-in or part of the log functionality
- Display all 61850 tHistory items

**Comment by JakobVogelsang** [comment]
We have discussed this issue in our last sprint meeting and are very happy to make a joint effort here. Thanks for that! 

We would like to add this feature to the already existing `log`. The reason is that we want to serialize editor actions into the `Hitem` to be able to undo even after file re-open. 

This however would be in conflict with the second acceptance criteria of yours. Instead of having a separate plug-in we suggest having another toggle button in the log.  This allows to filter for `Hitem` added by tools other than OpenSCD and also allows you to filter for only `Hitem`s added by other tools. Would that be acceptable for you, too?

**Comment by Sander3003** [comment]
It is imported for me that engineers can read the tHistory items in an easy manner. A seperate plug-in is not a hard requirement. Part of the log functionality can work fine.

**Comment by JakobVogelsang** [comment]
Perfect! 

The element `Hitem` does contain several attributes with the following requirement:
## Restrictions
| Attribute | Type | Required | Description |  
| --- | --- | --- | --- | 
| version | xs:normalizedString | yes | might be used every time you save a file |
| revision | xs:normalizedString | yes | might be incremented for every change/action |
| when |  xs:normalizedString | yes | Time stamp |
| who | xs:normalizedString | no | This is the attribute that distinct if the `Hitem` is owned by OpenSCD or not |
| what | xs:normalizedString | no | ... |
| why | xs:normalizedString | no | ... |

## Requirements
- Hide `Hitem` that either does not have `who` or `who` is not `OpenSCD` per default - new toggle button.
- Try to parse the `when` to the already used time stamp. If not possible, do not display the time stamp.
- The order of the `Hitem` is the opposite to the one in the `History`. 
- Use `twoline` [mwc-list-item](https://github.com/material-components/material-web/tree/master/packages/list)  component. The primary span could be whatever is the `what`. The secondary span could be whatever is `who`: `why`
 
I will create the two SVG images for switched on/off history

**Comment by Sander3003** [comment]
Do you suggest a button in the Log section for opening the tHistory items?
https://user-images.githubusercontent.com/7427358/131678285-4945c7f2-cded-48ff-b5fb-16a0f1e190d7.png

Or a seperate item in the menu?

![image](https://user-images.githubusercontent.com/7427358/131714419-79ed6e93-3f85-40e7-a09d-882f04b26f4b.png)

**Comment by JakobVogelsang** [comment]
Our favorite would be the first solution.

**Comment by JakobVogelsang** [comment]
Yes this is a good idea. Sorry it is a short description.

**Comment by ca-d** [comment]
Instead of having the fifth toggle button filter the list by `who === 'OpenSCD'`, we could filter by `who.endsWith(' (OpenSCD)')`.

**Comment by Sander3003** [comment]
When you click on a tHistory item, a seperate window will show the RAW tHistory data (per tHistory item).

**Comment by dlabordus** [comment]
Hi @JakobVogelsang, 
Did you already had time to create the SVG images for the new Switch?

**Comment by JakobVogelsang** [comment]
Hi @dlabordus 
I am sorry no. Or to be more correct not complete. I will give them to you this afternoon. I am sorry my time scedule was rugh :( .

**Comment by JakobVogelsang** [comment]
Hi @dlabordus 

This is my suggestions. 

```
<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 24 24"
  height="24"
  width="24"
  slot="offIcon"
>
  <path
    d="M 2 9 L 12.5 2 L 23 9 L 21 9 L 21 21 L 4 21 L 4 9 Z"
    fill="transparent"
    stroke="#657b83"
    stroke-width="2"
    stroke-linejoin="round"
  />
  <path
    d="M 11 7 L 17.5 7 L 13.5 11 L 16.5 11 L 10 19 L 11.5 13 L 8.5 13 Z "
    fill="#657b83"
  />
</svg>
```

```
<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 24 24"
  height="24"
  width="24"
  slot="onIcon"
>
  <path
    d="M 2 9 L 12.5 2 L 23 9 L 21 9 L 21 21 L 4 21 L 4 9 Z"
    fill="transparent"
    stroke="#6c71c4"
    stroke-width="2"
    stroke-linejoin="round"
  />
  <path
    d="M 11 7 L 17.5 7 L 13.5 11 L 16.5 11 L 10 19 L 11.5 13 L 8.5 13 Z "
    fill="#2aa198"
  />
</svg>
```

As a description: The `mwc-toggle-button` allows you to add two `svg` and to slot them with either `onIcon` or `offIcon`.
