### ISSUE TITLE
fix(substation): "Show IEDs" toggle button has the same icon in "on" and "off" state

### ISSUE THREAD

**Issue by ca-d** [openscd/open-scd#301]
The toggle button doesn't represent the current state of the "Show IEDs" setting.

**Comment by JakobVogelsang** [comment]
This is very strage. For `openscd.github.io` it works on my machine. Does the icon change at all?

**Comment by JakobVogelsang** [comment]
You cannot believe. Had the same issue, not with the review of #312. I could reproduce it on my machine and it seems to be a bug in `icon-button-toggle`
