### ISSUE TITLE
Add documentation on Substation update

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#304]
As an User,
I want to find out what the update substation function does in the documentation
So I can use it with confidence
![image](https://user-images.githubusercontent.com/7427358/132523908-6317838c-15ad-4c79-a4b7-aff5921447e3.png)

Acceptance criteria:

- Explanation on the update substation function in the manual
- Difference with Merge project and import IED function

**Comment by JakobVogelsang** [comment]
Hi Sander,

thank you for the hint. You are absolutelly rigth we are behind user documentation. I am at the moment writing it and will cosider this as well. You can already see new pages in the wiki. There will be a RP to have it in the help of OpenSCD as well.

BR

**Comment by Sander3003** [comment]
Thanks for your work! To improve CoMPAS/OpenSCD, it is nice to know what is already build ;)

**Comment by JakobVogelsang** [comment]
I have updated the [Merge wiki](https://github.com/openscd/open-scd/wiki/MergeFunctionality) and gave you some insights the difference between `MergeProject` and `Update Substation`.

**Comment by JakobVogelsang** [comment]
An extra PR will follow to add this to `Help`.

**Comment by Sander3003** [comment]
https://github.com/openscd/open-scd/wiki/Merge-functionality Thanks @JakobVogelsang
