### ISSUE TITLE
Epic: SLD editor [PLACEHOLDER]

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#309]
**This are the first idea's:**
Show only one substation (select one)
Seperate editor (not part of the existing, non-diagram editor)
Autogenerate the diagram lay-out (Using RTE code? / lookup in other system how to do this)
Ability to use HMI coordinates 
Display terminal (click / hover if clicking is not possible)

Adding primary equipment is not allowed (use the substation editor)
Move equipment around the diagram
Connect and modify terminals and connectivity nodes (and show id's)

Research:
1 pan zoomable libary (CIMdraw?): Omicron (Webcomponent required)
2 Check the status of the 61850-6-2 DRAFT: Useable?2 How to put the X and Y coordinaties into SCL (@JakobVogelsang can add an example of the "old" methode)
3 autoallign: Ask RTE

Steps:
Create an editor plug-in
Use the 61850-6-2 (read-only)
Draw diagram 
Automate alignment

**Comment by Sander3003** [comment]
PowSyBl project might have a auto route option.

**Comment by Sander3003** [comment]
Related issues: #310 #311 #313

**Comment by JakobVogelsang** [comment]
I opened a new project for us to have a better overview while working together and moved your notes to the project description. 
One more closed issues ;)
