### ISSUE TITLE
Investigate: Panzoomable component for SCL 

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#310]
Other than in the `Substation` editor, the `SLD` need another user interaction strategy. A zoomable pane and ideally a web-component would be great. 

Here we can collect and discuss the suggestions.

**Comment by Sander3003** [comment]
https://openbase.com/categories/js/best-javascript-canvas-libraries

**Comment by Sander3003** [comment]
http://fabricjs.com/ was used for the schema composer https://github.com/alliander-opensource/schema-composer

**Comment by Sander3003** [comment]
@ca-d can you add your insights on this topic?
