### ISSUE TITLE
Show elements in single line diagram

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#334]
As a user of OpenSCD I want to see all defined `ConductiveEquipment`, `PowerTrasnformer` and bus bar in the single line diagram.

**Requirements:**
- The bus bar is not a defined element within the IEC 61850-6 but shall be a `Bay` element with a single! `ConnectivityNode`.
- Try to reuse the existing svg icons from the icons.ts
- Set normalized width and height to 50px

**Comment by Sander3003** [comment]
@JakobVogelsang can you add this to https://github.com/openscd/open-scd/projects/7?
