### ISSUE TITLE
Add auto allignement function for 61850 SLD

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#344]
As an engineer,
I want to auto allign IEC61850 single line diagram incase it is lacking coordinates
So I can read the schema's easily

Background:
IEC61850 files sometimes don't contain any coordinate systems. 
To test  and show the conversion from IEC CIM to IEC61850 it is needed to show the single line diagram in a readable way. 

In case of complexity consider starting to work in this order:
Allign on bay, voltagelevel and substation.

**Comment by Sander3003** [comment]
FYI CoMPAS: https://github.com/com-pas/compas-open-scd/issues/100

**Comment by dlabordus** [comment]
For now the auto alignment functionality will only be build in the CoMPAS version of OpenSCD (https://github.com/com-pas/compas-open-scd).
This will use a back-end Services (https://github.com/com-pas/compas-scl-auto-alignment) to calculate these using PowSyBl.
Later can be decide to convert this services to a front-end functionality using a WebAssembly.
