### ISSUE TITLE
Update lit-element and lit-html to lit2.0

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#359]
This step has been done by all dependencies and dev dependencies in our project, and we should do it too. Mainly because open-wc is using it already but also because material web components cannot be used in their latest release without this step. This is what we have to do:

1.) Update import statements. Decorators are now allocated under `lit/decorators`
2.) Change `internalProperty` to `state`
3.) Change user-defined directives. `ifImplemented` in our case
4.) Adapt some API change of material web components. So far I have seen this with `mwc-switch`. E.g. the property `checked` was changed to `selected` and the `@checked` does not work any more either.

**Comment by Sander3003** [comment]
@dlabordus does this impact LF energy CoMPAS?

**Comment by JakobVogelsang** [comment]
Will be done with within `open-scd-core`
