### ISSUE TITLE
Display LN instances

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#363]
As an engineer
I want to see what logical nodes instances are inside a substation configuration
So I can see what kind of protection, measurements etc are configured.

Example by @JakobVogelsang:
![IED-editor](https://user-images.githubusercontent.com/7427358/140758500-5d53a845-305f-42e4-beee-346452455ebf.PNG)
:

**Comment by JakobVogelsang** [comment]
@Sander3003 can be closed rigth?

**Comment by Sander3003** [comment]
yes!
