### ISSUE TITLE
Display IED data attributes description

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#364]
As an engineer
I want to see the data objects description
So I can see how e.g. Measurements are configured

Background
With increasing congestion, it is imported to know how measurements are being configured and calculated to prevent misinterpretation.

Placement of an info icon:
![image](https://user-images.githubusercontent.com/7427358/151178296-9875494e-f892-44ef-9bd3-7e417734bd31.png)

Acceptance criteria:
Show the common data class

**Comment by randy993** [comment]
@Sander3003 What do you mean with setting and values? DO's by any chance? In that case, isn't this a duplicate of 390/425?

**Comment by Sander3003** [comment]
This is already fixed by uploading the nsdoc files
