### ISSUE TITLE
Increase padding in communication screen to see buttons and IED names

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#375]
In the communication screen at the moment there is insufficient padding to see the IED name or the interface buttons when there is a reasonable number of IEDs:

See screenshot (Firefox) from the current `main` branch:

![image](https://user-images.githubusercontent.com/674783/141531623-3a9df2f1-16fc-4829-a44b-f38c0f17bb22.png)

**Comment by danyill** [comment]
Adopting a similar layout as the Communication tab might be one good option:

![image](https://user-images.githubusercontent.com/674783/141531900-b1b4d359-70a0-4486-ad64-26fea2b6a817.png)

**Comment by JakobVogelsang** [comment]
Hi thanks for the comment, 

You are right and it is unfortunate this is the case at the moment. Just so that you can track it: We are already on it. The branch `action-icon` is a common web-component that we will be used for everything where actions are hidden behind an icon. With this we want to make sure that we have a common UI. This I think will solve the issue.

**Comment by JakobVogelsang** [comment]
This is now in main. We have added some other styling and are very curious about your feedback.

**Comment by danyill** [comment]
I'm really impressed, good job on the new styling :+1: it feels clean and fresh 

It's probably not great commenting on a closed issue and I do not wish to nitpick (!) but I would prefer enough padding to see IED names with up to say, 12 characters as a minimum. For our in-house naming we typically have:

* 3 characters for a substation
* 4 characters for a bay
* 2-3 characters to identify device function

I think this is fairly typical.

Here's an example in the Substation editor:

![image](https://user-images.githubusercontent.com/674783/146666642-a79ff568-6514-4d4c-b25a-5d59e391b985.png)

The Communication editor really gets this right:

![image](https://user-images.githubusercontent.com/674783/146666669-0cf982e1-5fa4-4ec4-9fb5-c034b2f4a64d.png)
