### ISSUE TITLE
Add IED editor with responsive IED container

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#383]
As a System Configuration Engineer, I want to be able to see how many IEDs are included in my project and their know their names.

**Requirements**:
- create new editor type plug-in `IED`
- show only one IED at a time - files can have more than 100 IEDs and rendering would take forever otherwise 
- reuse the functionality of action-pane as in `Substation` editor plug-in
- make sure to at least have the `name` and `desc` attribute in the header

**Pre-Condition**
- none

**Type Definition**:
- this is read only, and we don't need any of the attribute definition

**Restriction**:
- none as read only

**Edition 1 vs Edition 2**
- none as read only implementation

**Comment by Sander3003** [comment]
![IED-editor](https://user-images.githubusercontent.com/7427358/143258161-4190fd32-8e92-4107-baa9-faae32dbf922.PNG)
