### ISSUE TITLE
Add Server container to IED editor plug-in

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#388]
As a System Configuration Engineer, I want to see in which AccessPoint a Server is located if any

**Requirements**:
- reuse the functionality of action-pane  as in *Substation* editor plug-in
- show all `Server` elements - should be only one per IED, but we shall 100% represent the SCL file. If by mistake more than one is defined, this shall be visible in the *IED* editor type plug-in
- write Server to the header

**Pre-Condition**
- #386 

**Type Definition**:
- this is read only, and we don't need any of the attribute definition

**Restriction**:
- none as read only

**Edition 1 vs Edition 2**
- none as read only implementation

**Comment by Sander3003** [comment]
![IED-editor](https://user-images.githubusercontent.com/7427358/143259800-f4eadc49-07a4-4b29-9d58-5aa7f18c51d5.PNG)
