### ISSUE TITLE
Focused Bay header shows gap above

### ISSUE THREAD

**Issue by ca-d** [openscd/open-scd#392]
In the Substation editor, the focused bay container currently displays a gap above the header.

![bay_bug](https://user-images.githubusercontent.com/20446628/143000954-b60bea49-9ae7-4965-9be0-e8d7a8c7afe7.png)

**Comment by ca-d** [comment]
This can be fixed by using `padding: 0px 0px 0.05px 0px;` instead of `padding: 0.05px;`

**Comment by ca-d** [comment]
For an even cleaner solution, we could replace editor-container margins with padding throughout, that way we would have a bottom padding of `16px` and guarantee correct display without the possibility of margin collapse.

**Comment by JakobVogelsang** [comment]
@ca-d I think exchanging margin with padding is not the solution, as outline does behave different with padding. Looking closer into this issue, I realized that there are two type's of margin collapse. The one that is bothering us is the parent child bottom. The other one is the one between siblings. The reason why I bring this up is: one other way to avoid parent child collapse would be `display: flex; flex-direction: column;`. This, however, and other than `padding: 0.05px` or `overflow:hidden` also prevent the margin collapse between siblings e.g. between two voltage levels and this looks weird. But here we can adjust the margins. Do you know of any disadvantages using `display: flex; flex-direction: column;` it works in my machine good so far.
