### ISSUE TITLE
Make connection points for connected equipment routes aligned to icon

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#404]
As a CoMPAS user
I want to see the routes connected to equipments be more aligned to the icons
So it looks more smooth and 'connected'.

Example:
<img width="577" alt="Schermafbeelding 2021-12-01 om 22 54 09" src="https://user-images.githubusercontent.com/16406106/144320232-54fd234b-6da9-4698-bc9c-7d14579d5949.png">

Here, the route on the left should be underneath the icon to make it look more connected.

**Comment by JakobVogelsang** [comment]
I have already dealt with this "issue" in this [PR](https://github.com/openscd/open-scd/pull/403). I just changed the `getDirection` so that is leaves `ConductingEquipment` and `PowerTransformer` vertically and `ConnectivityNode` is the one that can be reached `horizontally` and `vertically`.

**Comment by Flurb** [comment]
@JakobVogelsang sounds good!
Is it an idea to make this dependently on the sxy:dir attribute in the SCL? (ConductingEquipment and PowerTransformer only)
