### ISSUE TITLE
ConnectivityNodes in SLD editor should not overlap other elements

### ISSUE THREAD

**Issue by Flurb** [openscd/open-scd#409]
As a CoMPAS user
I don't want to see a ConnectivityNode overlap another element
So both elements are more easy selectable and the diagram is more clear.

Example:
<img width="577" alt="Schermafbeelding 2021-12-02 om 09 58 10" src="https://user-images.githubusercontent.com/16406106/144390047-8ac80299-c4d4-48c7-a132-568059ae6131.png">
This is a ConnectivityNode on top of a Breaker. This should not happen.

**Comment by JakobVogelsang** [comment]
I have already dealt with this "issue" in this [PR](https://github.com/openscd/open-scd/pull/403). I multiplied x and y coordinates by two, guaranteeing the `ConnectivityNode` to not overlap but also that we have enough space to draw orthogonal paths between equipment.

**Comment by Flurb** [comment]
> I have already dealt with this "issue" in this [PR](https://github.com/openscd/open-scd/pull/403). I multiplied x and y coordinates by two, guaranteeing the `ConnectivityNode` to not overlap but also that we have enough space to draw orthogonal paths between equipment.

Sounds like a good fix, but when I test it with a given SCD file I still see it happening :(
![Schermafbeelding 2021-12-03 om 21 41 17](https://user-images.githubusercontent.com/16406106/144670104-d7fe1440-9f73-41c4-9d7b-301050e02b5f.png)
