### ISSUE TITLE
Element Wizards in SLD diagram should have the SCL Coordinates attributes editable

### ISSUE THREAD

**Issue by Flurb** [openscd/open-scd#413]
As a CoMPAS user
I want elements in the SLD diagram who are eligible to have SCL coordinates be able to edit these attributes
So I can easily edit these attributes in the SLD diagram

Background:
The x, y and dir attributes should be editable for elements that are eligible to have SCL coordinates (ConductingEquipments for example).

**Comment by Sander3003** [comment]
Add the coordinate system a extension of an box.
![image](https://user-images.githubusercontent.com/7427358/145195741-5a0ad1ed-2a37-40dd-95b1-7747d25b88c8.png)

**Comment by JakobVogelsang** [comment]
I would suggest creating a new one based on the existing one. I know this might sound picky, but the fact that x,y and dir are defined in the appendix disqualifies those elements to be part of the wizard library. But as we need those textfields in the single line diagram only, we can copy the existing wizard to the singlelinediagram folder and just extend it as we need.

**Comment by Flurb** [comment]
> I would suggest creating a new one based on the existing one. I know this might sound picky, but the fact that x,y and dir are defined in the appendix disqualifies those elements to be part of the wizard library. But as we need those textfields in the single line diagram only, we can copy the existing wizard to the singlelinediagram folder and just extend it as we need.

That was also our plan :)
