### ISSUE TITLE
Add icon set to IED editor containers

### ISSUE THREAD

**Issue by Flurb** [openscd/open-scd#439]
As a CoMPAS user
I want to see better distinguished IED sections by using icons in the separate IED containers
So I can have a quicker recognition of different IED sections.

**Comment by Sander3003** [comment]
OpenSCD design guidelines: https://material.io/design

**Comment by Sander3003** [comment]
These only need icons: IED (see the exsiting icon), server, LD, accespoint (communication icon)

https://materialdesignicons.com/

**Comment by randy993** [comment]
Proposal:
IED: mdi:developer-board
Accespoint: mdi:access-point
Server: mdi:server
Logical device: mdi:gate-or / mdi:code-greater-than-or-equal / mdi:consolidate
