### ISSUE TITLE
Change IED names

### ISSUE THREAD

**Issue by randy993** [openscd/open-scd#453]
As an engineer I want to be able to change the IED names so I import ICD files and change the IED template name to a production name.

- Create edit button in the IED editor (after dropdown menu)
- Create edit button in substation tab upon selecting an IED
- Create IED edit window
  ![image](https://user-images.githubusercontent.com/47896624/147101809-f44180e4-c157-4a52-8976-ab64e0a0f5d2.png)
- Create checks
-- for uniqueness, the user should only be able to save the IED name when there is no other IED with the same name
-- Name can't be empty
-- Name should be according to the pattern
```xml
<xs:simpleType name="tIEDName"> 
  <xs:restriction base="tAcsiName"> 
    <xs:maxLength value="64"/> 
    <xs:pattern value="[A-Za-z][0-9A-Za-z_]{0,2}"/> 
    <xs:pattern value="[A-Za-z][0-9A-Za-z_]{4,63}"/> 
    <xs:pattern value="[A-MO-Za-z][0-9A-Za-z_]{3}"/> 
    <xs:pattern value="N[0-9A-Za-np-z_][0-9A-Za-z_]{2}"/> 
    <xs:pattern value="No[0-9A-Za-mo-z_][0-9A-Za-z_]"/> 
    <xs:pattern value="Non[0-9A-Za-df-z_]"/> 
  </xs:restriction> 
</xs:simpleType>
```

- Change the IED name and all references to the IED upon saving in the following locations
-- TConnectedAP.tUnNaming
-- agLDRef
-- tLNode.tUnNaming
-- tIED.tUnNaming
-- tExtRef
-- tControlWithIEDName.tControl.IEDName

Background:
This could be done in the IED editor or somewhere else if that makes more sense. All references to this IED need to be changed as well.

**Comment by randy993** [comment]
@JakobVogelsang Could you add this issue to the IED editor project?

**Comment by randy993** [comment]
Will we also make the description editable? If so, in what places should this be updated?

**Comment by Sander3003** [comment]
The description does not need to be editable in this story.

**Comment by dlabordus** [comment]
The following reference to the IED Name are updated:

The attribute of the following elements:
- Association[iedName]
- ClientLN[iedName]
- ConnectedAP[iedName]
- ExtRef[iedName]
- KDC[iedName]
- LNode[iedName]

From the following elements the Text Content is updated:
- GSEControl > IEDName
- SampledValueControl > IEDName

Private Elements are ignored, but this can become a problem in the future. 
Not sure how to make a bulletproof way to do this...

**Comment by Sander3003** [comment]
It is fine to ignore the private types.
