### ISSUE TITLE
Allow movement of Bays in SLD via sxy coordinates

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#456]
It's possibly a little premature but the good work in #455 of allowing coordinate movements in the SLD editor made me want to (at least prototype) the possibility of changing bay coordinates to shift bays around. It seemed like the same kind of thing.

Why? I have sometimes hand-crafted an `ssd` file to replicate bays and after this I wish to move them apart graphically but I find it tedious to modify `sxy` coordinates.

I'd like to do this by clicking on the bay and setting coordinates on it.

Then, within the bay the coordinates should be relative to the bay object according to the standard (they are nested and relative according to IEC 61850-6 Ed 2.1, Annex C).

> If coordinates are defined at different SCL tag hierarchy levels, then each level contains
> coordinates relative to the higher level. The absolute coordinate of a lower level is thus
> calculated by summing up all higher level coordinates, and the object coordinates themselves.
> If there are no coordinates defined at a higher level, then (x,y) = (0,0) is assumed.

Prototyping PR coming up momentarily. 

I have a limited amount of SSD files which work in the SLD editor at the moment (possibly due to unrelated reasons or poor constructions of the SSD or some kind of looping condition in the logic with open-scd's rendering, I have not investigated yet). My example for examining this is the attached:

[HRP.ssd.txt](https://github.com/openscd/open-scd/files/7771658/HRP.ssd.txt)

**Comment by JakobVogelsang** [comment]
@danyill is this still relevant?
