### ISSUE TITLE
DISCUSS: Lazy loading data model in the IED editor

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#462]
The work on the IED editor as per #461 clearly shows that we need some kind of lazy loading. Even if we filter per IED on opening the editor, loading the data model in #461 takes some 15 s on my machine that is quite fast otherwise. I therefore think we need to load the data model lazy and not everything at once. There are several possibilities if you ask me and would ask you to add some more to the discussion:

1. Load every thing up until the logical node level and load the rest when clicking (focusing) the logical node container.
2. Load every thing up until the logical node level, add toggle button to each logical node container that allows to further load the rest of the data model. This would allow hiding DA/DA again in opposite to the first suggestion.
3. Load data model only for the visible part on the screen. On scrolling down, more of the data model can be loaded. Technically this would be the trickiest to implement, if done well we could give the user the experience to work as if everything is loaded at the beginning.

**Comment by JakobVogelsang** [comment]
@Flurb implemented the second suggestion already #461 :). Opinions?

**Comment by Sander3003** [comment]
We can start with the implementation of @Flurb first.

**Comment by JakobVogelsang** [comment]
This is fine for me. I like the implementation as is already
