### ISSUE TITLE
Unable to save LNodeType of class LLN0 in Templates editor

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#465]
If I open an SCD file and take a template with a type of LLN0, I can open it but cannot save it because it breaks the validation constraint somehow:

![image](https://user-images.githubusercontent.com/674783/148857965-2d7ce777-08dc-49a3-952d-4523f4e1e866.png)

**Comment by JakobVogelsang** [comment]
Sorry, that is clearly a bug :(. But I think easy to fix. I will add a fix asap
