### ISSUE TITLE
LNodeType changes not reflected in dependent LNs in Templates editor

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#466]
When I change a LNodeType id in the Template editor, dependent LNs do not receive an updated LNodeType.

What should be the default behaviour? I would either expect them to be silently updated or for there to be a dialog after the change asking the user if all references with the same id should be updated.

Currently we get a log entry along the lines of:

![image](https://user-images.githubusercontent.com/674783/148858875-5c20f1d5-1162-4753-8896-0aafcc4801d5.png)

But do not warn for the LNs which are now missing a valid LNodeType (I think).

**Comment by JakobVogelsang** [comment]
I agree!

**Comment by JakobVogelsang** [comment]
Looking closer on this issue, this is a bit more tricky. @ca-d and I were discussing this a lot and until now we agreed that the template editor is an expert tool backed up by the validators. If you do something wrong, this immediately will be seen by the validator. See for example also the attribute `lnClass` or the name of DO that then need to be updated in the IED section.

So to make a long story short the current procedure is doing stuff and be notified if you did something wrong which is not always intuitive I agree. If we change that,  step by step,  what do we want to do? Do stuff automatically or be notified, that there are others changed required as well to keep the project valid. What would you prefer?

**Comment by danyill** [comment]
> Looking closer on this issue, this is a bit more tricky. @ca-d and I were discussing this a lot and until now we agreed that the template editor is an expert tool backed up by the validators. If you do something wrong, this immediately will be seen by the validator. See for example also the attribute lnClass or the name of DO that then need to be updated in the IED section.

Totally your call -- I think it's unintuitive. I would suggest:

1. All user actions in open-scd should target carrying out actions at an atomicity which allows a conforming file to be built if possible and at a level of automation that supports it.

2. I guess the question would be "What is the use case where I wish to change an id but _not_ have the dependent objects updated if it can be done automatically?". The use case for changing them is that sometimes I want for various automation purposes to define the LNodeTypes (rather than using the prefix of the IED name when open-scd imports multiple IEDs). When I do that I don't want to have manually edit each dependency via, say an XPath search.

3. The user's workflow should not be made up of action > validator error > action to correct error (and then wash, rinse and repeat) as I see it because this requires the user to do the work that the machine should either be doing or providing an option for doing.

Perhaps the point here is that in this editor significant changes in a data-model "must" cause contradictions and cannot be avoided when we're editing "one bit" at a time. In which case that's fine but I think we should target providing the user an option of automating "implied changes to other equipment" _where possible_ to provide a powerful editing experience.

None of which is to say that this is especially urgent or important :wink: Perhaps we could call it a feature request for the distant future (would you accept a PR to provide this?).

**Comment by JakobVogelsang** [comment]
Hi @danyill,

I had other users complaining about this as well. I would say we cannot leave it as is and would love you to propose a fix.

**Comment by JakobVogelsang** [comment]
Should be implemented!

**Comment by JakobVogelsang** [comment]
@Sander3003 can you still reproduce it?

**Comment by JakobVogelsang** [comment]
@danyill can you reproduce it?
