### ISSUE TITLE
Requirement to have an arrow option to minimize/expand the Logical Device directory level in the IED Editor tab

### ISSUE THREAD

**Issue by arulrajirudayasamy** [openscd/open-scd#468]
Observed:
It is really difficult to minimize the Logical Device in the **IED Editor tab**-refer to the below screenshot or attachment.
![IED Editor](https://user-images.githubusercontent.com/97508332/148905545-88176302-cd43-45a5-b0cc-65c7054cca37.png).

Expected:
Single arrow mark availability required on the Logical Device level to minimize and expand the LD level  to make the usability and focus on the specific Logical Device directory easily.

**Comment by Sander3003** [comment]
Thanks for the feedback, highly appreciated!

**Comment by Sander3003** [comment]
It would be nice if the server can collapse as well. By default the windows should be open.
