### ISSUE TITLE
Vacuum definitions function for DataTypeTemplates

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#485]
This is a feature request.

It would be useful to have a "vacuum definitions" function to remove unused `LNodeType`s or `DOType`s, `DAType`s or unused `Enum`s in the `DataTypeTemplates` section. This is the kind of thing that other XML editing software (e.g. Inkscape) has.

I think this could usefully be part of the Templates section or it could be an additional menu item (although this is growing quickly and I guess we can't just keep adding menu items for forever...).

Even just for working on open-scd constructing a test case is more laborious than necessary even when I have the right starting material because I wish to keep a "simple" test file with as little extraneous data as possible. Currently, I manually edit and modify the types.

I like the name "Vacuum definitions" but "Remove unlinked types" would be more correct :wink:

**Comment by JakobVogelsang** [comment]
Thanks for this issue. This is an interesting one that I did not have on screen. It fits very nicely with another feature wish #290  posted by @BurTah00. I would love to combine those in a menu type plug-in that I would call something like clean up. When clicking on the menu button, a dialog opens where the user selects the type of clean-up. Your wish would be one of those. I don't think we need to be complete from the beginning as it can grow but start with the two issues , this one and #290.

**Comment by JakobVogelsang** [comment]
@danyill would you say we can close this?

**Comment by danyill** [comment]
Yes. Soon I will have a PR to improve the current state.
