### ISSUE TITLE
Extend plugin API to forward individually loaded `nsdoc` files

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#490]
This story is a precondition to #365. As `*.nsdoc` files cannot be uploaded and shipped for legal issues, we need a mechanism to individually load and use `nsdoc` files. The loading mechanism shall be part of `Settings`. Each plug-in can access this information through

1. A function `getAttributeDescription`
That takes as an input the element `Element` and the attribute `string` of interest and return either a description from the `nsdoc` or the attribute's value from the element, if the description for whatever reason is not available. 

? Do we require two functions, one for short and one for long description.

2. An object containing the nsdoc files
{
  nsdoc74?: XMLDocument;
  nsdoc73?: ...
  nsdoc72?: ...
  nsdoc81?: ...
}

**Comment by Sander3003** [comment]
@Flurb can this be closed?

**Comment by Flurb** [comment]
Resolved with #516
