### ISSUE TITLE
IED Editor switches back to first IED when starting to edit

### ISSUE THREAD

**Issue by dlabordus** [openscd/open-scd#496]
There is a bug that when you start to edit the selected IED in the IED Editor, the IED Editor always switches back to the first IED in the list.
This is caused by the rendering of the IED Editor where the first IED is always made selected.

**Comment by JakobVogelsang** [comment]
Yeah, when one test, it should not the first one to test with. I think a quick solution could be to stare the IED name to local Storage. If the IED name cannot be found to remove it and show the first IED. 
It is however not really a clean solution. Here we have to have a closer look why we re-render the whole Editor every time a wizard-dialog opens or closes.

**Comment by dlabordus** [comment]
Damn, you triggered me in testing something. The same problem has the SLD now when selecting the Substation.

**Comment by dlabordus** [comment]
I found another solution by creating a variable outside the Plugin/LitElement and use that.
It also not perfect, because it now becomes a global variable, so I named it by the SLD "sldSelectedSubstation".
