### ISSUE TITLE
Issue with sub-wizards in case wizards are depending on each other

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#498]
The example - issue - we see in our solution is this:

1.) Open edit wizard for `DataSet` say from `ReportControl` element. 
2.) Change the name of the DataSet
3.) As the name of the DataSet is reference from the `ReportControl` element, we need to change the attribute `datSet` there
4.) When - in a subwizard based UI - we return to the edit wizard of the `ReportControl` it actually does not show the `ReportControl` in the SCL, but the "old" one that was replaced with the Update action. 

I would say a solution would be to not use elements as the input for the function that return `Wizard` but to use our identity string. 

For now, we have tom make sure to either not allow changing things that might affect the wizard before or to not use subwizards in such cases.

**Comment by JakobVogelsang** [comment]
This is an issue with our Editing system. Specifically with our `onUpdate` function. What we do at the moment is to swap the `old` element with the `new` element. This function is very straight foreward and the undo does work in the same way, we just nieed to exchange `old` and `new`. 

Me an @ca-d as well as @dlabordus were discussing how we could solve the problem. @ca-d and me are seeing a long term solution and a potentially long term solution that I will open a new issue for. But in short:

*Potentially long-term*:
- do not use DOM objects at all for editing but objects and to identify the element in the DOM the identiy string we provide in the foundation

>Advantage: We have automatically serializable actions that we can store in the SCD - e.g. `Hitem`. 
>Disadvantage: The SCL does not have native id's for their elements and the id is a reference build from configurable attributes. This means we would need something event that triggers when a identity string changes :(

*Short-term*:
We leave the `Update` API as is `new:Element,old:Element` but do not swap in the `onUpdate` but we exchange attributes using the functions `removeAttributeNode` and `setAttributeNode`. Then we only need to change the `onUpdate` and everything else can stay as is.

>Advantages: clear reference through element, no big changes needed this can be implemented very fast
>Disadvantages: we relay with our API on DOM from the beginning, we can not undo history before file open

@dlabordus @Flurb @danyill and others what do you think about that

**Comment by dlabordus** [comment]
For the short-term, how are you planning to do the undo history in this case?
Because that still means that you need to save a clone of the old element to make this possible.
And in the future it still could be possible to undo history from before opening the file, just replacing the attributes again...

**Comment by JakobVogelsang** [comment]
What we thought of for the short-term is to not swap the element in the DOM but to swap the attributtes in the elements DOM objects. However, we still have DOM objects and those are not really serializable so far I know. An this is the crutial thing that is missing to push those to the `Hitem` elements in the SCL.

**Comment by JakobVogelsang** [comment]
We have added a new type of editor action that allows to keep the referenced element in the DOM: `Update`
