### ISSUE TITLE
Editor/Wizard unknown about identity change in Wizard/SubWizard

### ISSUE THREAD

**Issue by dlabordus** [openscd/open-scd#503]
The example where it now is going wrong is in the IED Editor when the IED is edited and the name is changed.
The IED Editor doesn't know the name changed and tries to find the IED using the old name.
In the IED Editor there is a short-time solution to select the first IED, so the screen doesn't produces a error.
But it would be nice if the IED Editor gets the new name and can use that to select the correct IED again.

**Comment by JakobVogelsang** [comment]
@dlabordus do you think this issues can be solved with the new `Update` action?

**Comment by Sander3003** [comment]
The update action can be used

**Comment by dlabordus** [comment]
We can use the Update Action in both the SLD Editor and IED Editor, but than we also need to change what is remembered by the selector (IED/Substation).
As a work-around we saved the name of the IED/Substation that was selected, but we now change this back to the Element that is selected. Because of the update the element stays the same and can then again be used to determine which IED/Substation was selected before editing the IED/Substation.
