### ISSUE TITLE
Display Enum description in IED editor

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#518]
As an engineer
I want to see the Enum description of the selected Enum value
So I understand the setting.

Background:
In info Icon can be placed here:
![image](https://user-images.githubusercontent.com/7427358/151179849-80df51ab-287e-45cd-af50-a05cfc51ee67.png)

To be added:
How to come from SCL to NSD??

**Comment by JakobVogelsang** [comment]
Is this implemented? @Flurb

**Comment by Flurb** [comment]
@JakobVogelsang Yes this has been implemented by this PR: https://github.com/openscd/open-scd/pull/522

**Comment by Sander3003** [comment]
It it is done, we can close it!
