### ISSUE TITLE
Create 'Subscription' plugin for GOOSE subscriptions

### ISSUE THREAD

**Issue by randy993** [openscd/open-scd#525]
[Discussion topic](https://github.com/openscd/open-scd/discussions/520)

To create the subscription functionality, we need a new plugin called 'Subscription'. This plugin creates a new tab in the user interface for the functionality of subscribing IEDs to GOOSE messages. This issue contains the creation of the plugin and showing the published GOOSE messages and IEDs which can subscribe or are already subscribed. This will later be extended.

Since it is likely that there will be more plugins, depending on the method implemented, it is desirable that the Js file has a suffix of the subscribtion method used. For example:

```
  {
    name: 'Subscription',
    src: '/src/editors/Subscribtion_ABB.js',
    icon: 'link',
    kind: 'editor'
  }
```
![image](https://user-images.githubusercontent.com/47896624/152175758-652265ff-113e-42b2-a253-a032897a19a2.png)

Show all published GOOSE messages from all IEDs:
``` XML
<GSEControl datSet="DataSet" confRev="20001" appID="SIP1/VI3p1/LLN0/Control_DataSet" name="Control_DataSet" type="GOOSE">
	<IEDName apRef="E">SIP_Merg</IEDName>
</GSEControl>

```

When selecting an IED, show all `<extRef>` with serviceType = GOOSE of all `LN`s.
``` XML
<Inputs>
	<ExtRef iedName="SIP_Client" ldInst="VI3p1" lnClass="PTRC" lnInst="1" doName="Op" daName="general" serviceType="GOOSE" srcLDInst="VI3p1" srcLNClass="LLN0" srcCBName="Control_DataSet" pServT="GOOSE" desc="RxOp" intAddr="RxOp;/Op/general" pDO="Op" pDA="general" />
	<ExtRef iedName="SIP_Client" ldInst="VI3p1" lnClass="PTRC" lnInst="1" doName="Op" daName="q" serviceType="GOOSE" srcLDInst="VI3p1" srcLNClass="LLN0" srcCBName="Control_DataSet" pServT="GOOSE" desc="RxOp" intAddr="RxOp;/Op/q" pDO="Op" pDA="q" />
</Inputs>

```

**Comment by randy993** [comment]
@JakobVogelsang Could you drag this in the [Communications mapping](https://github.com/openscd/open-scd/projects/4) project?

**Comment by JakobVogelsang** [comment]
@randy993 you should now be able to add issues to project as well.
