### ISSUE TITLE
Help's internal links do not work

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#532]
The error message in the console is:

```
Uncaught TypeError: event.target.closest(...) is null
    onclick https://openscd.github.io/:1
[openscd.github.io:1:25](https://openscd.github.io/)
    onclick https://openscd.github.io/:1
```

**Comment by Sander3003** [comment]
It work now well on https://openscd.github.io/. Is this still an issue?

**Comment by clepski** [comment]
The link in `Help.ts` does not work anymore

```
  const res = await fetch(`/public/md/${page}.md`);
```

But can be fixed with `/openscd/public/md/${page}.md`, there are still errors when clicking on links
