### ISSUE TITLE
Confusing Extensions userinterface

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#533]
As a user
It is confusing to me when to press the add button
I now think that once I selected an extions I need to click the add button

![image](https://user-images.githubusercontent.com/7427358/152369162-6a5c9556-8779-46bb-a8ff-ced29092874c.png)

Suggested solution, add a oke button for exiting the window and rename the add button to "add external plugin"

Background: this is what I saw multiple users making this mistake.

**Comment by Sander3003** [comment]
@JakobVogelsang do you have other suggestions for a solution?

**Comment by JakobVogelsang** [comment]
I agree with both the suggestions
