### ISSUE TITLE
Update 7-420 NSD file

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#542]
As an engineer
I want to use the lastest DER (7-420) NSD files to configure substations
So I can use the improvements

Background:
https://blog.nettedautomation.com/2021/11/four-additional-light-namespace.html

**Comment by JakobVogelsang** [comment]
I thinks we need to not only update those, but also to add all available scemas!

**Comment by Sander3003** [comment]
Do you envision a NSD schema selector? So users can select the NSD they want to use?

**Comment by JakobVogelsang** [comment]
I would say this is not neccassery. The version, revision, release is part of the schema since Ed2 and there are only NSD files for Ed2.1 and above. So to my understanding it is better to let OpenSCD choose the correct version. Is there a case where selecting of the user is preferred.

**Comment by Sander3003** [comment]
Staying with the latest version should be fine.
