### ISSUE TITLE
Add more background information in the related Reporting block fields

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#545]
As a new engineer
I want to read an explanation of fields
So I can understand 61850 faster without knowing all the abbreviations and looking them up in the IEC 61850 documents.

Background:
![image](https://user-images.githubusercontent.com/7427358/154307319-fadf2957-f319-4fc4-be0a-9d6e47d17a12.png)
E.g. what is the meaning of rptID?

This information might be in the nsdoc files. This can be done using an (i) icon.

Acceptance criteria:
Needs to be added to the the windows shown above and related windows (dataset, trigger options, optional fields)

**Comment by JakobVogelsang** [comment]
Some of it will be fixed with the PR: #544. I am not aware that there are mashine readable descriptions for attributes like the rptID. This is something that we will have to add by hand.

**Comment by randy993** [comment]
If we want to show user-friendly names, where do we get the data?
Maybe think about an option to go into 'expert' mode, which shows the technical (61850) labels.

**Comment by JakobVogelsang** [comment]
I think with the latest merge to main it is obsolete. I will close this and would like you to open a new issue if I missed something

**Comment by Sander3003** [comment]
Thanks for your contribution!
