### ISSUE TITLE
Add Functional contraint to the CDC IED editor

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#546]
As an engineer
I want to see the FC added to the CDC display in the IED editor
So I can use them in refering to them from other places

Background
Currently only the type is displayed in the CDC (in this case a boolean):
![image](https://user-images.githubusercontent.com/7427358/154311982-952e968a-bd75-4b68-8fa0-891054af979f.png)

**Comment by JakobVogelsang** [comment]
A saw a lot of software adding it like so `stVal - BOOLEAN [ST]`.
