### ISSUE TITLE
Tab bar scrolling

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#557]
The menu/tab bar is now large enough (a sign of success) that on some form factor devices or small screens there can be too many entries.

![image](https://user-images.githubusercontent.com/674783/155480998-6e095dbc-3424-40d3-8715-021aeb84f230.png)

We could solve this by showing left and right buttons and allowing scrolling of the tabs (especially wheel mouse scrolling which is what I'd expect to be available).

**Comment by JakobVogelsang** [comment]
Nice, that for sure would be an enhancement :)

**Comment by JakobVogelsang** [comment]
I think this is possible. When you hover over the bar and press `Control` while scrolling. At least this work on my PC. @danyill  can you reproduce this

**Comment by JakobVogelsang** [comment]
Is this still an issue @danyill?

**Comment by danyill** [comment]
Control scroll does not work for me. And it's very easy too have too many plugins to use the top bar without scrolling now, so yes :wink:

**Comment by JakobVogelsang** [comment]
Can you try shift and scroll? @danyill

**Comment by danyill** [comment]
That is good. I would like to document it since it is not very familiar.
