### ISSUE TITLE
Document contribution process and basic steps for plugin development

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#574]
Having recently had a go at writing my first plugin (no doubt still needing improvements), I'd like to document the process for developing an editor plugin - at least the loose outline of this and a few tips for users.  

I have had many learnings and before I lose them I would like to store this knowledge and receive some feedback. It will probably be initially quite rough but I think something is better than nothing and being able to iterate on a base is helpful. While my understanding of aspects may be quite rudimentary this may help me communicate to others who are new to OpenSCD.

It's fundamental to open source that others can contribute and presently there are some barriers to entry for OpenSCD (contributing guidelines, chat channel, API docs). I don't mind that at all (setting up infrastructure rather than focusing on core features takes time and effort) but I'd like to help with this.

Documentation facilitates an assessment by potential contributors of the effort and the areas where they need to learn.
This project has ambitious goals in terms of outreach to utilities and manufacturers and it needs to be both straightforward and seen to be straightforward for contributors to understand, get started, contribute and join the community: "Don't build your own, an OpenSCD plugin is quite easy to create, just read the docs".

I'd like to propose the following for some quick wins:

* We create a file called `CONTRIBUTING.adoc` which provides basic instructions on how to set up a project and includes information on workflow.
* For more detailed guidance on how to create a plugin or carry out other work, we use a directory called `docs` in the repository.
* If it's acceptable I'd like to use [Asciidoc](https://docs.asciidoctor.org/asciidoc/latest/) for this (it is rendered reasonably well in Github and has a better feature set than Markdown, plugins available in VS Code and most other editors). I'm somewhat involved in the Asciidoc project and am quite comfortable writing in this.
* Ultimately (not soon and not in scope for now) having a domain using a static site generator and using the OpenSCD branding and theme would be good (I am fond of Antora for this) - e.g. docs.openscd.org. 

I think the first topics could be:

* Setting up a development environment (cloning, recommended editors, how to debug). For instance, I spent at least half a day trying to get debug integration with VS Code before realising (I think) it wasn't possible...
* How to create a menu item plugin (this is the simplest extension because it doesn't involve UI work)
* How to create an editor plugin (harder but more powerful, UI concepts like lit are required and some idea of web components)
* How to write and debug a unit test
* How to write and debug an integration test

**Comment by Sander3003** [comment]
@danyill this is a good idea, It will help everone to understand OpenSCD better. In terms of documentation, this is how we do it in LF energy CoMPAS: https://com-pas.github.io/compas-architecture/

**Comment by danyill** [comment]
I'll un-assign myself to this in view of the looming Great Refactor where there are likely to be some significant changes and it may be better to have someone with more experience document this.

**Comment by JakobVogelsang** [comment]
I think for that same reason, we can close this issue. Depending on the allocation of the plugins, this might be even irrelevant.

**Comment by JakobVogelsang** [comment]
Do you agree @danyill?

**Comment by danyill** [comment]
Yes, thanks for checking :+1:
