### ISSUE TITLE
Add edit button or hyperlink to GSEControl dialog in the Subscription Editor

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#577]
In the upcoming subscription editor, it would help the user's context switching to be able to directly see and edit a GSEControl from the subscription window.

I suggest either adding an edit button or being able to hyperlink the dataset to open the editor.

Perhaps something like the following would be sufficient:

![image](https://user-images.githubusercontent.com/674783/157082101-e05f875a-c3dc-499e-8a7b-4cab1b4619f4.png)

**Comment by Sander3003** [comment]
Needs to be added to sampled values and GOOSE:

Icon location:
![image](https://user-images.githubusercontent.com/7427358/159710900-8d86dabd-e9a2-47d2-b20b-e0f080705d81.png)

**Comment by Sander3003** [comment]
Once you click on edit you see:
![image](https://user-images.githubusercontent.com/7427358/159711463-e6dbbe4b-8633-454a-8483-a944d7d26083.png)

**Comment by danyill** [comment]
I was perhaps insufficiently clear. I thought the edit button belonged adjacent to the publisher GSEControl

Perhaps something almost exactly like what I have done here:

![image](https://user-images.githubusercontent.com/674783/167246437-9e6563cc-b371-4cd4-8a09-1f7d4ae91e26.png)
