### ISSUE TITLE
Provide manufacturer and type filtering in IED Editor

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#591]
Here's a use case for providing name, manufacturer and type filtering in the IED editor (with some kind of auto-completion).

1. We're evaluating some IEDs.
2. We said, "We'd quite like to have an SCD file with some mappings in it to look at". It turns out this device will only offer proprietary file formats or an IID file once loaded to the device (and we don't have one physically handy).
3. We received a link to a [large collection of SCD files](https://iec61850.ucaiug.org/2019IOP-Charlotte/IOP%20Test%20Documents/Forms/AllItems.aspx?RootFolder=%2f2019IOP-Charlotte%2fIOP%20Test%20Documents%2fSCD%20Files&FolderCTID=&View=%7BEC1FD7D0-5289-4545-86ED-2CC3926EA317%7D) from Interoperability Testing.
4. I thought "I'll choose one and find the right device by opening it in OpenSCD".
5. The IED editor seems to be the right place.
6. In the file I chose, not all the naming makes much sense to me and not all the manufacturers have included the manufacturer in the device description.
7. It would be useful if I had a drop-down to see values and filter on manufacturer and device type in the IED editor and to have the ability to free-text filter on these fields (name, manufacturer and device type).
8. I know what I'm looking for but I can't get there...

**Comment by JakobVogelsang** [comment]
At the moment, this can be solved by providing a filtered-select web-component that uses the filtered-list instead of `mwc-list`. Then you can filter for everything that is part of the items' description. Manufacturer might be one of those. This is a short term solution to this. On a long term it could be part of the search bar. Where one of the standard choices could be ied: ... and also manufacturer: ...

**Comment by JakobVogelsang** [comment]
I would propose to make a very small step here before utilizing a filtered-list as it still is an open question if having more than IED loaded at the same time makes sense:

Extend the list item for the IED and make it a two line list item

- 1st line: IED.name (IED.desc)
- 2nd line: IED.type - IED.manufacturer
