### ISSUE TITLE
Select by Subscriber in Subscriptions Editor

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#592]
Here's a use case for a different interface than that provided in #549.

I'm not sure whether it should be in scope for that or a separate piece of work or not even be a requirement.

Here's what I was trying to do:

1. I had a sample file and I wanted to see the GOOSE subscriptions for a specific device.
2. I know the device name which has the subscriptions but I don't know the GOOSE publisher.

This means that with the information I have to hand I cannot locate the subscriptions.

Is this a reasonable use case? I think so. Let's imagine I am replacing a device and want to know "Everything it subscribes to".

Interested in the thoughts of others.

**Comment by Sander3003** [comment]
This sounds a reasonable use-case, it would indeed be nice if you can look up all relevant GOOSE/Sampled value stream going to a specific IED to replace the IED by something else.

**Comment by JakobVogelsang** [comment]
It does yes. With ABB the UI is a matrix, and you can see both the ways. For this plugin, I would suggest a swap button in between the lists, that allow to put switch source and sink list. Clicking on the IED would the  show the connected GSEControl elements on the left-hand side.

**Comment by danyill** [comment]
> It does yes. With ABB the UI is a matrix, and you can see both the ways. For this plugin, I would suggest a swap button in between the lists, that allow to put switch source and sink list. Clicking on the IED would the show the connected GSEControl elements on the left-hand side.

That's a nice idea. I note that existing tools (e.g. SEL Architect) don't provide this capability.

**Comment by Flurb** [comment]
@Flurb will add comments about a possible solution.

**Comment by randy993** [comment]
Maybe we can do something like this. Create a 'swap' button for the left column which will swap the publishers for subscriber IEDs. It can show a list of all IEDs which have a (partial) subscription to another IED. Then, on the right side we can show the subscriptions. 

![image](https://user-images.githubusercontent.com/47896624/160353995-73ee9b11-b3bc-4c2c-ab58-7418659c5717.png)

![image](https://user-images.githubusercontent.com/47896624/160354574-c36e6c2e-3c57-4f7e-a369-1fd411f1702e.png)

**Comment by Sander3003** [comment]
Styling issues needed to fixed first.

**Comment by JakobVogelsang** [comment]
Styling is done!
