### ISSUE TITLE
Generation of ctlVal not possible - missing FC in 7-3

### ISSUE THREAD

**Issue by SBaumgar** [openscd/open-scd#600]
![grafik](https://user-images.githubusercontent.com/80691258/158360008-c9698777-0a64-426d-95e6-e20419d9cea5.png)

The DA ctlVal of i.e. SPC could not be generated. 

Proposition: Change for this Attribute the validation/rule.

**Comment by JakobVogelsang** [comment]
The table you are presenting from the 7-3 is misleading. `ctlVal` is never a direct Child of a `DOType` e.g. SPC but is allocated in the 8-1 defined special structures for control operations: `Oper`, `Cancel`, `SBOw`. Here you can add this attribute - at least on my machine.

**Comment by SBaumgar** [comment]
Thanks for the explanation. This works also on my machine.
