### ISSUE TITLE
Remove IED button

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#616]
As an OpenSCD engineer user
I want to a button to remove IED's from a SCL file
So I can remove IED's that are not needed any longer

Accpetance criteria:
The IED and related information should be removed
Including the related reporting blocks 

Background:
When editing a substation, it could be usefull to remove a IED of an exsiting configuration.

**Comment by randy993** [comment]
Add trashbin icon to:
![image](https://user-images.githubusercontent.com/47896624/159688481-5e73b690-50ab-425c-b93e-e96c567182c9.png)

And add Remove button to:
![image](https://user-images.githubusercontent.com/47896624/159688625-2e15fe64-2a77-4607-8d8b-60180f8488f7.png)

Upon deletion, delete the `<IED>` element and the references to the IED element.
- All `<ConnectedAP>` elements in other IEDs with iedName = {the deleted IED}
- All `<ExtRef>` elements in other IEDs with iedName = {the deleted IED}
- All `<SampledValueControl>` elements with a value of the deleted IED name in the element `<IEDName>`
- All `<GSEControl>` elements with a value of the deleted ied name in the elemnt `<IEDName>`

What about `<tControlWithIEDName>`?

Maybe we should warn the user that all references to the IED will be deleted as well? For example GOOSE/SMV subscriptions etc?

**Comment by Sander3003** [comment]
To be added:
Dialog with things that are being removed (elements)

The delete function can be added to the *** menu

The rename function can be used to check if the remove function is complete: https://github.com/openscd/open-scd/issues/453

**Comment by Sander3003** [comment]
Don't forget to remove the data template section.
