### ISSUE TITLE
No message when file has no GOOSE / SMV

### ISSUE THREAD

**Issue by Flurb** [openscd/open-scd#629]
It's better to show a message when there are no messages available.

Right now it's like this:

![Schermafbeelding 2022-03-21 om 13 38 36](https://user-images.githubusercontent.com/16406106/159262576-8bad2320-3e97-433f-b1ea-9957186aa6c4.png)

**Comment by JakobVogelsang** [comment]
I think showing all IED would not be a bad choice here. I would be very beneficial, if you ask me to have an add button on the non-interactive IED elements. For that, we need to show all IEDs at the end anyway.
