### ISSUE TITLE
Change DAI values

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#639]
As an engineer
I want to be able to change DAI values
So I can change the values according to specifications

Button location:
![image](https://user-images.githubusercontent.com/7427358/160129585-7ce991c6-1e8f-40d0-a7eb-8dbf4858fa9f.png)

```
							<DAI name="sboTimeout">
								<Val>
									30000
								</Val>
							</DAI>
```

Once you click on the button, the values can be changed inline. The value becomes editable in the same window (inline editing). It should be able to edit multiple DAI at the same time. A change will be stored if the checkmark/Oke (green) is clicked or reverted if the users clicks on a X (red). 

XSD values according to the IEC61850 XSD:

```
<xs:simpleType name="tPredefinedBasicTypeEnum">
        <xs:restriction base="xs:Name">

Implementation for now:
            <xs:enumeration value="BOOLEAN"/>
            <xs:enumeration value="INT8"/>
            <xs:enumeration value="INT16"/>
            <xs:enumeration value="INT24"/>
            <xs:enumeration value="INT32"/>
            <xs:enumeration value="INT64"/>
            <xs:enumeration value="INT128"/>
            <xs:enumeration value="INT8U"/>
            <xs:enumeration value="INT16U"/>
            <xs:enumeration value="INT24U"/>
            <xs:enumeration value="INT32U"/>
            <xs:enumeration value="FLOAT32"/>
            <xs:enumeration value="FLOAT64"/>
            <xs:enumeration value="VisString32"/>
            <xs:enumeration value="VisString64"/>
            <xs:enumeration value="VisString65"/>
            <xs:enumeration value="VisString129"/>
            <xs:enumeration value="VisString255"/>

For later (new stories):
            <xs:enumeration value="Enum"/>
            <xs:enumeration value="Dbpos"/>
            <xs:enumeration value="Tcmd"/>
            <xs:enumeration value="Quality"/>
            <xs:enumeration value="Timestamp"/>
            <xs:enumeration value="Struct"/>
            <xs:enumeration value="EntryTime"/>
            <xs:enumeration value="Check"/>
            <xs:enumeration value="ObjRef"/>
            <xs:enumeration value="Currency"/>
            <xs:enumeration value="PhyComAddr"/>
            <xs:enumeration value="TrgOps"/>
            <xs:enumeration value="OptFlds"/>
            <xs:enumeration value="SvOptFlds"/>
            <xs:enumeration value="LogOptFlds"/>
            <xs:enumeration value="EntryID"/>
            <xs:enumeration value="Octet6"/>
            <xs:enumeration value="Octet16"/>
            <xs:enumeration value="Octet64"/>
            <xs:enumeration value="Unicode255"/>
            <!-- for 61850-8-1 Edition 2.1 -->
        </xs:restriction>
    </xs:simpleType>

```
Regular expressions can be used to check if the user input is.

Examples:
Validation of: <xs:enumeration value="INT8"/>
The value can be +/- 2^7

Validtaion of:  <xs:enumeration value="INT8U"/>
The value can be 2^8

All values can contrains can be found in IEC 61850-7-2 6.1 and 6.2 ([link for NEN connect users](https://connect.nen.nl/Family/Detail/38669))

Only editable fields to have an edit icon.

**Comment by Sander3003** [comment]
@danyill what values types to you like to edit besides the basic ones for now?

**Comment by Sander3003** [comment]
@dlabordus can you add the technical details?

**Comment by dlabordus** [comment]
A idea is to create some kind of structure/object per type that will render the input field and maybe process the input when saved. Per type we can create a implementation. If there is no implementation the Edit button won't be shown. 

This way we can slowly add more implementation, the simple ones will go fast, but the more complex ones can be done in separate issues.
