### ISSUE TITLE
Adding a new subnetwork to OpenSCD title

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#643]
wizard.title.create is probably not the intended title; Suggestion: Add subnetwork

![image](https://user-images.githubusercontent.com/7427358/160421880-17de8607-025a-4f9a-b9c8-211c27ef4717.png)

**Comment by Sander3003** [comment]
@JakobVogelsang can you look at this?

**Comment by JakobVogelsang** [comment]
@Sander3003 I will this is probably a minor issue.
