### ISSUE TITLE
104 support: Show/edit subnetworks without redundancy

### ISSUE THREAD

**Issue by randy993** [openscd/open-scd#649]
As an engineer 
I want to be able to see 104 communication subnetworks
So I can use it to configure devices or check the configuration.

More information can be found in IEC/TS 61850-80-1

Mockup:
![104mockups-Show subnetworks drawio](https://user-images.githubusercontent.com/7427358/165313699-08309a01-bbda-4133-943a-16ccca376b06.png)

The layout can be re-used for the exsisting 

Just like in the communications tab, the private 104 subnetworks should be shown to the user in the 104 plugin. This can either be a section with one link, or a section with redundant links. An example can be seen here:
 
![image](https://user-images.githubusercontent.com/47896624/161052992-9ff36c7e-94f6-4da8-a2f5-f47ac0732f7e.png)
![image](https://user-images.githubusercontent.com/47896624/161053004-9e37006b-9d9e-4934-9ef5-eba292e75d20.png)

![104mockups-Edit communication (no redundancy groups) drawio](https://user-images.githubusercontent.com/7427358/165313515-792e9f54-395a-42e0-a840-b172a125d5b4.png)

When the user clicks on one AP the `<P>` elements should be shown to the user. It should also show the descriptive names as well.
 
![image](https://user-images.githubusercontent.com/47896624/161053022-b0ebe4cd-d933-4004-ad49-889200b04683.png)

**Comment by Sander3003** [comment]
As an engineer 
I want to be able to see 104 communication subnetworks
So I can use it to configure devices or check the configuration.

More information can be found in IEC/TS 61850-80-1
