### ISSUE TITLE
104 support: Show 104 adresses

### ISSUE THREAD

**Issue by randy993** [openscd/open-scd#650]
As an engineer 
I want to see private 104 elements in DAI elements without editing capability
So I check the configuration

61850 Common dataclasses to support:
SPS
DPS
INS
ACT
ACD
SEC
BCR
MV
CMV
WYE
DEL
SEQ
HMV
DEL
SPC
DPC
INC
BSC
APC
SPG
ING
ASG
ENS
HST
ENC
ENG
BAC
CSG

Open questions:
Interface suggestion:
![104mockups-104 phase 1 display 104 values drawio](https://user-images.githubusercontent.com/7427358/165269899-abaae00d-8c89-4f66-9974-a12556b1920d.png)

The interface should use a filteredlist for easy filtering.
A radio button can be used to select the 104 network section or value selection.

The first section of the filterd list should show all signals with a 104 adres.

Background:
For more information: IEC/TS [61850-80-1 (for NEN connect users)](https://connect.nen.nl/Family/Detail/44652)
For the 104 communications, data attribute elements will have an added private element indication communication through 104. For example, the `<stVal>` of the `<SPS>` data class, can have a private element indicating the 104 communication.

![image](https://user-images.githubusercontent.com/47896624/161053219-d6282405-b6bb-4499-9ed8-70b9a70f9095.png)

In the new 104 tab, created by the plugin we can show all data attributes with an added 104 private.

**Comment by Sander3003** [comment]
As an engineer 
I want to see private 104 elements in DA elements
So I check the configuration

**Comment by Sander3003** [comment]
A radio button can be used to select network/Values

**Comment by Sander3003** [comment]
This needs to splitted into the values and the networksection.

**Comment by Sander3003** [comment]
For the table: https://github.com/openscd/open-scd/pull/568
