### ISSUE TITLE
Subscriptions filtering by device and message name

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#655]
After some very excellent work on subscriptions, I thought I'd have a look.

I expect the filtered list in the subscriptions to allow me to scope the IED basic properties (using the identity function) as well as the GOOSE message names (I looked at the GOOSE subscriptions). (I speculate we could concatenate the identity functions).

I would like to be able to scope to the IED name, manufacturer or type.

I tested the GOOSE subscriptions using https://openscd.github.io/ just now.

On the publishing side when I start typing an IED name it filters the IEDs.

![image](https://user-images.githubusercontent.com/674783/161213743-98c1db0f-39fb-463c-8825-239f5460c66f.png)

But this filtering prevents the GOOSE messages from being displayed.

![image](https://user-images.githubusercontent.com/674783/161213835-33a6b1d1-e861-4fc9-b751-9f61fb136724.png)

**Comment by JakobVogelsang** [comment]
See the issue before yours #654 :)

**Comment by Flurb** [comment]
Bit more background, the IED names are `noninteractive` in the filtered-list, which means they cannot be interacted with (duh!). filtered-lists as we use cannot handle noninteractive items in their filtering, so something needs to be done right here.

**Comment by danyill** [comment]
Thanks for the explanations.
It may be the same issue, it is not clear to me.

I was expecting to be able to filter by both the GOOSE message name and the IED characteristics. As it stands now I can filter by the GOOSE name. When I add to this a filter by the IED name. I lose the GOOSE message name.

I don't mind that the other IED objects remain in the filtered list as this will be resolved in #653 but that may not get to the heart of this.

Let me try to be more clear:

* I want to filter all D60 devices with a goose name beginning with `gcb`.
* I start by writing `gcb` and realise my list is still quite long for the task I set out to do.
   ![image](https://user-images.githubusercontent.com/674783/161311041-31a1f0cd-e063-43b3-9423-9b26d7d5e75e.png)
* I stop and think and realise that actually my task only involves D60 devices (whatever they are). I add D60 to my filter `gcb d60` expecting now to have all goose messages beginning with `gcb`, `d60` or the IED "characteristics" which have `d60` in them. 
* Instead I find I have filtered out the children of the object of interest.
    ![image](https://user-images.githubusercontent.com/674783/161311585-c866e809-6871-4a3a-8021-883dfcc61b73.png)
* Is this a good use case, I think so...

I don't think this is the same as #653. I don't mind that the IED objects are still there (well I do, just a little bit), but I would like to be able to filter on the "combined characteristics").

I am somewhat surprised that the identity string does not allow me to do this because this is what I can do in the cleanup of datasets now. Perhaps because this filtered list is more sophisticated with this parent/child relationship.

**Comment by danyill** [comment]
To be fair we are not using the identity string in the list items.

However even when I add it:

```js
import { compareNames, getNameAttribute, identity} from '../../foundation.js';

  renderGoose(element: Element): TemplateResult {
    return html`<mwc-list-item
      value="${identity(element)}"
      @click=${() => this.onGooseSelect(element)}
      graphic="large"
    >
      <span>${element.getAttribute('name')}</span>
      <mwc-icon slot="graphic">${gooseIcon}</mwc-icon>
    </mwc-list-item>`;
  }
```

I don't appear to be able to use this value field for filtering.

```html
<mwc-list-item graphic="large" value="L1_PU_GE_D60>>Master>gcb1" mwc-list-item="" tabindex="-1" aria-disabled="false" class="">
```

Perhaps I am confused :confused:. My misunderstanding was based on the comment [here](https://github.com/openscd/open-scd/pull/568#issuecomment-1054302515).

I thought we had a way to provide "hidden field searching" through the value attribute but maybe this is not how it works. `filtered-list.ts` seems to instead only work based on the item and its children's `innerText`.

Oh this is getting more confusing. I was utterly convinced in my mind that `onFilterInput` would do something like this:

```js
  onFilterInput(): void {
    this.items.forEach(item => {
      const text: string = (
        item.innerText +
        '\n' +
        Array.from(item.children)
          .map(child => (<HTMLElement>child).innerText)
          .join('\n')
          +
          Array.from(item.value.split('>')).join('\n')
      ).toUpperCase();
      const terms: string[] = this.searchField.value.toUpperCase().split(' ');

      terms.some(term => !text.includes(term))
        ? item.classList.add('hidden')
        : item.classList.remove('hidden');
    });
  }
```

But it doesn't (I added this bit: `Array.from(item.value.split('>')).join('\n')`) which gives the behaviour I was looking for but it may not be well thought out :wink:

**Comment by JakobVogelsang** [comment]
I think this is fixed sin't it? @danyill

**Comment by JakobVogelsang** [comment]
Of covered by another issue #904

**Comment by danyill** [comment]
I think we can let this go. Thanks!
