### ISSUE TITLE
Add documentation move button

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#670]
What is the purpose of the move button in the substation editor?
![image](https://user-images.githubusercontent.com/7427358/161727144-146ccb15-fca2-4726-9867-7f4d459f7975.png)
If I click on it, nothing seems to happen.

**Comment by JakobVogelsang** [comment]
Ideally form the UI of OpenSCD the user shall be capable to know the XML structure behind it. That is why the order of bays is the order in the SCL. And this is what this feature is for. You can reorder the sequence of bays, voltage levels, substations and conducting equipment

**Comment by Sander3003** [comment]
Thanks, I will try to reload the file to see if changes are made in de sequence order.

**Comment by Sander3003** [comment]
Some documentation / user support around this feature might be benifitial.

**Comment by Sander3003** [comment]
@DavoodSooran you can close this issue once you are done.

**Comment by DavoodSooran** [comment]
This document has been created and can be find below:

https://github.com/openscd/open-scd/wiki/Move-Button-:-The-%22Move%22-Functionality-in-the-Substation-Plug%E2%80%90in
