### ISSUE TITLE
XML editing button in SampledValueControl affected by label

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#673]
**Describe the bug**

In the recent SampledValueControl edit wizard, if Pro mode is enabled the edit/show XML screen styling is affected by the label

**To Reproduce**

1. Open a file with sampled values
2. In the substation editor click on the (S) menu
3. Select a SampledValueControl
4. See error (screenshot below).

**Expected behavior**

The edit button is visually distinguished from the title.

**Screenshots**

![image](https://user-images.githubusercontent.com/674783/161853045-c759098e-0fcc-46a4-be78-24bcdd989b9f.png)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser:  Chrome
 - Version: Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by Sander3003** [comment]
Solution: wider the screen to make it fit.
