### ISSUE TITLE
Regenerate Snapshots from Tests

### ISSUE THREAD

**Issue by dlabordus** [openscd/open-scd#676]
As a developer
I would like to know how to manage Snapshots
So it does not get messy

Acceptance:
What/why/when explained, including:
How do we work with snapshots
General behavior for approving snapshots in PR's

Background (old)
Maybe it's a idea to regenerate all the Snapshots made by the tests in OpenSCD.
I noticed that there are old captures still in the files, because test descriptions were renamed.

How to prevent this in the future? Because it can become messy.

**Comment by Sander3003** [comment]
It would be nice some dev guidelines can be added to the contributing.md on how to handle this.

**Comment by Sander3003** [comment]
@dlabordus is this still an open issue?

**Comment by dlabordus** [comment]
As you say @Sander3003 probably need some instructions in the contributing.md, because there is still often junk in the snap.js files.

When snapshot are changing is better to first remove the file and regenerate it. Afterward it easy to check the diff and verify if the changes are correct/expected.

**Comment by Sander3003** [comment]
Sounds good! Lets refine it and put it on the backlog!
