### ISSUE TITLE
Errors/typos in de.ts + en.ts

### ISSUE THREAD

**Issue by VerPer00** [openscd/open-scd#68]
At first glance, the following terms need correction:
(- old version > new, corrected version)

German:
- Neues Project > Neues Projekt
- IED Importieren > IED importieren
- Lade Project {{ name }} > Lade Projekt {{ name }}
- Bitte laden Sie eine SCL Datei, die IED Elemente enthält. > Bitte laden Sie eine SCL-Datei, die IED-Elemente enthält.

English:
- {{ name }} read error > Error reading {{ name }}
- {{ name }} read aborted > Aborted reading {{ name }}
- {{ name }} added > Added {{ name }}
- {{ name }} removed > Removed {{ name }}
- {{ name }} moved > Moved {{ name }}

And a few capitalization errors :)
(we only capitalize all words in a term if it's a window/section header)

- No Substation > No substation
- Substation Name > Substation name
- Substation Description > Substation description
- Add Substation > Add substation
- Edit Substation > Edit substation
- Add Voltage Level > Add voltage level
- Voltage Level Name > Voltage level name
- Voltage Level Description > Voltage level description
- Nominal Frequency > Nominal frequency
- Number of Phases > Number of phases
- Nominal Voltage > Nominal voltage
- Edit Voltage Level > Edit voltage level
- Bay Name > Bay name
- Bay Description > Bay description
- Add Bay > Add bay
- Edit Bay > Edit bay
- Conducting Equipment Name > Conducting equipment name
- Conducting Equipment Description > Conducting equipment description
- Conducting Equipment Type > Conducting equipment type
- Add Conducting Equipment > Add conducting equipment
- Edit Conducting Equipment > Edit conducting equipment
- Select Logical Devices > Select logical devices
- Select Logical Nodes > Select logical nodes
- Please load a SCL file that contains IED elements first. > Please load an SCL file that contains IED elements.
- filter > Filter

**Comment by JakobVogelsang** [comment]
Thank you very much @VerPer00 ! We are refactoring the files currently triggered by issue #57 . Your findings will be incorporated in the next pull request.

**Comment by JakobVogelsang** [comment]
Findings merged to master. Thx
