### ISSUE TITLE
IED Editor collapses all containers when opening a Wizard

### ISSUE THREAD

**Issue by dlabordus** [openscd/open-scd#690]
**Describe the bug**
In the IED Editor more Wizards are used to edit or show data. When you open the containers to view DA Values and then click the Edit IED button the screen is reset to the default collapsed containers. The same for the new Info Wizards for DO/DA Elements.

**To Reproduce**
1. Open a SCD file with IED's configured
2. Go to 'IED Editor'
3. Open all type of containers to view information
4. Click on 'Edit' icon of the IED
5. All manual opened container are closed

**Expected behavior**
It would be nice that the IED Editor keeps track on which containers are expended/opened and uses that info when repainting/rebuilding the screen. When a new document is opened this needs to be reset.

**Comment by Sander3003** [comment]
Also remember the last selected element.

**Comment by Sander3003** [comment]
This will be adressed with the major OpenSCD core fix.

**Comment by Sander3003** [comment]
Good for now!
