### ISSUE TITLE
Add 104 Addresses to existing DOI/DAI (CDC: SPS/DPS/INS/MV)

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#698]
**Is your feature request related to a problem? Please describe.**
As a 104 Engineer I want to add Address Elements to a existing DOI/DAI which don't have Address Element yet. 
Only the simple CDC Types, like SPS/DPS that will create one Address Element below a one DAI Element. 
Support multiple value for TI with different Queries to retrieve the DAI Element, like MV/INS.

**Describe the solution you'd like**

![104mockups-104phase 3 add 104 addresses drawio (3)](https://user-images.githubusercontent.com/7427358/168560949-63c66dec-af8e-41a9-9060-0bc40914ea5c.png)

The button "Add Address" will be shown below/right, not related to any of the containers, like IED/DOI...

If the user wants to add a 104 address, the user should click on the button "Add address".  A new windows should show to select the DOI. This can be similar to the dataset like window:

![image](https://user-images.githubusercontent.com/7427358/168561952-fb50f8fc-efef-4aae-8d02-8c9ea1c265e6.png)

The structure of the IED editor can be used here. IED/AccessPoint/LogicalDevice/LogicalNode/DOI. Only show DOI Elements for which there are no Address Elements already added and the CDC is supported. The supported CDC should be a list that will be expanded with the Simple CDC Types for which only a single Address Element will be created.

**Question**: Do we want below behavior, because multiple Address Elements can be created in the future? Or maybe only if a single Address Element is created?
After creation, a pop-up should be shown to change the relevant 104 values (see: https://github.com/openscd/open-scd/issues/686)

**Remark**: Make some generic logic that uses the CDC/TI to determine how many Address Elements need to be created and have a default TI Value or ask the User which TI Value to use.

**Comment by Sander3003** [comment]
We need to seperate this in 2 stories.

**Comment by dlabordus** [comment]
Also supports:
- CDC Security violation counting (SEC)
- CDC Single point setting (SPG)
- CDC integer status setting (ING)
- CDC analogue settings (ASG)
