### ISSUE TITLE
Allow re-opening of the same file

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#7]
`<open-scd>` is currently only listening to `#file-input`'s `change` event, meaning a file is not loaded if it's the same file as before.

We could either implement a "reload file" button parsing the same `File` object again or listen to something like `#file-input`'s `click` event, checking whether the selected file has changed, and asking whether to reload if not.

**Comment by c-dinkel** [comment]
Which pull request resolved this issue?

**Comment by c-dinkel** [comment]
This was never resolved.
