### ISSUE TITLE
Naming in the subscription editor

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#729]
**Is your feature request related to a problem? Please describe.**

I (am sorry,) didn't manage to look at this at the time the PR was raised. I think the subscriber wording could be clearer:

![image](https://user-images.githubusercontent.com/674783/167245813-98bbcf6d-4d36-43ba-b6ee-a1087a74a6b5.png)

Any time we need 6-7 words to describe a radio button (and brackets!), the world seems to have become very complicated.

As a user of OpenSCD I want to not read a lot of words, and have descriptions of functionality be short and intuitive.

**Describe the solution you'd like**

I'd like to propose that the left radio button be: "Publisher | Subscriber" and the right radio button be "Subscriber | Publisher", perhaps something like this:

![image](https://user-images.githubusercontent.com/674783/167246011-91971e56-34ba-441a-bfd4-ea1b546830e0.png)

WDYT?

**Comment by Sander3003** [comment]
Sounds good to me. @JakobVogelsang what do you think?

**Comment by JakobVogelsang** [comment]
This sound good to me :)
