### ISSUE TITLE
Display IED services

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#738]
**Is your feature request related to a problem? Please describe.**
As an engineer
I want to see the IED services available and related settings
So I can see if the IED has the capability needed for my use-case

Example of an services section:
```

<Services nameLength="64">
      <DynAssociation max="10"/>
      <SettingGroups>
        <SGEdit resvTms="false"/>
        <ConfSG resvTms="false"/>
      </SettingGroups>
      <GetDirectory/>
      <GetDataObjectDefinition/>
      <DataObjectDirectory/>
      <GetDataSetValue/>
      <SetDataSetValue/>
      <DataSetDirectory/>
      <ConfDataSet max="32" maxAttributes="100" modify="true"/>
      <DynDataSet max="32" maxAttributes="100"/>
      <ReadWrite/>
      <ConfReportControl max="16" bufConf="true" bufMode="both"/>
      <GetCBValues/>
      <ReportSettings cbName="Conf" datSet="Conf" bufTime="Conf" intgPd="Conf" optFields="Conf" owner="true" resvTms="true" rptID="Conf" trgOps="Conf"/>
      <LogSettings cbName="Conf" datSet="Conf" intgPd="Conf" logEna="Conf" trgOps="Conf"/>
      <GSESettings cbName="Conf" datSet="Conf" appID="Conf"/>
      <GSEDir/>
      <GOOSE max="8" fixedOffs="false"/>
      <SMVsc max="12" delivery="both" deliveryConf="true"/>
      <ConfLNs fixLnInst="false" fixPrefix="false"/>
      <ClientServices bufReport="true" goose="true" gsse="false" maxAttributes="250" maxGOOSE="32" maxReports="32" maxSMV="32" readLog="false" supportsLdName="true" sv="true" unbufReport="true">
        <TimeSyncProt sntp="true" c37_238="false" other="false"/>
      </ClientServices>
```

**Describe the solution you'd like**
A viewer of available services and settings in the IED editor plug-in via a menu on the IED and access point.

![image](https://user-images.githubusercontent.com/7427358/168283434-35d5b50a-cd3f-4622-af7d-239676b373c0.png)

Icon:
https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aservice_directory%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

The IED services can be defined under and IED or under an accespoint.

**Requirements**
Read-only of the related fields. The services can be defined within an IED or access point:

![servicesXSD](https://user-images.githubusercontent.com/7427358/169646145-d8246fec-60cd-41d1-8bf6-df5a77e7fbcc.png)

**Suggestions for a specific user interaction**
Het services should shown based on the XSD capabilities and based on the appearance in the XML file, they should be shown in the supported or unsupported section. In case of the unsupported section, the values do not appear in the SCL file.

![image](https://user-images.githubusercontent.com/7427358/177317067-dd090a2f-5a5b-4ba9-bfe0-07d4228ce55c.png)
https://excalidraw.com/#json=5TjMXf_mJl9GnOWa2djPS,ZxUM-NNhQFRHBNP_XsHdeA

These items will get their own screen via the edit button (separate issues):
SMVSettings
ClientServices

**Additional information**
XSD (tservices):
https://github.com/com-pas/compas-scl-xsd/blob/develop/src/main/resources/xsd/SCL2007B4/SCL_IED.xsd

**Comment by Sander3003** [comment]
All possible parameter according to the 2007B4 XSD:
![servicesXSD](https://user-images.githubusercontent.com/7427358/168844893-37679ffa-74e0-4200-8c0c-319aa2698365.png)

**Comment by Sander3003** [comment]
Relates to https://github.com/openscd/open-scd/issues/147

**Comment by Sander3003** [comment]
@JakobVogelsang will build a UI mockup

**Comment by Sander3003** [comment]
A describtion of the services can be found in IEC 61850-6:2009

**Comment by JakobVogelsang** [comment]
This issue is transformed into a project with several steps.
