### ISSUE TITLE
Losing data when a user click the back button in the browser

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#743]
**Is your feature request related to a problem? Please describe.**
As an engineer
I want to be informed to save the data first before I click the "back" button in modern browers
So I do not lose my changes

**Describe the solution you'd like**
Show a warning when a user want to back in the browser.

**Requirements**
Only show the warning if a document is open in OpenSCD

**Suggestions for a specific user interaction**
A pop-up window should show up:
Are you sure? Your work will be lost

**Additional information**
Example:
https://stackoverflow.com/questions/38306510/alert-on-browser-back-button-click-or-page-refresh

**Comment by ca-d** [comment]
TODO: assign @juancho0202
