### ISSUE TITLE
Importing IED

### ISSUE THREAD

**Issue by OzaDay00** [openscd/open-scd#77]
![OpenSCD](https://user-images.githubusercontent.com/76159349/102476857-e00bbf80-405b-11eb-8997-5d7657621282.png)
Hey, Is there any reason that i cant import additional IEDs in to a SCD file which is already open ? It was available in previous OpenSCD.

Or should we stick to the application instructions?
![2020-12-17 11_38_04-Inbox - ozan dayanc@omicronenergy com - Outlook](https://user-images.githubusercontent.com/76159349/102477224-5d373480-405c-11eb-91b6-57026689fdcd.png)

**Comment by JakobVogelsang** [comment]
We did not implement this feature yet. When we want to do it correct this feature takes some time. How badly do you need this feature for the scope `Improve SCL file quality`?

**Comment by OzaDay00** [comment]
SCL files from the customers are mostly piece meals. Eventually, We have to merge them to assign station, voltage, and bay levels. 
This way is mostly works for StationGuard and StationScout on visualization to customer.
