### ISSUE TITLE
Log Information

### ISSUE THREAD

**Issue by OzaDay00** [openscd/open-scd#79]
Hey,
I am not sure If there is a purpose to keep the System behavior in the Log section as well.
But since I save the project, or change the language in the left toolbar, It didn't appear in the logs.

Additionally 
![2020-12-18 11_25_54-OpenSCD and 1 more page - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/76159349/102604568-a783e880-4124-11eb-821a-a5f5b2d37755.png)
 It would be better to have white text on the toolbar when you turn on the dark theme. Its nearly not visible

**Comment by JakobVogelsang** [comment]
Thank you very much for your feedback. There are some questions in one Issue and I would like to ask you to create for each a new `Issue` in the future. 

1. Information in the log (will be tracked with this Issue)
I would propose to add saving actions to the log and would not include setting changes. 

2. Coloring issue
Unfortunately there is a bug in the library we are using. We are confident that the bug will be solved in near future. I created a new Issue #80 that you can track.
