### ISSUE TITLE
Change Control Model in the 104 Plugin

### ISSUE THREAD

**Issue by dlabordus** [openscd/open-scd#797]
**Is your feature request related to a problem? Please describe.**
As a 104 Engineer I want to updated the Control Model (DAI) value in the 104 Plugin when adding Address to a DOI/DO Element. This way the creation of the Address Elements can be controlled. 

**Describe the solution you'd like**
Depending on the value of CtlModel (DAI) it's determined which Address Element are created, 'status-only' will not create Address elements as defined in the control section of the DAI Elements.
When new Address Elements are added for a DOI/DO a prepare window is shown to configure how the Address elements are created, in this window we will add the option to Change the value of the CtlModel DAI Element, if a DAI/DA Element is available for the CtlModel. The values can be retrieved from the Enum part of the Template section (SCL).
Also the value may only be changed if the attribute 'valImport' of the DA is false. If the value is 'true' the vendor indicates that this isn't allowed.

**Additional information**
No additional information.

**Comment by Sander3003** [comment]
Change the Control Model is possible in the IED Editor.
