### ISSUE TITLE
SampledValue editor errors on scd file without SampledValue subscriber information

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#808]
**Describe the bug**

Unexpected console error.

**To Reproduce**

1. Open for example: `test/testfiles/zeroline/functions.scd`. 
2. Select the "Sampled Values subscriber" editor.
3. Observe a console log error.

**Expected behavior**

No console errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/674783/172037257-63773bb2-f2f6-40df-8d10-9b1c4ca42b2f.png)

**Desktop (please complete the following information):**

- OS: Linux, Kubuntu 22.04
- Browser: Chrome
- Version: Version 102.0.5005.61 (Official Build) (64-bit)

**Comment by Sander3003** [comment]
Possibly solved by https://github.com/openscd/open-scd/pull/830
