### ISSUE TITLE
Unable to create a subnetwork

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#809]
**Describe the bug**

I cannot create a subnetwork although the application presents the option.
Unusable buttons, locked gates and immovable objects cause user angst!

**To Reproduce**

1. Open a new project.
1. Go to Communication
2. Click on "Add Subnetwork"
3. Enter some fields
4. Click Add. Nothing happens.
5. But there is an error in development tools console.

**Expected behavior**

Either I should receive an error if the dialog does not go away or the dialog should go away with the action complete.
As a user I should not be able to enter into a "create action" which cannot complete for unknown reasons.

**Screenshots**

![image](https://user-images.githubusercontent.com/674783/172037778-1d21c53a-d596-4986-92a6-9181af8f5fcd.png)

![image](https://user-images.githubusercontent.com/674783/172037887-a36ded81-2a20-4279-9e39-9df63c171995.png)

I think the document is missing as a whole which causes this because the project is "empty".

**Desktop:**
 - OS: Linux, Kubuntu 22.04
 - Browser: Chrome
 - Version: Version 102.0.5005.61 (Official Build) (64-bit)

**Comment by ca-d** [comment]
Drive-by fixed by https://github.com/openscd/open-scd/pull/814 .
