### ISSUE TITLE
Large (DAI) values in IED Editor are displayed outside the container

### ISSUE THREAD

**Issue by dlabordus** [openscd/open-scd#823]
**Describe the bug**
When a (String) value for a DAI Element is entered, but is very long the text is outside the container, see screenshot.

**To Reproduce**
1. Go to 'IED Editor'
2. Open a existing DA Value
3. Edit the value or add a value (DAI) of a VisString type
4. Enter a very long text
5. See screenshot how value is displayed

**Expected behavior**
Text stays within container, solution can be discussed, (forced) wrap on multiple lines or show a ellipsis (...) 

**Screenshots**
![image](https://user-images.githubusercontent.com/1453032/174532825-91b1f4fc-c7c8-4288-93d4-78cd8e09e632.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Additional context**
-

**Comment by Sander3003** [comment]
Approach:
Use multiple lines
If spaces are within the line, use a logic place to cut
If it is a full string, cut where needed.
