### ISSUE TITLE
WIP: Schedule node editor

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#831]
**Is your feature request related to a problem? Please describe.**
As a openSCD user
I want to program schedule LN (FSCC, 61850-90-10)
So I can program DER agents with 61850

**Describe the solution you'd like**

**Requirements**
What are the minimal requirements you need to have for this feature wish

**Suggestions for a specific user interaction**
Have a specific UI gesture in mind? If you want to discuss this first, please provide your suggestion in the discussions field.

**Additional information**
Example SCL file with DER scheduling:
https://github.com/alliander-opensource/der-scheduling/blob/main/models/der_scheduler.cid

Schedule controller: FSCC
Schedule: FSCH

**Comment by JakobVogelsang** [comment]
Your feature request is not completely clear to me. If you are asking for something that allows to create the whole structure including children than the `Template` editor is the one that can do it right now. Or do you want to include it into the `templates.scd` in OpenSCD's public folder?

**Comment by JakobVogelsang** [comment]
This is a collection of information that need to be edited:
 For the schedule (FSCH):
| Setting | Limits | short description | 
| --- | --- | --- | 
| SchdPrio | 0...n (INT32) | priority fo this schedule | 
| NumEntr | > 0 INT32 |  the number of the valid instantiated value |
| SchdIntv | > 0 INT32 | son't get that myself yet :) |
| ValASG | FLOAT32 + multiplier + SI unit | Schedule value for primary data like current voltages frequencies and others purpose |
| ValING | INT32 | Schedule value in integer | 
| ValSPG | boolean | Schedule value in boolean | 
| ValENG | ? | ? | 
| StrTm | `Timestamp` or `CalenderTime`| Start time of the schedule |
| EvTrgSPG | boolean | if can be triggered from outside | 
| InSynORG | `ObjectReference` | a pointer to the control type object  that listens for trigger |
| SchdReuseSPG | boolean | indicates if the schedule is periodical |

**Comment by Sander3003** [comment]
The plan for now is to filter LN in the IED editor. User can make their modifications for now in the IED editor.
