### ISSUE TITLE
Overview of relevant parameters

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#835]
**Is your feature request related to a problem? Please describe.**

As an 61850 test engineer
I would like to see an overview of important 61850 configuration settings
So I can spot error pretty quickly.

Parameters per IED:

IEDname
IP adress (only 1 port available)
Subnetmask  (only 1 port available)
Template (IED description)

Current related TCTR (IL1 and RES):
Path:
IED name / LD0 / server / LD0 / TCTR 
/ ARtg  / setMag  = Primary rated current
ARtgNom / setMag = Network Nominal Current
ARtgSec / setVal = Secondary rated current 
VRtgSec / VRtgSec = Rated Secondary Value

Voltage related:
IED name / LD0 / server / LD0 / TVTR
VRtgScy = secondary rated voltage
VRtg = Primary rated voltage
Rat = Devision ratio / Ratio between the primary and secondary value of an instrument transformer.

LPHD / PhyNam / vendor = Vendor
LPHD / PhyNam / model = Model

**Background**
With template engineering, some parameters need to be adjusted when apply an template.

**Describe the solution you'd like**
The parameters can change over time, It would be nice if relevant parameters are configured in an configuration file (or equal).

**Suggestions for a specific user interaction**

![image](https://user-images.githubusercontent.com/7427358/175560457-7619af71-d277-4363-8a95-9ce59f5a43e9.png)
https://excalidraw.com/#json=cDNz1-4xVKzTOquYzmaat,CCts1udoBdSY9DwU3jADdQ

**Additional information**
For further reading including e.g parts of IEC 61850, Tissues or other sources that triggered your feature wish

**Open Questions**
Where can the SNTP IP address (primary/secondary) settings be found in the ABB SCL files? This can be build in a later version (once found).

Where to show the exact location?
Display the full path/query?

**Comment by Sander3003** [comment]
For the hardware
LPHD /model

Software/firmware:
LPHD / phynam /swRev
eSwNum

**Comment by JakobVogelsang** [comment]
There are several to deal with this. 
1. Have an `menu` type plugin that opens a dialog that can be designed as one like. Web component libraries grow bigger and bigger, and there are plenty with containing table views. For this purpose we might not even need that as it is read-only but use pure CSS and HTML.
2. Have a print function that just collects information from the `doc` and displays it as one wish. I could think of exporting to PDF or maybe even better CSV that can be saved and open in Excel.

The design of the table is very specific to the things needed within Alliander. Other users might want to have other signals/information to be shown. I therefore see two ways to do it. Either do it in compas-open-scd as an extra menu type plugin. Or create something that is customizable, which could be a multiple of the effort.

**Comment by Sander3003** [comment]
Move to CoMPAS; Use a table (HTML/CSS or a libary).

**Comment by Sander3003** [comment]
This will be a feature for CoMPAS due the utility specific nature of it: https://github.com/com-pas/compas-open-scd/issues/167
