### ISSUE TITLE
Compare IED from Actual Substation with IED from Template

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#836]
**Is your feature request related to a problem? Please describe.**
As a test engineer
I want to compare SCL IED Templates with IED Implementations
So I see the differences, based on the differences, I want to judge the amount of testing required

**Describe the solution you'd like**

1. Open the SCL File containing the IED Templates; This will pop-up the File Open Dialog of the browser, just like with Open Project.

2. Next step is that the user selects the IED to compare.
On the left side select an IED from the implementation and on the right side selects a IED template from the opened file.
![image](https://user-images.githubusercontent.com/7427358/176436438-76bd3466-8769-49b1-a669-7719410a575a.png)
https://excalidraw.com/#json=V5SUeZ88Qn8T3Viirh3f7,R8XqBOeEkqNSTQDenBIurw

3. The user will start the compare function.
With the compare function, the IED can be compared with the IED of the template.
In CoMPAS there is now a compare between versions and showing all difference in one wizard.
We like to move this functionality to OpenSCD and use that here to show the differences.

**Requirements**
What are the minimal requirements you need to have for this feature wish

**Additional information**
The compare will show the difference below the IED Element, so up to the LN(0), including the DOI/SDI/DAI.

** open question **
Is this functionality to have in OpenSCD? 
If not CoMPAS will do, if we do, move the compare function from CoMPAS to OpenSCD.

**Comment by dlabordus** [comment]
@Sander3003, for opeing from the CoMPAS Data Service I created a issue in CoMPAS (https://github.com/com-pas/compas-open-scd/issues/162) 
This can't of course be done here. We need to update the plugin the compas fork for this, as we did with the Open Project and others also.

**Comment by dlabordus** [comment]
@JakobVogelsang can you translate the following English term to German

`
  compare: {
    compareButton: 'Compare',
    attributes: 'Attributes from {{ elementName }}',
    children: 'Child elements from {{ elementName }}',
  },

  'compare-ied': {
    title: 'Compare IED with IED from template project',
    projectIedTitle: 'IED in project',
    templateIedTitle: 'IED in template project',
    selectIedButton: 'Select IED',
    selectTemplateButton: 'Select template project',
    noDiff:
      'No differences between the project IED "{{ projectIedName }}" and template IED "{{ templateIedName }}"',
  },

`

**Comment by JakobVogelsang** [comment]
```js
  compare: {
    compareButton: 'Starte Vergleich',
    attributes: 'Attribute von {{ elementName }}',
    children: 'Kindelement von {{ elementName }}',
  },

  'compare-ied': {
    title: 'Vergleiche IED mit Vorlage',
    projectIedTitle: 'IED Name aus Projekt',
    templateIedTitle: 'IED Name aus Vorlage',
    selectIedButton: 'IED auswählen',
    selectTemplateButton: 'Vorlage auswählen',
    noDiff:
      'Keine Unterschiede zwischen IED Projekt "{{ projectIedName }}" und IED aus Vorlage "{{ templateIedName }}" gefunden',
  },

`
