### ISSUE TITLE
Filter DAI Attributes when comparing IEDs with Template

### ISSUE THREAD

**Issue by dlabordus** [openscd/open-scd#841]
**Is your feature request related to a problem? Please describe.**
When comparing IEDs from the actual substation with IEDs from the Template File we want to ignore differences for some DAI Element, because they will always change compared to the template.

**Describe the solution you'd like**
During comparing of the IEDs exclude a list of DAI Element that shouldn't be compared.

Filter out the following parameters that change during engineering:
| type | element | attribute | description | 
| --- | --- | --- | --- |
| A | IED | name | 
| E | P |  | | 
| T | LN[lnClass="TCTR"] > ARtg > setMag > Val |  | Primary rated current |
| T | LN[lnClass="TCTR"] > Rat > setMag > Val |  | Current Transformer Ratio | 
| T | LN[lnClass="TCTR"] > ARtgNom > setMag > Val |  | Network Nominal Current |
| T | LN[lnClass="TCTR"] > ARtgSec > setVal > Val |  | Secondary rated current |
| T | LN[lnClass="TVTR"] > VRtg > setMag > Val | | Primary rated voltage |
| T | LN[lnClass="TVTR"] > Rat > setMag > Val | | Current Transformer Ratio |
| T | LN[lnClass="TVTR"] > VRtgSec > setVal > Val | | Secondary rated current |

**Requirements**
Data Attribute changes should be displayed.

**Additional information**
Related to issue https://github.com/openscd/open-scd/issues/836 and this issue should first be implemented.

**Open question(s)**
Filter protection settings?

**Comment by dlabordus** [comment]
@JakobVogelsang, if we are ignoring the element "P" is the filtering on IP and IP-SUBNET still needed?

**Comment by JakobVogelsang** [comment]
I would say no as we ignore every P element in the SCL file anyway. Do I miss something?

**Comment by JakobVogelsang** [comment]
Sorry yes I forgot to throw those out :)
