### ISSUE TITLE
WIP: Display IED services: SMVSettings

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#846]
**Is your feature request related to a problem? Please describe.**
As a CoMPAS user
I would like to seen the SMVSetting in the SCL file
So I can engineer according to the capabilities

**Describe the solution you'd like**
A display that opens after clicking the edit button in https://github.com/openscd/open-scd/issues/738.

**Requirements**
It should support the values 
![image](https://user-images.githubusercontent.com/7427358/177320154-cfa94ef2-dc11-49bf-a138-fe12da5f4a10.png)

**Suggestions for a specific user interaction**
Have a specific UI gesture in mind? If you want to discuss this first, please provide your suggestion in the discussions field.

**Additional information**
For further reading including e.g parts of IEC 61850, Tissues or other sources that triggered your feature wish

**Comment by Sander3003** [comment]
@JakobVogelsang is this still relevant or already covered by other stories

**Comment by JakobVogelsang** [comment]
Yes it is covered by this issue https://github.com/openscd/open-scd/issues/893
