### ISSUE TITLE
Creating Function in Substation section fails

### ISSUE THREAD

**Issue by SBaumgar** [openscd/open-scd#850]
**Describe the bug**
It is not possibe to create a function at any level. 

**To Reproduce**
1. on the voltage level 
2. Click right and select Function
3. See error

**Expected behavior**
A function similar to a equipment.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80691258/177817327-8c873222-b466-4406-a828-e33c65f31c9b.png)

**Comment by JakobVogelsang** [comment]
Hi @SBaumgar this is an updating issue introduced with performance improvement we did in OpenSCD. The element is still created, but you cannot see it. You can check by switching between two editors. This fix is on the way :)
