### ISSUE TITLE
Publisher editor feedback

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#853]
The new publisher editor is really, very nice, I was a little pushed to usefully review #844 at the right time.

I have a few comments, of variable quality as usual:

1. In a typical SCL file there appears to be an unused row at the top (number 1):
    ![image](https://user-images.githubusercontent.com/674783/177949653-861b8966-6bf6-411c-a62b-b8b7f1de378c.png)

2. A little thing: I like to see all IEDs but in a large file given that the IED name is shown in the secondary text it makes the information substantially less dense, e.g. this:
   
    ![image](https://user-images.githubusercontent.com/674783/177950009-ef33d949-cda3-4c3a-be75-f33c37e0445a.png)

> This is so very true. It comes down to a topic we have so often and did not find a good solution to that yet. I would propose to try the following here: Add a filter button for IEDs only. That will allow to work only with those. There rest of the list I would left untouched. What do you think about this?

    There are actually 4 devices with SEL487, but all the other "empty" devices "clutter" the display. I know it is the same and in other areas so this is probably just a general comment...

3. I like that the filter text is kept as I move the toggle at the top. Often in a material design component we would have an "x" that we could push on to cancel or reset the text (rather than click and then backspace it). I know we use this component everywhere and I haven't made this observation before!

4. It would be nice to have an "on hover" edit button as has been done in the SMV/GOOSE publisher for each control block and dataset.

> I will add that one :)

6. Perhaps it would be nice to use multiple columns to allow a denser display of information.

If these comments do not have merit, other than 1 they are matters of taste and it may be closed expeditiously! :wink: 

I could certainly look at a PR for any of these that are worthy.

**Comment by JakobVogelsang** [comment]
Can you share the SCL file for this bug?

**Comment by danyill** [comment]
> Can you share the SCL file for this bug?

It is the same as included in #854

**Comment by danyill** [comment]
I can't reproduce it with other SCL files, to be fair but so far I can't see a reason for this behaviour on a shallow inspection.

**Comment by JakobVogelsang** [comment]
This is because of this private section 
```xml
    <Private type="ABB Comm">
      <eComm:CommNode x="-536870912" y="-536870912" xmlns:eComm="http://www.abb.com/61850/2015/SCL_ABBCommunication">
        <eComm:IED />
        <eComm:Port id="SFP_301" xRel="0" yRel="0" />
      </eComm:CommNode>
    </Private>
```

The query on IED does find `<eComm:IED/>` as well. This is an easy one :)

**Comment by JakobVogelsang** [comment]
Sorry, I did edit your initial comment @danyill. But please see the block comments there. Would be curious what you think :)

**Comment by danyill** [comment]
> It comes down to a topic we have so often and did not find a good solution to that yet. I would propose to try the following here: Add a filter button for IEDs only. That will allow to work only with those. There rest of the list I would left untouched. What do you think about this?

I think an IED filter and a "thing inside IEDs filter" is a good idea.
Often an IED will have a naming convention which might allow the user to scope the query to "IEDS of interest", e.g. beginning "E1Q1" or "XYZ<baynum>" which could be useful for workflow (the user is working on this bay or in this area of the SCL file).

**Comment by JakobVogelsang** [comment]
Is fixed!
