### ISSUE TITLE
Filter option for logical nodes inside the IED browser

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#856]
**Is your feature request related to a problem? Please describe.**
As a user of OpenSCD I want to filter for display specific logical nodes. 

**Describe the solution you'd like**
Most data models become bigger and bigger. Therefore, filtering is key here. One of the most common filtering interests are function aka logical nodes. Being able to select multiple logical nodes that are display within the and the unselected are not displayed.

**Requirements**
- allow filter for logical node class as well as description when nsdoc description of available
- allow multiple selection
- allow select all (default)
- do not display leaf/empty (by filtering) logical devices 

**Suggestions for a specific user interaction**
![logical_node_filter_mock excalidraw](https://user-images.githubusercontent.com/66802940/178241434-605fbe33-a937-49d2-a91f-229c62d53499.png)

**Comment by danyill** [comment]
One use case for this is:

Evaluating IEDs is hard. I would quite like to import a number of ICD files and then look at some of the LNs for each IED.
For instance, I might want to see some system monitoring LNs to look at support for this (LTMS, LCCH, LGOS, LSVS), which not all IEDs support and I want to quickly see what the devices do.

Quite incidentally being able to split the IED editor to look at two IEDs side by side might be an interesting idea (e.g. a virtual IED and an instantiated one, some device which has been instantiated from a template, an as-built file and an issued one).

**Comment by JakobVogelsang** [comment]
This could be easily achieved by making the first list: IED to a multi list as well. We did not do that for performance reasons. Most data models are just too crazy. With the logical node filtering, we might consider. I still would suggest adding the logical node filtering first and in a second step try in prototypes how to show multiple devices. Would that be a way to go for you?
