### ISSUE TITLE
Subscriber Later Binding (GOOSE): Show connected and available `ExtRef` on `FCDA` selection

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#865]
As a user of OpenSCD I want to know if an existing data point in a `GSEControl` element is connected to a `ExtRef` element.

**Requirements**
- show all connected later binding `ExtRef` for the selected `FCDA`. That means the `ExtRef` element
1. has an existing attribute `intAddress`
2. has attributes `ldInst`, `prefix`, `lnClass`, `lnInst`, `doName` and `daName` that are equal to the same once in `FCDA`
3. has an attribute `iedName` equals to the `name` attribute of the `IED` element, where `FCDA` resides

Ed.2 and higher also
5. `serviceType="GOOSE"`
6.`srcLDInst`, `srcPrefix`, `srcLNClass`, `srcLNInst` and `srcCBName` fit to the `SampledValueControl` containing the `FCDA`

- mark all `ExtRef` with existing `intAddress` that are not connected (missing `iedName`, `ldInst`, `prefix`, `lnClass`, `lnInst`, `doName`, `daName`) as unsubscribed
- exclude all `ExtRef` from the source IED (same IED as the selected `FCDA`)
- disable elements in the unsubscribed list that cannot be connected (attributes `pLN`, `pDO`, `pDA` and `pServT` are present in the only criteria for now)

**Mockups**
![with_ext_ref_list excalidraw](https://user-images.githubusercontent.com/66802940/179539485-491958ee-05f3-4c00-a923-095d3302a5b7.png)

**Comment by danyill** [comment]
It may be a useful feature to also display the `desc` field on an `ExtRef` to help the user in mappings. In some cases the `intAddr` is not sufficient to clarify meaning (e.g. in a SEL relay this describe a internal bit and does not name a function directly).

**Comment by JakobVogelsang** [comment]
I updated the Mockup :)
