### ISSUE TITLE
Subscriber Later Binding: Check for CDC and bType

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#867]
As a user of OpenSCD I want to be warned that a later binding type `ExtRef` does not meet the requirements based on the attributes `pLN`, `pDO` and `pDA`.

**Requirements:**
- Check if `cdc` of both `ExtRef` and the `FCDA` does meet
- Check if `bType` of both `ExtRef` and `FCDA` meet

**Additional Information: **
Getting `CDC` for `FCDA`:
1. Take `ldInst`, `prefix`, `lnClass` and `lnInst`
2. Navigate to the `LN0` or `LN` in the source IED (the IED where `FCDA` resides in)
3. Take `lnType` attribute
4. Navigate to the `LNodeType` (`lnType` equals the `id` attribute of `LNodeType`)
5. Take the `doName` from the `FCDA`
6. Navigate to the `DO` element
7. Take the `type` attribute
8. Navigate to the `DOType` (`type` equals `id` attribute of the `DOType`)
9. Take the `cdc` attribute -> Done!

> In case `doName` has more than one name `A.phsA` and is seperated by `.` the steps 6 to 8 have to be repeated!

Getting CDC of `ExtRef`:
1. Take `pLN`
2. Navigate to the `LN0` or `LN` in the sink IED (the IED where `ExtRef` resides in) 
3. Do steps 3 to 9 (in step 5 take `pDO` instead of `doName`)
> In case `doName` has more than one name `A.phsA` and is seperated by `.` the steps 6 to 8 have to be repeated!

Getting `bType` of `FCDA`:
1. do steps 1 to 8
2. Take `daName` from `FCDA`
3. Navigate to `DA`/`BDA` element
4. Take the `bType` element
> In case `daName` has more than one name `cVal.mag.f` and is seperated by `.` the `BDA` is a child of a `DAType`.

Getting `bType` of `ExtRef`:
Same as the above, except that `pDA` has to be taken instead of `daName`

**Comment by dlabordus** [comment]
@JakobVogelsang, what needs to be done when cdc or bType don't match? So when the check fails.

**Comment by JakobVogelsang** [comment]
I think that in this case, we need to disable this `ExtRef` in the available to subscribe list indicating it as we do right now when there is `pLN`, `pDO`, `pDA` and `pServT`

**Comment by danyill** [comment]
Just to note that the "filter" requirements are used by Siemens SIPROTEC 5 relays at present.

Here's an example:

```xml
<ExtRef desc="PowS_BAY230MUCT.CT 1" intAddr="AmpSv;TCTR/AmpSv/instMag.i" serviceType="SMV" pServT="SMV" pLN="TCTR" pDO="AmpSv" pDA="instMag.i" iedName="XAT_232_M2" ldInst="PowS_MeasPointI3ph1" lnClass="TCTR" lnInst="1" doName="AmpSv" daName="instMag.i" srcLDInst="Mod3_MU1" srcLNClass="LLN0" srcCBName="MSVCB01" />
<ExtRef desc="PowS_BAY230MUCT.CT 1" intAddr="AmpSv;TCTR/AmpSv/q" serviceType="SMV" pServT="SMV" pLN="TCTR" pDO="AmpSv" pDA="q" iedName="XAT_232_M2" ldInst="PowS_MeasPointI3ph1" lnClass="TCTR" lnInst="1" doName="AmpSv" daName="q" srcLDInst="Mod3_MU1" srcLNClass="LLN0" srcCBName="MSVCB01" />
```

Here's an example file in case it is of use:

* [XAT_Prot2.zip](https://github.com/openscd/open-scd/files/9440815/XAT_Prot2.zip)
