### ISSUE TITLE
Subscriber Later Binding (SMV): Disconnect FCDA from ExtRef

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#868]
As a user of OpenSCD I want to disconnect an existing later binding connection (`ExtRef` with existing `intAddr`)

**Requirements:**
Remove attributes from `ExtRef`
- `iedName`
- `ldInst`
- `prefix`
- `lnClass`
- `lnInst`
- `doName`
- `daName`
- `serviceType`
- `srcLDInst`
- `srcPrefix`
- `srcLNClass`
- `srcLNInst`
- `srcCBName`

Leave attributes in `ExtRef`
- `intAddr`
- `pLN`
- `pDO`
- `pDA`
- `desc`

**Comment by dlabordus** [comment]
@JakobVogelsang, shouldn't we also remove doName and daName?

**Comment by JakobVogelsang** [comment]
True sorry for that!! I did update!

**Comment by JakobVogelsang** [comment]
A also saw that `desc` was missing in the leave as is list.
