### ISSUE TITLE
Create a basic EnumType manipulation capability

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#89]
As a user of OpenSCD I want to create/edit/delete `EnumType` elements. I want to create enumerations and use the pre-defined enumerations defined in `IEC 61850-7-3` and `IEC 61850-7-4`. 
 
**Requirement**:
- Pre-defined enumerations from `IEC 61850-7-3` and `IEC 61850-7-4` shall not be hard-coded and stored in a extra files and data structure to allowing easier contribution adding/updating these enumerations. 
- Pre-defined enumeration contain 
  -  `EnumVal` value range (e.g.  not-supported | bay-control | station-control | remote-control | automatic-bay | automatic-station | automatic-remote | maintenance | process )
  - `EnumVal` attribute `ord` (e.g. 0 |  1 |  2 ...) 

**Type description**:
element|attribute | description |  
--- | --- | --- |
EnumType  | id | The identifier for the element. Is used in the type attribute to connect `EnumType` to `DA`,`DO`,`SDO `|   
EnumType  | desc | Description |    
EnumVal | ord | Contains  the  order  of  the  values |
EnumVal | desc | Description   |
EnumVal | value | Enumeration value | 

**Restriction** :
- Enumerations defined in `IEC 61850-7-3` start with `0` and enumerations defined in `IEC 61850-7-4` start with `1`. 
- Value range for pre-defined enumerations (deleting values is ok but not extra value can be added)

element|attribute | required |  pattern  | min length  | max length | 
--- | --- | --- | --- | --- | --- | 
EnumType | id | yes | xs:token `\S+`| 1  | 127 |   
EnumType | desc | no | xs:normalizedString | 0 |    |    
EnumVal| ord | yes | xs:int | 1  |   |    
EnumVal | desc | no | xs:normalizedString | 0 |    |
EnumVal | value | no | tEnumStringValue |  | 127  | 

**Type definition**:
type  |  pattern/value range  | min length  | max length |  
--- | --- | --- | --- | 
tEnumStringValue| `[\p{IsBasicLatin}\p{IsLatin-1Supplement}]*` |   |  127 |   

**Further Information Link**

**Edition 1 vs Edition 2**
- `EnumType` attribute `id` has no max value in Edition 1 and Edition 2 and is limited to 127 characters in Edition 2.1

**Example**:
```
<EnumType id="myOrCat">
	<EnumVal ord="0">not-supported</EnumVal>
	<EnumVal ord="1">bay-control</EnumVal>
	<EnumVal ord="2">station-control</EnumVal>
	<EnumVal ord="3">remote-control</EnumVal>
	<EnumVal ord="4">automatic-bay</EnumVal>
	<EnumVal ord="5">automatic-station</EnumVal>
	<EnumVal ord="6">automatic-remote</EnumVal>
	<EnumVal ord="7">maintenance</EnumVal>
	<EnumVal ord="8">process</EnumVal>
</EnumType>
```

**Comment by c-dinkel** [comment]
I'm a bit lost on how to enforce this requirement:

> deleting values is ok but not extra value can be added

The way we currently handle pre-defined EnumTypes is simply as a "new EnumType" creation template, with the resultant EnumType containing no reference whatsoever to the fact that a template was used to create it. This means in principle I could manually create a custom EnumType containing exactly the same EnumVals as one of the templates, in which case I would still have to be able to add "extra" values.

@JakobVogelsang do you have any idea how we might distinguish this? Or could we maybe relax the requirement?

**Comment by c-dinkel** [comment]
@JakobVogelsang Did you mean `textContent` by `EnumVal` attribute `value` in above table?

**Comment by JakobVogelsang** [comment]
Regarding your first comment:

We could relax this requirement. When defining it initially I Was thinking about a unexperienced user who could by mistake add some EnumVal to a pre-defined. 

Regarding your second comment:
Yes this is what I ment
