### ISSUE TITLE
Services edit wizard: Add wizard page for SMV related configurations

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#893]
As a user of OpenSCD I want to be able to see settings and configuration defined in `Services` section on IED as well as `AccessPoint` level.

**Requirements**
- clear representation of the XML file. Make differences in empty string and missing attribute visible
- no primary action - element cannot be changed
- if an attribute is missing, show its default value
- no german translation in helper text

**Mockup**
![grafik](https://user-images.githubusercontent.com/66802940/179922063-3107dfed-ae20-4ba0-a10f-353c62f653c7.png)

**Additional Information:**
attributes/elements definition acc. IEC 61850-6 (2007B4) from top to bottom as in the mockup

In element `SMVSettings`
|       | name | required | type | pattern | default | helper text |
| --- | --- | --- | --- | --- | --- | --- |
|  A | cbName | no | Enum | Conf, Fix | Fix | Whether SMV control block name is configurable offline (Conf) or fixed (Fix) |
| A | datSet | no | Enum |  Dyn, Conf, Fix | Fix | Whether SMV control blocks data set and its structure is configurable offline (Conf), online(Dyn) or is fixed (Fix) | 
| A | svID | no | Enum | Dyn, Conf, Fix | Fix | Whether SMV control blocks ID is configurable offline (Conf), online(Dyn) or is fixed (Fix) | 
| A | optFields | no | Enum | Dyn, Conf, Fix | Fix | Whether SMV control blocks optional fields are configurable offline (Conf), online(Dyn) or are fixed (Fix) |
| A | smpRate | no | Enum | Dyn, Conf, Fix | Fix | Whether SMV control blocks attribute smpRate is configurable offline (Conf), online(Dyn) or is fixed (Fix) |
| A | nofASDU | no | Enum |  Conf, Fix | Fix | Whether SMV control blocks attribute noASDU (number of timesstapms per packet) is configurable offline (Conf), online(Dyn) or is fixed (Fix) |
| A | samplesPerSec | no | boolean |  | false | Whether SMV supported sample rate definition as SamplesPerSec or SecPerSamples |
| A | synchSrcId | no | boolean |  | false | Whether grandmaster clock ID can be included in the SMV |
| A | pdcTimeStamp | no | boolean |  | false | Whether the PDC timestamp can be included into SMV |
| A | kdaParticipant | no | boolean |  | false | Whether server supports key delivery assurance (KDA) |

In element `SMVSettings>McSecurity`
|       | name | required | type | pattern | default | helper text |
| --- | --- | --- | --- | --- | --- | --- |
| A | signature | no | boolean |  | false | Whether calculation of a signature is supported for each GOOSE |
| A | encryption | no | boolean |  | false | Whether message encryption is supported for each GOOSE |

In element `SMVSettings>SmpRate`
|       | name | required | type | pattern | default | helper text |
| --- | --- | --- | --- | --- | --- | --- |
| T | no name is inner text | yes | unsigned int |  | none | Defines the implemented SmpRate in the IED |

In element `SMVSettings>SamplesPerSec`
|       | name | required | type | pattern | default | helper text |
| --- | --- | --- | --- | --- | --- | --- | 
| T | no name is inner text | yes | unsigned int |  | none | Defines the implemented SamplesPerSec in the IED|

In element `SMVSettings>SecPerSamples`
|       | name | required | type | pattern | default | helper text |
| --- | --- | --- | --- | --- | --- | --- |
| T | no name is inner text | yes | unsigned int |  | none | Defines the implemented SecPerSamples in the IED |

In element  `SMsc`
|       | name | required | type | pattern | default | helper text |
| --- | --- | --- | --- | --- | --- | --- |
|  A | max | yes | unsigned int | none | none | The maximum number of SMV control blocks the IED can publish |
|  A | delivery | no | Enum | unicast, multicast, both | multicast | Whether the IED supports publishing of muslticast, unicast or both types of SMV streams |
|  A | deliveryConf | no | boolean | none | false | Whether the system configurator is allowed to configure SMV control blocks |
|  A | sv | no | boolean | none | true | Whether IED supports layer 2 sampled value streams |
|  A | rSV | no | boolean |  | false | Whether the IED supports layer 3 sampled value streams |

In element `CientServices`
|       | name | required | type | pattern | default | helper text |
| --- | --- | --- | --- | --- | --- | --- |
|  A | sv | no | boolean |  | false | Whether the IED supports client side SMV related services |
|  A | maxSMV | no | unsigned int | none | none | The maximal number of layer 2 sampled value streams the client can subscribe to |
|  A | rSV | no | boolean |  | false | The maximal number of layer 3 sampled value streams the client can subscribe to |

In element `SupSubscriber`
|       | name | required | type | pattern | default | helper text |
| --- | --- | --- | --- | --- | --- | --- |
|  A | maxSv | no | unsigned int | none | none | The maximum number of SMV supervision supported by this IED (LSVS) |

**Comment by Stef3st** [comment]
@JakobVogelsang  Isn't SMsc element  suppose to be SMVsc? And isn't SubSubscriber element suppose to be SupSubscription?

**Comment by JakobVogelsang** [comment]
That could be very well the case. I would ask you to look it up in the schema 2007B4. You can find it in the schema.ts file in the code.
