### ISSUE TITLE
Pretty-print XML in code editor

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#895]
**Is your feature request related to a problem? Please describe.**

For advanced editing and looking at an SCD file, some editors pretty-print the XML and some do not.

**Describe the solution you'd like**

Either a reformat for the whole document or a reformat within the code editor.

**Requirements**

A mechanism for reformatting the document or what the user sees in the Ace editor.

**Suggestions for a specific user interaction**

We could have a reformat button in the Ace editor (the green circle).
The XML would then be reformatted (red arrow).

![image](https://user-images.githubusercontent.com/674783/179863931-aa433ee4-cb1a-4ef7-b6a4-e0dd5486c359.png)

**Comment by danyill** [comment]
We _could_ use [xml-formatter](https://www.npmjs.com/package/xml-formatter) which seems fairly mature and well used for this and AFAICT the MIT license is compatible with Apache2.

Would we trigger code formatting on actions which update the XML element, provide a menu item or only do this in a pretty-print of the editor (and possibly a document save)?

**Comment by dlabordus** [comment]
I think there is some custom method already in OpenSCD that formats the XML when the SCD is saved.
This probably can also be used in the Code Editor to first format it, before showing.
