### ISSUE TITLE
Substation structures SCDs created by OpenSCDWeb are not compatible with OpenSCD

### ISSUE THREAD

**Issue by DiegoGasca** [openscd/open-scd#92]
Creating a project in OpenSCD Web from scratch with only substation information and without IEDs (because the import IED is still not implemented) is not compatible with OpenSCD (2.8.1).

The SCD is opened but without Substation structure, no errors are displayed

**Comment by JakobVogelsang** [comment]
See comment in issue #93. This is probably the same bug. Will be tracked in #93
