### ISSUE TITLE
Schema invalid file when subscribing

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#929]
**Describe the bug**
Subscribing causes schema invalidity

**To Reproduce**
1. open project with two `IED`s and one `GSEControl`
2. got to Subscriber editor plugin
3. subscribe GOOSE
4. see error from schema validator

**Expected behavior**
OpenSCD action should not be schema invalid

**Additional context**
The error pops up, because the attribute `srcLNInst` in the element `ExtRef` cannot be an empty string. Instead of an empty string, the attribute should not be present in the file.

**Comment by danyill** [comment]
I have tested and believe this also applies to sampled values in the Subscriber(SMV) plugin.

Additionally, I think it is possible `lnInst` is entirely missing, which is allowable (only) for LLN0 according to Part 6 (Table 8). At the moment we don't handle this correctly either if I am not mistaken. Given that LLN0 is where GSEControl and SampledValueControl elements must reside we need to cater for this.

I will have a PR for this in a day or two, I hope.

**Comment by danyill** [comment]
Eek! And then I see @dlabordus got there first!
