### ISSUE TITLE
Create an SCD block the tabs in OpenSCD 2.8.1 until save and re-open

### ISSUE THREAD

**Issue by DiegoGasca** [openscd/open-scd#93]
Creating a SCD from scratch in OpenSCD 2.8.1 block all the tabs and buttons for create the substation.
 
When the project is saved and re-open then the tabs and buttons are still available

**Comment by JakobVogelsang** [comment]
Thank you for your contribution. We think this is a bug. When creating a substation from scratch the namespace attribute `xmlns` is an empty string in the element `Substation`. Can you conform this? 

We will track this bug in this issue.
