### ISSUE TITLE
Remove `GSEControl` in the publisher plugin

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#947]
As a user of OpenSCD I want to be able to remove a `GSEControl` element in the publisher plugin.

**Requirements**
- add a meta icon button to the list element representing a `GSEControl` element
- use Google material icon  "delete"
- remove the `GSEControl` element
- remove referenced `DataSet` !!Only if it used for this control block only

- remove use of the control block:  `ExtRef` element with fitting `iedName`, `serviceType`, `srcLDInst`, `srcPRefix`, `srcLNClass`, `srcLNInst`, `srcCBName` by removing those attributes.
1. `iedName` is the `name` attribute of the `IED` element where the source `ReportControl` resides in
2. `serviceType` is `GSE`
3. `srcLDInst` is the `inst` attribute of the `LDevice` element where the source `ReportControl` resides in
4. `srcPrefix` is the `prefix` attribute of the `LN(0)` element where the source `ReportControl` resides in
5. `srcLNClass` is the `class` attribute of the `LN(0)` element where the source `ReportControl` resides in
6. `srcLNInst` is the `inst` attribute of the `LN(0)` element where the source `ReportControl` resides in (empty string is schema invalid)
7. `srcCBName` is the `name` attribute of the `ReportControl` 
8. Update when `instAddr` is present and remove attributes
9. Remove `ExtRef` when `intAddr` is missing

- reuse the complex action title from the edit wizard for `GSEControl` elements

**Additional Information**
control blocks as the `GSEControl` are connected to their payload through an attribute `datSet`. This attribute is the name of the element `DataSet` that defines the payload. The restriction here is that the `SampledValueControl` element and is referenced `DataSet` element must be in the same parent. This connection of the payload through referencing allows to reuse `DataSet` element by multiple control blocks. We therefore have to be careful when deleting the control block. Not removing the references `DataSet` would lead to unlinked `DataSet`s. Removing without checking would lead to errors. We can and must remove when the `DataSet` is used by only one control block

**Comment by Sander3003** [comment]
@JakobVogelsang is their a difference between the 2003 and newer versions?

**Comment by JakobVogelsang** [comment]
This is not applicable, as implemented in the "new" publisher plugin.
