### ISSUE TITLE
Feedback on Later Binding SMV Plugin

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#958]
**Is your feature request related to a problem? Please describe.**

This is some early, highly optional feedback on the excellent SMV Later Binding plugin. I did not manage to find time to comment during the review cycle, sorry.
We used this plugin (briefly) to configure some SMV subscriptions, and here is some feedback for enhancements at some stage.

**Describe the solution you'd like**

1. Initially, the person I tried out this extension on was confused about how to use it. I think perhaps some terminology changes would help.
    a. For the publisher on the left-hand side, I'd like to suggest a terminology change. Instead of "List of Sampled Values Controls with linked FCDAs" we could have (as per the other SMV plugin): "Sampled Values Publisher".
    b. For the subscriber on the left-hand side, I'd like to suggest we rename this from, "Selected Sampled Value data "smvcb0" / FCDA "AmpSv.instMag.i"" to: "Subscriber to". I'm not sure the control block name or the FCDA is useful if item 2 below is implemented. But if they are useful, I think including the IED name would be helpful. In many cases, merging units will have the same SMV control block name.

2. The selection on the LHS becomes lost when carrying out activity on the right-hand side. In other plugins (for instance, the Publisher plugin) we don't lose this, and it has a light green background (I think this is the `activated` property). This is valuable context for the user.

3. While the later binding plugin provides good functionality for the action of binding, it doesn't readily allow an overview of the configured ExtRefs which most tools provide, see the following screenshots from other applications which provide a tabular overview for each FCDA.

    a. AcSELerator Architect
        ![image](https://user-images.githubusercontent.com/674783/187053306-bd7bb32d-2f92-4a6c-9411-62ade3174198.png)

    b. Siemens DIGSI 5
        ![image](https://user-images.githubusercontent.com/674783/187053346-755e6265-a19f-4f84-9681-09099ebf1a5c.png)

    c. We could do this through a separate plugin. Perhaps this is a useful overview for all the different editors. But if you are doing the mappings for a three-phase set of currents and voltages, for example, it is helpful to be able to see what is "already done and what is still to do".
    d. Another idea might be to allow clicking on the IED, and when this happens for all items in the SMV control block to be a synchronised list between the values on the left and right-hand screen, but this might not readily fit a mobile form factor.

**Comment by JakobVogelsang** [comment]
Regarding point 3 of your feedback, I would propose to add the number of connection to the list item representing the `FCDA` element like so

![grafik](https://user-images.githubusercontent.com/66802940/187226593-dee2de31-6672-4f6d-86b8-a1d5626a72da.png)

**Comment by danyill** [comment]
> Regarding point 3 of your feedback, I would propose to add the number of connection to the list item representing the `FCDA` element like so

I think that's a good idea.

**Comment by danyill** [comment]
Re-opening until #993 is dealt with.
