### ISSUE TITLE
Add read-only SubEquipment editor to the Substation plugin

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#960]
As a user of OpenSCD I want to see `SubEquipment` element in the SCL in the substation plugin

**Requirements**
- make use of `action-pane`
- title is "SubEquipment.name — SubEquipment.desc (SubEquipment.phase)"
- show in all possible parents that is `PowerTransformer`, `ConductingEquipment`, `TransformerWinding`, `TapChanger`
- show all possible children, that is: `LNode`, `EqFunction`
- show only with function filter disabled `showfunction=true`

**Comment by pascalwilbrink** [comment]
* Add snapshot tests to both the sub-equipment-editor and possible parents (power-transformer-editor and conducting-equipment-editor)
