### ISSUE TITLE
Add "add" button to the `SubEquipment` editor

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#961]
As a user of OpenSCD I want to add possible child element `LNode` and `EqFunction` to the `SubEquipment` parent.

**Requirements**
- add `playlist_add` button to the sub equipment editor in the substation plugin
- show menu in icon button click: selection based on allowed children AND existing create wizards in the wizard-library
- open the create wizard for the selected element

**Comment by Sander3003** [comment]
Waiting for a fix of @Stef3st in order to render the menu correctly all the time.

**Comment by marcvanraalte** [comment]
#961 is closed
