### ISSUE TITLE
Add edit wizard for `SubEquipment` element into the wizard library

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#962]
As a user of OpenSCD I want to change the attributes in the `SubEquipment` element.

**Requirements**
- add edit button to the sub equipment element in the substation section 
- click triggers to open the edit wizard for `SubEquipment` from the wizard library 

**Restrictions**
| name | required | type | pattern or restriction | default | helper text |
| --- | --- | --- | --- | --- | --- |
| name |  yes |  xs:normalizedString | min. lenght 1 | no |scl.name |
| desc | no | xs:normalizedString | no | no | scl.desc |
| phase | no | enumeration | `A`, `B`, `C`, `N`, `all`, `none`, `AB`, `BC`, `CA` | `none` | "Phase" | 
| virtual | no | boolean | no | false | no |

**Comment by pascalwilbrink** [comment]
closed by #1063
