### ISSUE TITLE
Remove `SubEquipment` in the substation plugin

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#964]
As a user of OpenSCD I want to remove the `SubEquipment` element in the substation plugin

**Requirements**
- add icon button to header of sub equipment container in the substation plugin
- remove the `SubEquipment` element including its children from the project
- make sure to re-render after removal

**Comment by marcvanraalte** [comment]
Remove SubEquipment in the substation plugin closed.

**Comment by marcvanraalte** [comment]
Remove SubEquipment in the substation plugin
