### ISSUE TITLE
Remove `GeneralEquipment` in substation plugin

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#978]
As a user of OpenSCD I want to remove the `GeneralEquipment` element in the substation plugin

**Requirements**
- add icon button to header of general equipment container in the substation plugin
- remove the `GeneralEquipment` element including its children from the project
- make sure to re-render after removal

**Comment by marcvanraalte** [comment]
Remove GeneralEquipment in substation closed.
