### ISSUE TITLE
Add "add" button to the general equipemnt container in the substation plugin

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#979]
As a user of OpenSCD I want to add possible child element `LNode` and `EqFunction` to the `GeneralEquipment` parent.

**Requirements**
- add `playlist_add` button to the general equipment editor in the substation plugin
- show menu in icon button click: selection based on allowed children AND existing create wizards in the wizard-library
- open the create wizard for the selected element

**Comment by marcvanraalte** [comment]
Add "add" button to the general equipemnt container closed.
