### ISSUE TITLE
Add read-only line editor in the substation plugin

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#980]
As a user of OpenSCD I want to see `Line` element in the SCL in the substation plugin

**Requirements**
- make use of `action-pnae`
- title is "Line.name — Line.desc (Line>Voltage.innerText+Line>Voltage.multiplier)"
- show in all possible parents that is `Process`, `SCL` 
- show all possible children, that is: `ConductingEquipment`, `GeneralEquipment`
- show all hiden children with showfunction=true that is `Function`, `LNode`

**Comment by pascalwilbrink** [comment]
According to the XSD, the `Line` element is a sibling of the `Substation` element. Should this really be in the substation editor, or should this become a new plugin? (Same with Process)
