### ISSUE TITLE
Editing features are not working under the publisher menu of OpenSCD

### ISSUE THREAD

**Issue by arulrajirudayasamy** [openscd/open-scd#994]
**System Environment:**
OpenSCD V 0.22.0
Web application
Windows 10 Enterprise

**Steps to reproduce:**

- Import any one of the configured SCL file that has the definitions of dataset mapped to rcb.
- Enable the publisher menu and select the report section and try to increse or decrease the maximum client support value for one the RCB.

**Expected;**
Suggestion1: It should be reflected to one the rcbs post saving the SCL file.
Sugession2:it can also be reflected to all rcbs to make the job easier post saving the SCL file.

**Observed;**
The single changes are reflected in all the rcbs only in the OpenSCD but unfortunately not saved post saving the SCL file.

Note: Incase if the Publisher menu option is intended to provide as a read only then the edit features need to be disabled for the easy understanding of user.

Refer to the below picture attached to reproduce the problem,
![Publisher_OpenSCD](https://user-images.githubusercontent.com/97508332/188301775-3a469884-3566-4e76-96a0-f9b297bc624a.png)

**Comment by Sander3003** [comment]
@arulrajirudayasamy Thanks for your report! The publisher plug-in is work in progress. We should make this more clear!

**Comment by Sander3003** [comment]
My suggestion: rename the publisher plug-in from "publisher" to "publisher DRAFT"

**Comment by Sander3003** [comment]
@JakobVogelsang will disable the uneditable fields
